// Code generated by ent, DO NOT EDIT.

package imageobject

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the imageobject type in the database.
	Label = "image_object"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldObjectID holds the string denoting the object_id field in the database.
	FieldObjectID = "object_id"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldAPIKeyID holds the string denoting the api_key_id field in the database.
	FieldAPIKeyID = "api_key_id"
	// FieldTaskID holds the string denoting the task_id field in the database.
	FieldTaskID = "task_id"
	// FieldStorageKey holds the string denoting the storage_key field in the database.
	FieldStorageKey = "storage_key"
	// FieldContentType holds the string denoting the content_type field in the database.
	FieldContentType = "content_type"
	// FieldByteSize holds the string denoting the byte_size field in the database.
	FieldByteSize = "byte_size"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// Table holds the table name of the imageobject in the database.
	Table = "image_objects"
)

// Columns holds all SQL columns for imageobject fields.
var Columns = []string{
	FieldID,
	FieldObjectID,
	FieldUserID,
	FieldAPIKeyID,
	FieldTaskID,
	FieldStorageKey,
	FieldContentType,
	FieldByteSize,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// ObjectIDValidator is a validator for the "object_id" field. It is called by the builders before save.
	ObjectIDValidator func(string) error
	// TaskIDValidator is a validator for the "task_id" field. It is called by the builders before save.
	TaskIDValidator func(string) error
	// StorageKeyValidator is a validator for the "storage_key" field. It is called by the builders before save.
	StorageKeyValidator func(string) error
	// DefaultContentType holds the default value on creation for the "content_type" field.
	DefaultContentType string
	// ContentTypeValidator is a validator for the "content_type" field. It is called by the builders before save.
	ContentTypeValidator func(string) error
	// ByteSizeValidator is a validator for the "byte_size" field. It is called by the builders before save.
	ByteSizeValidator func(int64) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)

// OrderOption defines the ordering options for the ImageObject queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByObjectID orders the results by the object_id field.
func ByObjectID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldObjectID, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByAPIKeyID orders the results by the api_key_id field.
func ByAPIKeyID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAPIKeyID, opts...).ToFunc()
}

// ByTaskID orders the results by the task_id field.
func ByTaskID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTaskID, opts...).ToFunc()
}

// ByStorageKey orders the results by the storage_key field.
func ByStorageKey(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStorageKey, opts...).ToFunc()
}

// ByContentType orders the results by the content_type field.
func ByContentType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldContentType, opts...).ToFunc()
}

// ByByteSize orders the results by the byte_size field.
func ByByteSize(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldByteSize, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}
