// Code generated by ent, DO NOT EDIT.

package teamownershiptransfer

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/LuckyKuang/sub2api-plus/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.TeamOwnershipTransfer {
	return predicate.TeamOwnershipTransfer(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.TeamOwnershipTransfer {
	return predicate.TeamOwnershipTransfer(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.TeamOwnershipTransfer {
	return predicate.TeamOwnershipTransfer(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.TeamOwnershipTransfer {
	return predicate.TeamOwnershipTransfer(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.TeamOwnershipTransfer {
	return predicate.TeamOwnershipTransfer(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.TeamOwnershipTransfer {
	return predicate.TeamOwnershipTransfer(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.TeamOwnershipTransfer {
	return predicate.TeamOwnershipTransfer(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.TeamOwnershipTransfer {
	return predicate.TeamOwnershipTransfer(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.TeamOwnershipTransfer {
	return predicate.TeamOwnershipTransfer(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.TeamOwnershipTransfer {
	return predicate.TeamOwnershipTransfer(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.TeamOwnershipTransfer {
	return predicate.TeamOwnershipTransfer(sql.FieldEQ(FieldUpdatedAt, v))
}

// TeamID applies equality check predicate on the "team_id" field. It's identical to TeamIDEQ.
func TeamID(v int64) predicate.TeamOwnershipTransfer {
	return predicate.TeamOwnershipTransfer(sql.FieldEQ(FieldTeamID, v))
}

// FromUserID applies equality check predicate on the "from_user_id" field. It's identical to FromUserIDEQ.
func FromUserID(v int64) predicate.TeamOwnershipTransfer {
	return predicate.TeamOwnershipTransfer(sql.FieldEQ(FieldFromUserID, v))
}

// ToUserID applies equality check predicate on the "to_user_id" field. It's identical to ToUserIDEQ.
func ToUserID(v int64) predicate.TeamOwnershipTransfer {
	return predicate.TeamOwnershipTransfer(sql.FieldEQ(FieldToUserID, v))
}

// TokenHash applies equality check predicate on the "token_hash" field. It's identical to TokenHashEQ.
func TokenHash(v string) predicate.TeamOwnershipTransfer {
	return predicate.TeamOwnershipTransfer(sql.FieldEQ(FieldTokenHash, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.TeamOwnershipTransfer {
	return predicate.TeamOwnershipTransfer(sql.FieldEQ(FieldStatus, v))
}

// ExpiresAt applies equality check predicate on the "expires_at" field. It's identical to ExpiresAtEQ.
func ExpiresAt(v time.Time) predicate.TeamOwnershipTransfer {
	return predicate.TeamOwnershipTransfer(sql.FieldEQ(FieldExpiresAt, v))
}

// ResolvedAt applies equality check predicate on the "resolved_at" field. It's identical to ResolvedAtEQ.
func ResolvedAt(v time.Time) predicate.TeamOwnershipTransfer {
	return predicate.TeamOwnershipTransfer(sql.FieldEQ(FieldResolvedAt, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.TeamOwnershipTransfer {
	return predicate.TeamOwnershipTransfer(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.TeamOwnershipTransfer {
	return predicate.TeamOwnershipTransfer(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.TeamOwnershipTransfer {
	return predicate.TeamOwnershipTransfer(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.TeamOwnershipTransfer {
	return predicate.TeamOwnershipTransfer(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.TeamOwnershipTransfer {
	return predicate.TeamOwnershipTransfer(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.TeamOwnershipTransfer {
	return predicate.TeamOwnershipTransfer(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.TeamOwnershipTransfer {
	return predicate.TeamOwnershipTransfer(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.TeamOwnershipTransfer {
	return predicate.TeamOwnershipTransfer(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.TeamOwnershipTransfer {
	return predicate.TeamOwnershipTransfer(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.TeamOwnershipTransfer {
	return predicate.TeamOwnershipTransfer(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.TeamOwnershipTransfer {
	return predicate.TeamOwnershipTransfer(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.TeamOwnershipTransfer {
	return predicate.TeamOwnershipTransfer(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.TeamOwnershipTransfer {
	return predicate.TeamOwnershipTransfer(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.TeamOwnershipTransfer {
	return predicate.TeamOwnershipTransfer(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.TeamOwnershipTransfer {
	return predicate.TeamOwnershipTransfer(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.TeamOwnershipTransfer {
	return predicate.TeamOwnershipTransfer(sql.FieldLTE(FieldUpdatedAt, v))
}

// TeamIDEQ applies the EQ predicate on the "team_id" field.
func TeamIDEQ(v int64) predicate.TeamOwnershipTransfer {
	return predicate.TeamOwnershipTransfer(sql.FieldEQ(FieldTeamID, v))
}

// TeamIDNEQ applies the NEQ predicate on the "team_id" field.
func TeamIDNEQ(v int64) predicate.TeamOwnershipTransfer {
	return predicate.TeamOwnershipTransfer(sql.FieldNEQ(FieldTeamID, v))
}

// TeamIDIn applies the In predicate on the "team_id" field.
func TeamIDIn(vs ...int64) predicate.TeamOwnershipTransfer {
	return predicate.TeamOwnershipTransfer(sql.FieldIn(FieldTeamID, vs...))
}

// TeamIDNotIn applies the NotIn predicate on the "team_id" field.
func TeamIDNotIn(vs ...int64) predicate.TeamOwnershipTransfer {
	return predicate.TeamOwnershipTransfer(sql.FieldNotIn(FieldTeamID, vs...))
}

// FromUserIDEQ applies the EQ predicate on the "from_user_id" field.
func FromUserIDEQ(v int64) predicate.TeamOwnershipTransfer {
	return predicate.TeamOwnershipTransfer(sql.FieldEQ(FieldFromUserID, v))
}

// FromUserIDNEQ applies the NEQ predicate on the "from_user_id" field.
func FromUserIDNEQ(v int64) predicate.TeamOwnershipTransfer {
	return predicate.TeamOwnershipTransfer(sql.FieldNEQ(FieldFromUserID, v))
}

// FromUserIDIn applies the In predicate on the "from_user_id" field.
func FromUserIDIn(vs ...int64) predicate.TeamOwnershipTransfer {
	return predicate.TeamOwnershipTransfer(sql.FieldIn(FieldFromUserID, vs...))
}

// FromUserIDNotIn applies the NotIn predicate on the "from_user_id" field.
func FromUserIDNotIn(vs ...int64) predicate.TeamOwnershipTransfer {
	return predicate.TeamOwnershipTransfer(sql.FieldNotIn(FieldFromUserID, vs...))
}

// FromUserIDGT applies the GT predicate on the "from_user_id" field.
func FromUserIDGT(v int64) predicate.TeamOwnershipTransfer {
	return predicate.TeamOwnershipTransfer(sql.FieldGT(FieldFromUserID, v))
}

// FromUserIDGTE applies the GTE predicate on the "from_user_id" field.
func FromUserIDGTE(v int64) predicate.TeamOwnershipTransfer {
	return predicate.TeamOwnershipTransfer(sql.FieldGTE(FieldFromUserID, v))
}

// FromUserIDLT applies the LT predicate on the "from_user_id" field.
func FromUserIDLT(v int64) predicate.TeamOwnershipTransfer {
	return predicate.TeamOwnershipTransfer(sql.FieldLT(FieldFromUserID, v))
}

// FromUserIDLTE applies the LTE predicate on the "from_user_id" field.
func FromUserIDLTE(v int64) predicate.TeamOwnershipTransfer {
	return predicate.TeamOwnershipTransfer(sql.FieldLTE(FieldFromUserID, v))
}

// ToUserIDEQ applies the EQ predicate on the "to_user_id" field.
func ToUserIDEQ(v int64) predicate.TeamOwnershipTransfer {
	return predicate.TeamOwnershipTransfer(sql.FieldEQ(FieldToUserID, v))
}

// ToUserIDNEQ applies the NEQ predicate on the "to_user_id" field.
func ToUserIDNEQ(v int64) predicate.TeamOwnershipTransfer {
	return predicate.TeamOwnershipTransfer(sql.FieldNEQ(FieldToUserID, v))
}

// ToUserIDIn applies the In predicate on the "to_user_id" field.
func ToUserIDIn(vs ...int64) predicate.TeamOwnershipTransfer {
	return predicate.TeamOwnershipTransfer(sql.FieldIn(FieldToUserID, vs...))
}

// ToUserIDNotIn applies the NotIn predicate on the "to_user_id" field.
func ToUserIDNotIn(vs ...int64) predicate.TeamOwnershipTransfer {
	return predicate.TeamOwnershipTransfer(sql.FieldNotIn(FieldToUserID, vs...))
}

// ToUserIDGT applies the GT predicate on the "to_user_id" field.
func ToUserIDGT(v int64) predicate.TeamOwnershipTransfer {
	return predicate.TeamOwnershipTransfer(sql.FieldGT(FieldToUserID, v))
}

// ToUserIDGTE applies the GTE predicate on the "to_user_id" field.
func ToUserIDGTE(v int64) predicate.TeamOwnershipTransfer {
	return predicate.TeamOwnershipTransfer(sql.FieldGTE(FieldToUserID, v))
}

// ToUserIDLT applies the LT predicate on the "to_user_id" field.
func ToUserIDLT(v int64) predicate.TeamOwnershipTransfer {
	return predicate.TeamOwnershipTransfer(sql.FieldLT(FieldToUserID, v))
}

// ToUserIDLTE applies the LTE predicate on the "to_user_id" field.
func ToUserIDLTE(v int64) predicate.TeamOwnershipTransfer {
	return predicate.TeamOwnershipTransfer(sql.FieldLTE(FieldToUserID, v))
}

// TokenHashEQ applies the EQ predicate on the "token_hash" field.
func TokenHashEQ(v string) predicate.TeamOwnershipTransfer {
	return predicate.TeamOwnershipTransfer(sql.FieldEQ(FieldTokenHash, v))
}

// TokenHashNEQ applies the NEQ predicate on the "token_hash" field.
func TokenHashNEQ(v string) predicate.TeamOwnershipTransfer {
	return predicate.TeamOwnershipTransfer(sql.FieldNEQ(FieldTokenHash, v))
}

// TokenHashIn applies the In predicate on the "token_hash" field.
func TokenHashIn(vs ...string) predicate.TeamOwnershipTransfer {
	return predicate.TeamOwnershipTransfer(sql.FieldIn(FieldTokenHash, vs...))
}

// TokenHashNotIn applies the NotIn predicate on the "token_hash" field.
func TokenHashNotIn(vs ...string) predicate.TeamOwnershipTransfer {
	return predicate.TeamOwnershipTransfer(sql.FieldNotIn(FieldTokenHash, vs...))
}

// TokenHashGT applies the GT predicate on the "token_hash" field.
func TokenHashGT(v string) predicate.TeamOwnershipTransfer {
	return predicate.TeamOwnershipTransfer(sql.FieldGT(FieldTokenHash, v))
}

// TokenHashGTE applies the GTE predicate on the "token_hash" field.
func TokenHashGTE(v string) predicate.TeamOwnershipTransfer {
	return predicate.TeamOwnershipTransfer(sql.FieldGTE(FieldTokenHash, v))
}

// TokenHashLT applies the LT predicate on the "token_hash" field.
func TokenHashLT(v string) predicate.TeamOwnershipTransfer {
	return predicate.TeamOwnershipTransfer(sql.FieldLT(FieldTokenHash, v))
}

// TokenHashLTE applies the LTE predicate on the "token_hash" field.
func TokenHashLTE(v string) predicate.TeamOwnershipTransfer {
	return predicate.TeamOwnershipTransfer(sql.FieldLTE(FieldTokenHash, v))
}

// TokenHashContains applies the Contains predicate on the "token_hash" field.
func TokenHashContains(v string) predicate.TeamOwnershipTransfer {
	return predicate.TeamOwnershipTransfer(sql.FieldContains(FieldTokenHash, v))
}

// TokenHashHasPrefix applies the HasPrefix predicate on the "token_hash" field.
func TokenHashHasPrefix(v string) predicate.TeamOwnershipTransfer {
	return predicate.TeamOwnershipTransfer(sql.FieldHasPrefix(FieldTokenHash, v))
}

// TokenHashHasSuffix applies the HasSuffix predicate on the "token_hash" field.
func TokenHashHasSuffix(v string) predicate.TeamOwnershipTransfer {
	return predicate.TeamOwnershipTransfer(sql.FieldHasSuffix(FieldTokenHash, v))
}

// TokenHashEqualFold applies the EqualFold predicate on the "token_hash" field.
func TokenHashEqualFold(v string) predicate.TeamOwnershipTransfer {
	return predicate.TeamOwnershipTransfer(sql.FieldEqualFold(FieldTokenHash, v))
}

// TokenHashContainsFold applies the ContainsFold predicate on the "token_hash" field.
func TokenHashContainsFold(v string) predicate.TeamOwnershipTransfer {
	return predicate.TeamOwnershipTransfer(sql.FieldContainsFold(FieldTokenHash, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.TeamOwnershipTransfer {
	return predicate.TeamOwnershipTransfer(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.TeamOwnershipTransfer {
	return predicate.TeamOwnershipTransfer(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.TeamOwnershipTransfer {
	return predicate.TeamOwnershipTransfer(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.TeamOwnershipTransfer {
	return predicate.TeamOwnershipTransfer(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.TeamOwnershipTransfer {
	return predicate.TeamOwnershipTransfer(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.TeamOwnershipTransfer {
	return predicate.TeamOwnershipTransfer(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.TeamOwnershipTransfer {
	return predicate.TeamOwnershipTransfer(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.TeamOwnershipTransfer {
	return predicate.TeamOwnershipTransfer(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.TeamOwnershipTransfer {
	return predicate.TeamOwnershipTransfer(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.TeamOwnershipTransfer {
	return predicate.TeamOwnershipTransfer(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.TeamOwnershipTransfer {
	return predicate.TeamOwnershipTransfer(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.TeamOwnershipTransfer {
	return predicate.TeamOwnershipTransfer(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.TeamOwnershipTransfer {
	return predicate.TeamOwnershipTransfer(sql.FieldContainsFold(FieldStatus, v))
}

// ExpiresAtEQ applies the EQ predicate on the "expires_at" field.
func ExpiresAtEQ(v time.Time) predicate.TeamOwnershipTransfer {
	return predicate.TeamOwnershipTransfer(sql.FieldEQ(FieldExpiresAt, v))
}

// ExpiresAtNEQ applies the NEQ predicate on the "expires_at" field.
func ExpiresAtNEQ(v time.Time) predicate.TeamOwnershipTransfer {
	return predicate.TeamOwnershipTransfer(sql.FieldNEQ(FieldExpiresAt, v))
}

// ExpiresAtIn applies the In predicate on the "expires_at" field.
func ExpiresAtIn(vs ...time.Time) predicate.TeamOwnershipTransfer {
	return predicate.TeamOwnershipTransfer(sql.FieldIn(FieldExpiresAt, vs...))
}

// ExpiresAtNotIn applies the NotIn predicate on the "expires_at" field.
func ExpiresAtNotIn(vs ...time.Time) predicate.TeamOwnershipTransfer {
	return predicate.TeamOwnershipTransfer(sql.FieldNotIn(FieldExpiresAt, vs...))
}

// ExpiresAtGT applies the GT predicate on the "expires_at" field.
func ExpiresAtGT(v time.Time) predicate.TeamOwnershipTransfer {
	return predicate.TeamOwnershipTransfer(sql.FieldGT(FieldExpiresAt, v))
}

// ExpiresAtGTE applies the GTE predicate on the "expires_at" field.
func ExpiresAtGTE(v time.Time) predicate.TeamOwnershipTransfer {
	return predicate.TeamOwnershipTransfer(sql.FieldGTE(FieldExpiresAt, v))
}

// ExpiresAtLT applies the LT predicate on the "expires_at" field.
func ExpiresAtLT(v time.Time) predicate.TeamOwnershipTransfer {
	return predicate.TeamOwnershipTransfer(sql.FieldLT(FieldExpiresAt, v))
}

// ExpiresAtLTE applies the LTE predicate on the "expires_at" field.
func ExpiresAtLTE(v time.Time) predicate.TeamOwnershipTransfer {
	return predicate.TeamOwnershipTransfer(sql.FieldLTE(FieldExpiresAt, v))
}

// ResolvedAtEQ applies the EQ predicate on the "resolved_at" field.
func ResolvedAtEQ(v time.Time) predicate.TeamOwnershipTransfer {
	return predicate.TeamOwnershipTransfer(sql.FieldEQ(FieldResolvedAt, v))
}

// ResolvedAtNEQ applies the NEQ predicate on the "resolved_at" field.
func ResolvedAtNEQ(v time.Time) predicate.TeamOwnershipTransfer {
	return predicate.TeamOwnershipTransfer(sql.FieldNEQ(FieldResolvedAt, v))
}

// ResolvedAtIn applies the In predicate on the "resolved_at" field.
func ResolvedAtIn(vs ...time.Time) predicate.TeamOwnershipTransfer {
	return predicate.TeamOwnershipTransfer(sql.FieldIn(FieldResolvedAt, vs...))
}

// ResolvedAtNotIn applies the NotIn predicate on the "resolved_at" field.
func ResolvedAtNotIn(vs ...time.Time) predicate.TeamOwnershipTransfer {
	return predicate.TeamOwnershipTransfer(sql.FieldNotIn(FieldResolvedAt, vs...))
}

// ResolvedAtGT applies the GT predicate on the "resolved_at" field.
func ResolvedAtGT(v time.Time) predicate.TeamOwnershipTransfer {
	return predicate.TeamOwnershipTransfer(sql.FieldGT(FieldResolvedAt, v))
}

// ResolvedAtGTE applies the GTE predicate on the "resolved_at" field.
func ResolvedAtGTE(v time.Time) predicate.TeamOwnershipTransfer {
	return predicate.TeamOwnershipTransfer(sql.FieldGTE(FieldResolvedAt, v))
}

// ResolvedAtLT applies the LT predicate on the "resolved_at" field.
func ResolvedAtLT(v time.Time) predicate.TeamOwnershipTransfer {
	return predicate.TeamOwnershipTransfer(sql.FieldLT(FieldResolvedAt, v))
}

// ResolvedAtLTE applies the LTE predicate on the "resolved_at" field.
func ResolvedAtLTE(v time.Time) predicate.TeamOwnershipTransfer {
	return predicate.TeamOwnershipTransfer(sql.FieldLTE(FieldResolvedAt, v))
}

// ResolvedAtIsNil applies the IsNil predicate on the "resolved_at" field.
func ResolvedAtIsNil() predicate.TeamOwnershipTransfer {
	return predicate.TeamOwnershipTransfer(sql.FieldIsNull(FieldResolvedAt))
}

// ResolvedAtNotNil applies the NotNil predicate on the "resolved_at" field.
func ResolvedAtNotNil() predicate.TeamOwnershipTransfer {
	return predicate.TeamOwnershipTransfer(sql.FieldNotNull(FieldResolvedAt))
}

// HasTeam applies the HasEdge predicate on the "team" edge.
func HasTeam() predicate.TeamOwnershipTransfer {
	return predicate.TeamOwnershipTransfer(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, TeamTable, TeamColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTeamWith applies the HasEdge predicate on the "team" edge with a given conditions (other predicates).
func HasTeamWith(preds ...predicate.Team) predicate.TeamOwnershipTransfer {
	return predicate.TeamOwnershipTransfer(func(s *sql.Selector) {
		step := newTeamStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.TeamOwnershipTransfer) predicate.TeamOwnershipTransfer {
	return predicate.TeamOwnershipTransfer(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.TeamOwnershipTransfer) predicate.TeamOwnershipTransfer {
	return predicate.TeamOwnershipTransfer(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.TeamOwnershipTransfer) predicate.TeamOwnershipTransfer {
	return predicate.TeamOwnershipTransfer(sql.NotPredicates(p))
}
