package routes

import (
	"github.com/LuckyKuang/sub2api-plus/internal/handler"
	"github.com/LuckyKuang/sub2api-plus/internal/service"
	"github.com/gin-gonic/gin"
)

// Support reads reuse the ordinary user handlers and response models. Only
// these explicitly declared GET routes receive a separately validated target.
func registerAdminSupportRoutes(admin *gin.RouterGroup, h *handler.Handlers, settings *service.SettingService) {
	support := admin.Group("/support/users/:user_id")
	support.Use(h.Admin.User.RequireSupportTarget)
	registerAdminSupportGotoccRoutes(support, h)
	support.GET("/user/profile", h.User.GetProfile)
	support.GET("/user/platform-quotas", h.User.GetMyPlatformQuotas)
	support.GET("/user/aff", h.User.GetAffiliate)
	support.GET("/user/totp/status", h.Totp.GetStatus)
	support.GET("/user/totp/verification-method", h.Totp.GetVerificationMethod)
	support.GET("/user/passkeys", h.Passkey.List)
	support.GET("/user/api-keys/:id/usage/daily", h.Usage.GetMyAPIKeyDailyUsage)
	support.GET("/keys", h.APIKey.List)
	support.GET("/keys/:id", h.APIKey.GetByID)
	support.GET("/groups/available", h.APIKey.GetAvailableGroups)
	support.GET("/groups/rates", h.APIKey.GetUserGroupRates)
	support.GET("/channels/available", h.AvailableChannel.List)
	support.GET("/usage", h.Usage.List)
	support.GET("/usage/errors", h.Usage.ListErrors)
	support.GET("/usage/errors/:id", h.Usage.GetErrorDetail)
	support.GET("/usage/:id", h.Usage.GetByID)
	support.GET("/usage/stats", h.Usage.Stats)
	support.GET("/usage/dashboard/stats", h.Usage.DashboardStats)
	support.GET("/usage/dashboard/trend", h.Usage.DashboardTrend)
	support.GET("/usage/dashboard/models", h.Usage.DashboardModels)
	support.GET("/usage/dashboard/snapshot-v2", h.Usage.DashboardSnapshotV2)
	support.GET("/usage/dashboard/api-keys-usage", h.Usage.DashboardAPIKeysUsage)
	support.GET("/announcements", h.Announcement.List)
	support.GET("/redeem/history", h.Redeem.GetHistory)
	support.GET("/subscriptions", h.Subscription.List)
	support.GET("/subscriptions/active", h.Subscription.GetActive)
	support.GET("/subscriptions/progress", h.Subscription.GetProgress)
	support.GET("/subscriptions/summary", h.Subscription.GetSummary)
	support.GET("/channel-monitors", h.ChannelMonitor.List)
	support.GET("/channel-monitors/:id/status", h.ChannelMonitor.GetStatus)
	v2 := support.Group("/channel-monitor-v2", channelMonitorModeV2Guard(settings))
	v2.GET("/dimensions", h.ChannelMonitorV2.Dimensions)
	v2.GET("/snapshot", h.ChannelMonitorV2.Snapshot)
	v2.GET("/models", h.ChannelMonitorV2.Models)
	v2.GET("/matrix", h.ChannelMonitorV2.Matrix)
	v2.GET("/errors", h.ChannelMonitorV2.Errors)
	v2.GET("/users", h.ChannelMonitorV2.Users)
	support.GET("/channel-monitor-v3/snapshot", channelMonitorModeV3Guard(settings), h.ChannelMonitorV3.Snapshot)
	support.GET("/payment/config", h.Payment.GetPaymentConfig)
	support.GET("/payment/checkout-info", h.Payment.GetCheckoutInfo)
	support.GET("/payment/plans", h.Payment.GetPlans)
	support.GET("/payment/limits", h.Payment.GetLimits)
	support.GET("/payment/orders/my", h.Payment.GetMyOrders)
	support.GET("/payment/orders/refund-eligible-providers", h.Payment.GetRefundEligibleProviders)
	support.GET("/payment/orders/:id", h.Payment.GetOrder)

	images := support.Group("/images", h.APIKey.RequireSupportImageKey)
	images.GET("/models", func(c *gin.Context) { dispatchModelsGateway(c, h) })
	images.GET("/tasks", h.AsyncImage.List)
	images.GET("/tasks/:task_id", h.AsyncImage.Get)
	images.GET("/tasks/:task_id/download", h.AsyncImage.Download)
	images.GET("/batches", h.BatchImage.List)
	images.GET("/batches/models", h.BatchImage.Models)
	images.GET("/batches/:id", h.BatchImage.Get)
	images.GET("/batches/:id/items", h.BatchImage.Items)
	images.GET("/batches/:id/items/:custom_id/content", h.BatchImage.ItemContent)
	images.GET("/batches/:id/download", h.BatchImage.Download)
}
