// Code generated by ent, DO NOT EDIT.

package openaivideotask

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the openaivideotask type in the database.
	Label = "open_ai_video_task"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldLocalRequestID holds the string denoting the local_request_id field in the database.
	FieldLocalRequestID = "local_request_id"
	// FieldTaskID holds the string denoting the task_id field in the database.
	FieldTaskID = "task_id"
	// FieldActorUserID holds the string denoting the actor_user_id field in the database.
	FieldActorUserID = "actor_user_id"
	// FieldBillingUserID holds the string denoting the billing_user_id field in the database.
	FieldBillingUserID = "billing_user_id"
	// FieldTeamID holds the string denoting the team_id field in the database.
	FieldTeamID = "team_id"
	// FieldAPIKeyID holds the string denoting the api_key_id field in the database.
	FieldAPIKeyID = "api_key_id"
	// FieldGroupID holds the string denoting the group_id field in the database.
	FieldGroupID = "group_id"
	// FieldChannelID holds the string denoting the channel_id field in the database.
	FieldChannelID = "channel_id"
	// FieldAccountID holds the string denoting the account_id field in the database.
	FieldAccountID = "account_id"
	// FieldSubscriptionID holds the string denoting the subscription_id field in the database.
	FieldSubscriptionID = "subscription_id"
	// FieldRequestedModel holds the string denoting the requested_model field in the database.
	FieldRequestedModel = "requested_model"
	// FieldUpstreamModel holds the string denoting the upstream_model field in the database.
	FieldUpstreamModel = "upstream_model"
	// FieldRequestSeconds holds the string denoting the request_seconds field in the database.
	FieldRequestSeconds = "request_seconds"
	// FieldResolution holds the string denoting the resolution field in the database.
	FieldResolution = "resolution"
	// FieldBillingMode holds the string denoting the billing_mode field in the database.
	FieldBillingMode = "billing_mode"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldUpstreamStatus holds the string denoting the upstream_status field in the database.
	FieldUpstreamStatus = "upstream_status"
	// FieldBillingType holds the string denoting the billing_type field in the database.
	FieldBillingType = "billing_type"
	// FieldBillingStatus holds the string denoting the billing_status field in the database.
	FieldBillingStatus = "billing_status"
	// FieldTotalCost holds the string denoting the total_cost field in the database.
	FieldTotalCost = "total_cost"
	// FieldActualCost holds the string denoting the actual_cost field in the database.
	FieldActualCost = "actual_cost"
	// FieldHoldAmount holds the string denoting the hold_amount field in the database.
	FieldHoldAmount = "hold_amount"
	// FieldGroupRateMultiplier holds the string denoting the group_rate_multiplier field in the database.
	FieldGroupRateMultiplier = "group_rate_multiplier"
	// FieldAccountRateMultiplier holds the string denoting the account_rate_multiplier field in the database.
	FieldAccountRateMultiplier = "account_rate_multiplier"
	// FieldAllowanceReserved holds the string denoting the allowance_reserved field in the database.
	FieldAllowanceReserved = "allowance_reserved"
	// FieldRequestPayloadHash holds the string denoting the request_payload_hash field in the database.
	FieldRequestPayloadHash = "request_payload_hash"
	// FieldInboundEndpoint holds the string denoting the inbound_endpoint field in the database.
	FieldInboundEndpoint = "inbound_endpoint"
	// FieldUpstreamEndpoint holds the string denoting the upstream_endpoint field in the database.
	FieldUpstreamEndpoint = "upstream_endpoint"
	// FieldModelMappingChain holds the string denoting the model_mapping_chain field in the database.
	FieldModelMappingChain = "model_mapping_chain"
	// FieldUserAgent holds the string denoting the user_agent field in the database.
	FieldUserAgent = "user_agent"
	// FieldIPAddress holds the string denoting the ip_address field in the database.
	FieldIPAddress = "ip_address"
	// FieldRetryCount holds the string denoting the retry_count field in the database.
	FieldRetryCount = "retry_count"
	// FieldNextPollAt holds the string denoting the next_poll_at field in the database.
	FieldNextPollAt = "next_poll_at"
	// FieldLeaseUntil holds the string denoting the lease_until field in the database.
	FieldLeaseUntil = "lease_until"
	// FieldLeaseToken holds the string denoting the lease_token field in the database.
	FieldLeaseToken = "lease_token"
	// FieldLastErrorCode holds the string denoting the last_error_code field in the database.
	FieldLastErrorCode = "last_error_code"
	// FieldLastErrorMessage holds the string denoting the last_error_message field in the database.
	FieldLastErrorMessage = "last_error_message"
	// FieldUsageRecorded holds the string denoting the usage_recorded field in the database.
	FieldUsageRecorded = "usage_recorded"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldSubmittedAt holds the string denoting the submitted_at field in the database.
	FieldSubmittedAt = "submitted_at"
	// FieldFinishedAt holds the string denoting the finished_at field in the database.
	FieldFinishedAt = "finished_at"
	// FieldSettledAt holds the string denoting the settled_at field in the database.
	FieldSettledAt = "settled_at"
	// FieldUsageRecordedAt holds the string denoting the usage_recorded_at field in the database.
	FieldUsageRecordedAt = "usage_recorded_at"
	// Table holds the table name of the openaivideotask in the database.
	Table = "openai_video_tasks"
)

// Columns holds all SQL columns for openaivideotask fields.
var Columns = []string{
	FieldID,
	FieldLocalRequestID,
	FieldTaskID,
	FieldActorUserID,
	FieldBillingUserID,
	FieldTeamID,
	FieldAPIKeyID,
	FieldGroupID,
	FieldChannelID,
	FieldAccountID,
	FieldSubscriptionID,
	FieldRequestedModel,
	FieldUpstreamModel,
	FieldRequestSeconds,
	FieldResolution,
	FieldBillingMode,
	FieldStatus,
	FieldUpstreamStatus,
	FieldBillingType,
	FieldBillingStatus,
	FieldTotalCost,
	FieldActualCost,
	FieldHoldAmount,
	FieldGroupRateMultiplier,
	FieldAccountRateMultiplier,
	FieldAllowanceReserved,
	FieldRequestPayloadHash,
	FieldInboundEndpoint,
	FieldUpstreamEndpoint,
	FieldModelMappingChain,
	FieldUserAgent,
	FieldIPAddress,
	FieldRetryCount,
	FieldNextPollAt,
	FieldLeaseUntil,
	FieldLeaseToken,
	FieldLastErrorCode,
	FieldLastErrorMessage,
	FieldUsageRecorded,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldSubmittedAt,
	FieldFinishedAt,
	FieldSettledAt,
	FieldUsageRecordedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// LocalRequestIDValidator is a validator for the "local_request_id" field. It is called by the builders before save.
	LocalRequestIDValidator func(string) error
	// TaskIDValidator is a validator for the "task_id" field. It is called by the builders before save.
	TaskIDValidator func(string) error
	// RequestedModelValidator is a validator for the "requested_model" field. It is called by the builders before save.
	RequestedModelValidator func(string) error
	// UpstreamModelValidator is a validator for the "upstream_model" field. It is called by the builders before save.
	UpstreamModelValidator func(string) error
	// ResolutionValidator is a validator for the "resolution" field. It is called by the builders before save.
	ResolutionValidator func(string) error
	// BillingModeValidator is a validator for the "billing_mode" field. It is called by the builders before save.
	BillingModeValidator func(string) error
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
	// StatusValidator is a validator for the "status" field. It is called by the builders before save.
	StatusValidator func(string) error
	// UpstreamStatusValidator is a validator for the "upstream_status" field. It is called by the builders before save.
	UpstreamStatusValidator func(string) error
	// DefaultBillingStatus holds the default value on creation for the "billing_status" field.
	DefaultBillingStatus string
	// BillingStatusValidator is a validator for the "billing_status" field. It is called by the builders before save.
	BillingStatusValidator func(string) error
	// DefaultTotalCost holds the default value on creation for the "total_cost" field.
	DefaultTotalCost float64
	// DefaultHoldAmount holds the default value on creation for the "hold_amount" field.
	DefaultHoldAmount float64
	// DefaultGroupRateMultiplier holds the default value on creation for the "group_rate_multiplier" field.
	DefaultGroupRateMultiplier float64
	// DefaultAccountRateMultiplier holds the default value on creation for the "account_rate_multiplier" field.
	DefaultAccountRateMultiplier float64
	// DefaultAllowanceReserved holds the default value on creation for the "allowance_reserved" field.
	DefaultAllowanceReserved bool
	// RequestPayloadHashValidator is a validator for the "request_payload_hash" field. It is called by the builders before save.
	RequestPayloadHashValidator func(string) error
	// InboundEndpointValidator is a validator for the "inbound_endpoint" field. It is called by the builders before save.
	InboundEndpointValidator func(string) error
	// UpstreamEndpointValidator is a validator for the "upstream_endpoint" field. It is called by the builders before save.
	UpstreamEndpointValidator func(string) error
	// ModelMappingChainValidator is a validator for the "model_mapping_chain" field. It is called by the builders before save.
	ModelMappingChainValidator func(string) error
	// IPAddressValidator is a validator for the "ip_address" field. It is called by the builders before save.
	IPAddressValidator func(string) error
	// DefaultRetryCount holds the default value on creation for the "retry_count" field.
	DefaultRetryCount int
	// LeaseTokenValidator is a validator for the "lease_token" field. It is called by the builders before save.
	LeaseTokenValidator func(string) error
	// LastErrorCodeValidator is a validator for the "last_error_code" field. It is called by the builders before save.
	LastErrorCodeValidator func(string) error
	// DefaultUsageRecorded holds the default value on creation for the "usage_recorded" field.
	DefaultUsageRecorded bool
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the OpenAIVideoTask queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByLocalRequestID orders the results by the local_request_id field.
func ByLocalRequestID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLocalRequestID, opts...).ToFunc()
}

// ByTaskID orders the results by the task_id field.
func ByTaskID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTaskID, opts...).ToFunc()
}

// ByActorUserID orders the results by the actor_user_id field.
func ByActorUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldActorUserID, opts...).ToFunc()
}

// ByBillingUserID orders the results by the billing_user_id field.
func ByBillingUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBillingUserID, opts...).ToFunc()
}

// ByTeamID orders the results by the team_id field.
func ByTeamID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTeamID, opts...).ToFunc()
}

// ByAPIKeyID orders the results by the api_key_id field.
func ByAPIKeyID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAPIKeyID, opts...).ToFunc()
}

// ByGroupID orders the results by the group_id field.
func ByGroupID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGroupID, opts...).ToFunc()
}

// ByChannelID orders the results by the channel_id field.
func ByChannelID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldChannelID, opts...).ToFunc()
}

// ByAccountID orders the results by the account_id field.
func ByAccountID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAccountID, opts...).ToFunc()
}

// BySubscriptionID orders the results by the subscription_id field.
func BySubscriptionID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSubscriptionID, opts...).ToFunc()
}

// ByRequestedModel orders the results by the requested_model field.
func ByRequestedModel(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRequestedModel, opts...).ToFunc()
}

// ByUpstreamModel orders the results by the upstream_model field.
func ByUpstreamModel(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpstreamModel, opts...).ToFunc()
}

// ByRequestSeconds orders the results by the request_seconds field.
func ByRequestSeconds(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRequestSeconds, opts...).ToFunc()
}

// ByResolution orders the results by the resolution field.
func ByResolution(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldResolution, opts...).ToFunc()
}

// ByBillingMode orders the results by the billing_mode field.
func ByBillingMode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBillingMode, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByUpstreamStatus orders the results by the upstream_status field.
func ByUpstreamStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpstreamStatus, opts...).ToFunc()
}

// ByBillingType orders the results by the billing_type field.
func ByBillingType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBillingType, opts...).ToFunc()
}

// ByBillingStatus orders the results by the billing_status field.
func ByBillingStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBillingStatus, opts...).ToFunc()
}

// ByTotalCost orders the results by the total_cost field.
func ByTotalCost(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTotalCost, opts...).ToFunc()
}

// ByActualCost orders the results by the actual_cost field.
func ByActualCost(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldActualCost, opts...).ToFunc()
}

// ByHoldAmount orders the results by the hold_amount field.
func ByHoldAmount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldHoldAmount, opts...).ToFunc()
}

// ByGroupRateMultiplier orders the results by the group_rate_multiplier field.
func ByGroupRateMultiplier(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGroupRateMultiplier, opts...).ToFunc()
}

// ByAccountRateMultiplier orders the results by the account_rate_multiplier field.
func ByAccountRateMultiplier(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAccountRateMultiplier, opts...).ToFunc()
}

// ByAllowanceReserved orders the results by the allowance_reserved field.
func ByAllowanceReserved(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAllowanceReserved, opts...).ToFunc()
}

// ByRequestPayloadHash orders the results by the request_payload_hash field.
func ByRequestPayloadHash(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRequestPayloadHash, opts...).ToFunc()
}

// ByInboundEndpoint orders the results by the inbound_endpoint field.
func ByInboundEndpoint(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInboundEndpoint, opts...).ToFunc()
}

// ByUpstreamEndpoint orders the results by the upstream_endpoint field.
func ByUpstreamEndpoint(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpstreamEndpoint, opts...).ToFunc()
}

// ByModelMappingChain orders the results by the model_mapping_chain field.
func ByModelMappingChain(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldModelMappingChain, opts...).ToFunc()
}

// ByUserAgent orders the results by the user_agent field.
func ByUserAgent(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserAgent, opts...).ToFunc()
}

// ByIPAddress orders the results by the ip_address field.
func ByIPAddress(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIPAddress, opts...).ToFunc()
}

// ByRetryCount orders the results by the retry_count field.
func ByRetryCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRetryCount, opts...).ToFunc()
}

// ByNextPollAt orders the results by the next_poll_at field.
func ByNextPollAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNextPollAt, opts...).ToFunc()
}

// ByLeaseUntil orders the results by the lease_until field.
func ByLeaseUntil(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLeaseUntil, opts...).ToFunc()
}

// ByLeaseToken orders the results by the lease_token field.
func ByLeaseToken(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLeaseToken, opts...).ToFunc()
}

// ByLastErrorCode orders the results by the last_error_code field.
func ByLastErrorCode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastErrorCode, opts...).ToFunc()
}

// ByLastErrorMessage orders the results by the last_error_message field.
func ByLastErrorMessage(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastErrorMessage, opts...).ToFunc()
}

// ByUsageRecorded orders the results by the usage_recorded field.
func ByUsageRecorded(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUsageRecorded, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// BySubmittedAt orders the results by the submitted_at field.
func BySubmittedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSubmittedAt, opts...).ToFunc()
}

// ByFinishedAt orders the results by the finished_at field.
func ByFinishedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFinishedAt, opts...).ToFunc()
}

// BySettledAt orders the results by the settled_at field.
func BySettledAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSettledAt, opts...).ToFunc()
}

// ByUsageRecordedAt orders the results by the usage_recorded_at field.
func ByUsageRecordedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUsageRecordedAt, opts...).ToFunc()
}
