// Code generated by ent, DO NOT EDIT.

package reusableinvitationcodeuse

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/LuckyKuang/sub2api-plus/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.ReusableInvitationCodeUse {
	return predicate.ReusableInvitationCodeUse(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.ReusableInvitationCodeUse {
	return predicate.ReusableInvitationCodeUse(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.ReusableInvitationCodeUse {
	return predicate.ReusableInvitationCodeUse(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.ReusableInvitationCodeUse {
	return predicate.ReusableInvitationCodeUse(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.ReusableInvitationCodeUse {
	return predicate.ReusableInvitationCodeUse(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.ReusableInvitationCodeUse {
	return predicate.ReusableInvitationCodeUse(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.ReusableInvitationCodeUse {
	return predicate.ReusableInvitationCodeUse(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.ReusableInvitationCodeUse {
	return predicate.ReusableInvitationCodeUse(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.ReusableInvitationCodeUse {
	return predicate.ReusableInvitationCodeUse(sql.FieldLTE(FieldID, id))
}

// CodeID applies equality check predicate on the "code_id" field. It's identical to CodeIDEQ.
func CodeID(v int64) predicate.ReusableInvitationCodeUse {
	return predicate.ReusableInvitationCodeUse(sql.FieldEQ(FieldCodeID, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.ReusableInvitationCodeUse {
	return predicate.ReusableInvitationCodeUse(sql.FieldEQ(FieldUserID, v))
}

// Email applies equality check predicate on the "email" field. It's identical to EmailEQ.
func Email(v string) predicate.ReusableInvitationCodeUse {
	return predicate.ReusableInvitationCodeUse(sql.FieldEQ(FieldEmail, v))
}

// AuthSource applies equality check predicate on the "auth_source" field. It's identical to AuthSourceEQ.
func AuthSource(v string) predicate.ReusableInvitationCodeUse {
	return predicate.ReusableInvitationCodeUse(sql.FieldEQ(FieldAuthSource, v))
}

// UsedAt applies equality check predicate on the "used_at" field. It's identical to UsedAtEQ.
func UsedAt(v time.Time) predicate.ReusableInvitationCodeUse {
	return predicate.ReusableInvitationCodeUse(sql.FieldEQ(FieldUsedAt, v))
}

// CodeIDEQ applies the EQ predicate on the "code_id" field.
func CodeIDEQ(v int64) predicate.ReusableInvitationCodeUse {
	return predicate.ReusableInvitationCodeUse(sql.FieldEQ(FieldCodeID, v))
}

// CodeIDNEQ applies the NEQ predicate on the "code_id" field.
func CodeIDNEQ(v int64) predicate.ReusableInvitationCodeUse {
	return predicate.ReusableInvitationCodeUse(sql.FieldNEQ(FieldCodeID, v))
}

// CodeIDIn applies the In predicate on the "code_id" field.
func CodeIDIn(vs ...int64) predicate.ReusableInvitationCodeUse {
	return predicate.ReusableInvitationCodeUse(sql.FieldIn(FieldCodeID, vs...))
}

// CodeIDNotIn applies the NotIn predicate on the "code_id" field.
func CodeIDNotIn(vs ...int64) predicate.ReusableInvitationCodeUse {
	return predicate.ReusableInvitationCodeUse(sql.FieldNotIn(FieldCodeID, vs...))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.ReusableInvitationCodeUse {
	return predicate.ReusableInvitationCodeUse(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.ReusableInvitationCodeUse {
	return predicate.ReusableInvitationCodeUse(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.ReusableInvitationCodeUse {
	return predicate.ReusableInvitationCodeUse(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.ReusableInvitationCodeUse {
	return predicate.ReusableInvitationCodeUse(sql.FieldNotIn(FieldUserID, vs...))
}

// EmailEQ applies the EQ predicate on the "email" field.
func EmailEQ(v string) predicate.ReusableInvitationCodeUse {
	return predicate.ReusableInvitationCodeUse(sql.FieldEQ(FieldEmail, v))
}

// EmailNEQ applies the NEQ predicate on the "email" field.
func EmailNEQ(v string) predicate.ReusableInvitationCodeUse {
	return predicate.ReusableInvitationCodeUse(sql.FieldNEQ(FieldEmail, v))
}

// EmailIn applies the In predicate on the "email" field.
func EmailIn(vs ...string) predicate.ReusableInvitationCodeUse {
	return predicate.ReusableInvitationCodeUse(sql.FieldIn(FieldEmail, vs...))
}

// EmailNotIn applies the NotIn predicate on the "email" field.
func EmailNotIn(vs ...string) predicate.ReusableInvitationCodeUse {
	return predicate.ReusableInvitationCodeUse(sql.FieldNotIn(FieldEmail, vs...))
}

// EmailGT applies the GT predicate on the "email" field.
func EmailGT(v string) predicate.ReusableInvitationCodeUse {
	return predicate.ReusableInvitationCodeUse(sql.FieldGT(FieldEmail, v))
}

// EmailGTE applies the GTE predicate on the "email" field.
func EmailGTE(v string) predicate.ReusableInvitationCodeUse {
	return predicate.ReusableInvitationCodeUse(sql.FieldGTE(FieldEmail, v))
}

// EmailLT applies the LT predicate on the "email" field.
func EmailLT(v string) predicate.ReusableInvitationCodeUse {
	return predicate.ReusableInvitationCodeUse(sql.FieldLT(FieldEmail, v))
}

// EmailLTE applies the LTE predicate on the "email" field.
func EmailLTE(v string) predicate.ReusableInvitationCodeUse {
	return predicate.ReusableInvitationCodeUse(sql.FieldLTE(FieldEmail, v))
}

// EmailContains applies the Contains predicate on the "email" field.
func EmailContains(v string) predicate.ReusableInvitationCodeUse {
	return predicate.ReusableInvitationCodeUse(sql.FieldContains(FieldEmail, v))
}

// EmailHasPrefix applies the HasPrefix predicate on the "email" field.
func EmailHasPrefix(v string) predicate.ReusableInvitationCodeUse {
	return predicate.ReusableInvitationCodeUse(sql.FieldHasPrefix(FieldEmail, v))
}

// EmailHasSuffix applies the HasSuffix predicate on the "email" field.
func EmailHasSuffix(v string) predicate.ReusableInvitationCodeUse {
	return predicate.ReusableInvitationCodeUse(sql.FieldHasSuffix(FieldEmail, v))
}

// EmailEqualFold applies the EqualFold predicate on the "email" field.
func EmailEqualFold(v string) predicate.ReusableInvitationCodeUse {
	return predicate.ReusableInvitationCodeUse(sql.FieldEqualFold(FieldEmail, v))
}

// EmailContainsFold applies the ContainsFold predicate on the "email" field.
func EmailContainsFold(v string) predicate.ReusableInvitationCodeUse {
	return predicate.ReusableInvitationCodeUse(sql.FieldContainsFold(FieldEmail, v))
}

// AuthSourceEQ applies the EQ predicate on the "auth_source" field.
func AuthSourceEQ(v string) predicate.ReusableInvitationCodeUse {
	return predicate.ReusableInvitationCodeUse(sql.FieldEQ(FieldAuthSource, v))
}

// AuthSourceNEQ applies the NEQ predicate on the "auth_source" field.
func AuthSourceNEQ(v string) predicate.ReusableInvitationCodeUse {
	return predicate.ReusableInvitationCodeUse(sql.FieldNEQ(FieldAuthSource, v))
}

// AuthSourceIn applies the In predicate on the "auth_source" field.
func AuthSourceIn(vs ...string) predicate.ReusableInvitationCodeUse {
	return predicate.ReusableInvitationCodeUse(sql.FieldIn(FieldAuthSource, vs...))
}

// AuthSourceNotIn applies the NotIn predicate on the "auth_source" field.
func AuthSourceNotIn(vs ...string) predicate.ReusableInvitationCodeUse {
	return predicate.ReusableInvitationCodeUse(sql.FieldNotIn(FieldAuthSource, vs...))
}

// AuthSourceGT applies the GT predicate on the "auth_source" field.
func AuthSourceGT(v string) predicate.ReusableInvitationCodeUse {
	return predicate.ReusableInvitationCodeUse(sql.FieldGT(FieldAuthSource, v))
}

// AuthSourceGTE applies the GTE predicate on the "auth_source" field.
func AuthSourceGTE(v string) predicate.ReusableInvitationCodeUse {
	return predicate.ReusableInvitationCodeUse(sql.FieldGTE(FieldAuthSource, v))
}

// AuthSourceLT applies the LT predicate on the "auth_source" field.
func AuthSourceLT(v string) predicate.ReusableInvitationCodeUse {
	return predicate.ReusableInvitationCodeUse(sql.FieldLT(FieldAuthSource, v))
}

// AuthSourceLTE applies the LTE predicate on the "auth_source" field.
func AuthSourceLTE(v string) predicate.ReusableInvitationCodeUse {
	return predicate.ReusableInvitationCodeUse(sql.FieldLTE(FieldAuthSource, v))
}

// AuthSourceContains applies the Contains predicate on the "auth_source" field.
func AuthSourceContains(v string) predicate.ReusableInvitationCodeUse {
	return predicate.ReusableInvitationCodeUse(sql.FieldContains(FieldAuthSource, v))
}

// AuthSourceHasPrefix applies the HasPrefix predicate on the "auth_source" field.
func AuthSourceHasPrefix(v string) predicate.ReusableInvitationCodeUse {
	return predicate.ReusableInvitationCodeUse(sql.FieldHasPrefix(FieldAuthSource, v))
}

// AuthSourceHasSuffix applies the HasSuffix predicate on the "auth_source" field.
func AuthSourceHasSuffix(v string) predicate.ReusableInvitationCodeUse {
	return predicate.ReusableInvitationCodeUse(sql.FieldHasSuffix(FieldAuthSource, v))
}

// AuthSourceEqualFold applies the EqualFold predicate on the "auth_source" field.
func AuthSourceEqualFold(v string) predicate.ReusableInvitationCodeUse {
	return predicate.ReusableInvitationCodeUse(sql.FieldEqualFold(FieldAuthSource, v))
}

// AuthSourceContainsFold applies the ContainsFold predicate on the "auth_source" field.
func AuthSourceContainsFold(v string) predicate.ReusableInvitationCodeUse {
	return predicate.ReusableInvitationCodeUse(sql.FieldContainsFold(FieldAuthSource, v))
}

// UsedAtEQ applies the EQ predicate on the "used_at" field.
func UsedAtEQ(v time.Time) predicate.ReusableInvitationCodeUse {
	return predicate.ReusableInvitationCodeUse(sql.FieldEQ(FieldUsedAt, v))
}

// UsedAtNEQ applies the NEQ predicate on the "used_at" field.
func UsedAtNEQ(v time.Time) predicate.ReusableInvitationCodeUse {
	return predicate.ReusableInvitationCodeUse(sql.FieldNEQ(FieldUsedAt, v))
}

// UsedAtIn applies the In predicate on the "used_at" field.
func UsedAtIn(vs ...time.Time) predicate.ReusableInvitationCodeUse {
	return predicate.ReusableInvitationCodeUse(sql.FieldIn(FieldUsedAt, vs...))
}

// UsedAtNotIn applies the NotIn predicate on the "used_at" field.
func UsedAtNotIn(vs ...time.Time) predicate.ReusableInvitationCodeUse {
	return predicate.ReusableInvitationCodeUse(sql.FieldNotIn(FieldUsedAt, vs...))
}

// UsedAtGT applies the GT predicate on the "used_at" field.
func UsedAtGT(v time.Time) predicate.ReusableInvitationCodeUse {
	return predicate.ReusableInvitationCodeUse(sql.FieldGT(FieldUsedAt, v))
}

// UsedAtGTE applies the GTE predicate on the "used_at" field.
func UsedAtGTE(v time.Time) predicate.ReusableInvitationCodeUse {
	return predicate.ReusableInvitationCodeUse(sql.FieldGTE(FieldUsedAt, v))
}

// UsedAtLT applies the LT predicate on the "used_at" field.
func UsedAtLT(v time.Time) predicate.ReusableInvitationCodeUse {
	return predicate.ReusableInvitationCodeUse(sql.FieldLT(FieldUsedAt, v))
}

// UsedAtLTE applies the LTE predicate on the "used_at" field.
func UsedAtLTE(v time.Time) predicate.ReusableInvitationCodeUse {
	return predicate.ReusableInvitationCodeUse(sql.FieldLTE(FieldUsedAt, v))
}

// HasCode applies the HasEdge predicate on the "code" edge.
func HasCode() predicate.ReusableInvitationCodeUse {
	return predicate.ReusableInvitationCodeUse(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, CodeTable, CodeColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasCodeWith applies the HasEdge predicate on the "code" edge with a given conditions (other predicates).
func HasCodeWith(preds ...predicate.ReusableInvitationCode) predicate.ReusableInvitationCodeUse {
	return predicate.ReusableInvitationCodeUse(func(s *sql.Selector) {
		step := newCodeStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.ReusableInvitationCodeUse {
	return predicate.ReusableInvitationCodeUse(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.ReusableInvitationCodeUse {
	return predicate.ReusableInvitationCodeUse(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ReusableInvitationCodeUse) predicate.ReusableInvitationCodeUse {
	return predicate.ReusableInvitationCodeUse(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ReusableInvitationCodeUse) predicate.ReusableInvitationCodeUse {
	return predicate.ReusableInvitationCodeUse(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ReusableInvitationCodeUse) predicate.ReusableInvitationCodeUse {
	return predicate.ReusableInvitationCodeUse(sql.NotPredicates(p))
}
