// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/LuckyKuang/sub2api-plus/ent/imageobject"
	"github.com/LuckyKuang/sub2api-plus/ent/predicate"
)

// ImageObjectUpdate is the builder for updating ImageObject entities.
type ImageObjectUpdate struct {
	config
	hooks    []Hook
	mutation *ImageObjectMutation
}

// Where appends a list predicates to the ImageObjectUpdate builder.
func (_u *ImageObjectUpdate) Where(ps ...predicate.ImageObject) *ImageObjectUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetContentType sets the "content_type" field.
func (_u *ImageObjectUpdate) SetContentType(v string) *ImageObjectUpdate {
	_u.mutation.SetContentType(v)
	return _u
}

// SetNillableContentType sets the "content_type" field if the given value is not nil.
func (_u *ImageObjectUpdate) SetNillableContentType(v *string) *ImageObjectUpdate {
	if v != nil {
		_u.SetContentType(*v)
	}
	return _u
}

// SetByteSize sets the "byte_size" field.
func (_u *ImageObjectUpdate) SetByteSize(v int64) *ImageObjectUpdate {
	_u.mutation.ResetByteSize()
	_u.mutation.SetByteSize(v)
	return _u
}

// SetNillableByteSize sets the "byte_size" field if the given value is not nil.
func (_u *ImageObjectUpdate) SetNillableByteSize(v *int64) *ImageObjectUpdate {
	if v != nil {
		_u.SetByteSize(*v)
	}
	return _u
}

// AddByteSize adds value to the "byte_size" field.
func (_u *ImageObjectUpdate) AddByteSize(v int64) *ImageObjectUpdate {
	_u.mutation.AddByteSize(v)
	return _u
}

// Mutation returns the ImageObjectMutation object of the builder.
func (_u *ImageObjectUpdate) Mutation() *ImageObjectMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ImageObjectUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ImageObjectUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ImageObjectUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ImageObjectUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ImageObjectUpdate) check() error {
	if v, ok := _u.mutation.ContentType(); ok {
		if err := imageobject.ContentTypeValidator(v); err != nil {
			return &ValidationError{Name: "content_type", err: fmt.Errorf(`ent: validator failed for field "ImageObject.content_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ByteSize(); ok {
		if err := imageobject.ByteSizeValidator(v); err != nil {
			return &ValidationError{Name: "byte_size", err: fmt.Errorf(`ent: validator failed for field "ImageObject.byte_size": %w`, err)}
		}
	}
	return nil
}

func (_u *ImageObjectUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(imageobject.Table, imageobject.Columns, sqlgraph.NewFieldSpec(imageobject.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ContentType(); ok {
		_spec.SetField(imageobject.FieldContentType, field.TypeString, value)
	}
	if value, ok := _u.mutation.ByteSize(); ok {
		_spec.SetField(imageobject.FieldByteSize, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedByteSize(); ok {
		_spec.AddField(imageobject.FieldByteSize, field.TypeInt64, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{imageobject.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ImageObjectUpdateOne is the builder for updating a single ImageObject entity.
type ImageObjectUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ImageObjectMutation
}

// SetContentType sets the "content_type" field.
func (_u *ImageObjectUpdateOne) SetContentType(v string) *ImageObjectUpdateOne {
	_u.mutation.SetContentType(v)
	return _u
}

// SetNillableContentType sets the "content_type" field if the given value is not nil.
func (_u *ImageObjectUpdateOne) SetNillableContentType(v *string) *ImageObjectUpdateOne {
	if v != nil {
		_u.SetContentType(*v)
	}
	return _u
}

// SetByteSize sets the "byte_size" field.
func (_u *ImageObjectUpdateOne) SetByteSize(v int64) *ImageObjectUpdateOne {
	_u.mutation.ResetByteSize()
	_u.mutation.SetByteSize(v)
	return _u
}

// SetNillableByteSize sets the "byte_size" field if the given value is not nil.
func (_u *ImageObjectUpdateOne) SetNillableByteSize(v *int64) *ImageObjectUpdateOne {
	if v != nil {
		_u.SetByteSize(*v)
	}
	return _u
}

// AddByteSize adds value to the "byte_size" field.
func (_u *ImageObjectUpdateOne) AddByteSize(v int64) *ImageObjectUpdateOne {
	_u.mutation.AddByteSize(v)
	return _u
}

// Mutation returns the ImageObjectMutation object of the builder.
func (_u *ImageObjectUpdateOne) Mutation() *ImageObjectMutation {
	return _u.mutation
}

// Where appends a list predicates to the ImageObjectUpdate builder.
func (_u *ImageObjectUpdateOne) Where(ps ...predicate.ImageObject) *ImageObjectUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ImageObjectUpdateOne) Select(field string, fields ...string) *ImageObjectUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ImageObject entity.
func (_u *ImageObjectUpdateOne) Save(ctx context.Context) (*ImageObject, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ImageObjectUpdateOne) SaveX(ctx context.Context) *ImageObject {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ImageObjectUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ImageObjectUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ImageObjectUpdateOne) check() error {
	if v, ok := _u.mutation.ContentType(); ok {
		if err := imageobject.ContentTypeValidator(v); err != nil {
			return &ValidationError{Name: "content_type", err: fmt.Errorf(`ent: validator failed for field "ImageObject.content_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ByteSize(); ok {
		if err := imageobject.ByteSizeValidator(v); err != nil {
			return &ValidationError{Name: "byte_size", err: fmt.Errorf(`ent: validator failed for field "ImageObject.byte_size": %w`, err)}
		}
	}
	return nil
}

func (_u *ImageObjectUpdateOne) sqlSave(ctx context.Context) (_node *ImageObject, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(imageobject.Table, imageobject.Columns, sqlgraph.NewFieldSpec(imageobject.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ImageObject.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, imageobject.FieldID)
		for _, f := range fields {
			if !imageobject.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != imageobject.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ContentType(); ok {
		_spec.SetField(imageobject.FieldContentType, field.TypeString, value)
	}
	if value, ok := _u.mutation.ByteSize(); ok {
		_spec.SetField(imageobject.FieldByteSize, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedByteSize(); ok {
		_spec.AddField(imageobject.FieldByteSize, field.TypeInt64, value)
	}
	_node = &ImageObject{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{imageobject.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
