// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/LuckyKuang/sub2api-plus/ent/imageobject"
)

// ImageObjectCreate is the builder for creating a ImageObject entity.
type ImageObjectCreate struct {
	config
	mutation *ImageObjectMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetObjectID sets the "object_id" field.
func (_c *ImageObjectCreate) SetObjectID(v string) *ImageObjectCreate {
	_c.mutation.SetObjectID(v)
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *ImageObjectCreate) SetUserID(v int64) *ImageObjectCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetAPIKeyID sets the "api_key_id" field.
func (_c *ImageObjectCreate) SetAPIKeyID(v int64) *ImageObjectCreate {
	_c.mutation.SetAPIKeyID(v)
	return _c
}

// SetTaskID sets the "task_id" field.
func (_c *ImageObjectCreate) SetTaskID(v string) *ImageObjectCreate {
	_c.mutation.SetTaskID(v)
	return _c
}

// SetStorageKey sets the "storage_key" field.
func (_c *ImageObjectCreate) SetStorageKey(v string) *ImageObjectCreate {
	_c.mutation.SetStorageKey(v)
	return _c
}

// SetContentType sets the "content_type" field.
func (_c *ImageObjectCreate) SetContentType(v string) *ImageObjectCreate {
	_c.mutation.SetContentType(v)
	return _c
}

// SetNillableContentType sets the "content_type" field if the given value is not nil.
func (_c *ImageObjectCreate) SetNillableContentType(v *string) *ImageObjectCreate {
	if v != nil {
		_c.SetContentType(*v)
	}
	return _c
}

// SetByteSize sets the "byte_size" field.
func (_c *ImageObjectCreate) SetByteSize(v int64) *ImageObjectCreate {
	_c.mutation.SetByteSize(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *ImageObjectCreate) SetCreatedAt(v time.Time) *ImageObjectCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ImageObjectCreate) SetNillableCreatedAt(v *time.Time) *ImageObjectCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// Mutation returns the ImageObjectMutation object of the builder.
func (_c *ImageObjectCreate) Mutation() *ImageObjectMutation {
	return _c.mutation
}

// Save creates the ImageObject in the database.
func (_c *ImageObjectCreate) Save(ctx context.Context) (*ImageObject, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ImageObjectCreate) SaveX(ctx context.Context) *ImageObject {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ImageObjectCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ImageObjectCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ImageObjectCreate) defaults() {
	if _, ok := _c.mutation.ContentType(); !ok {
		v := imageobject.DefaultContentType
		_c.mutation.SetContentType(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := imageobject.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ImageObjectCreate) check() error {
	if _, ok := _c.mutation.ObjectID(); !ok {
		return &ValidationError{Name: "object_id", err: errors.New(`ent: missing required field "ImageObject.object_id"`)}
	}
	if v, ok := _c.mutation.ObjectID(); ok {
		if err := imageobject.ObjectIDValidator(v); err != nil {
			return &ValidationError{Name: "object_id", err: fmt.Errorf(`ent: validator failed for field "ImageObject.object_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "ImageObject.user_id"`)}
	}
	if _, ok := _c.mutation.APIKeyID(); !ok {
		return &ValidationError{Name: "api_key_id", err: errors.New(`ent: missing required field "ImageObject.api_key_id"`)}
	}
	if _, ok := _c.mutation.TaskID(); !ok {
		return &ValidationError{Name: "task_id", err: errors.New(`ent: missing required field "ImageObject.task_id"`)}
	}
	if v, ok := _c.mutation.TaskID(); ok {
		if err := imageobject.TaskIDValidator(v); err != nil {
			return &ValidationError{Name: "task_id", err: fmt.Errorf(`ent: validator failed for field "ImageObject.task_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.StorageKey(); !ok {
		return &ValidationError{Name: "storage_key", err: errors.New(`ent: missing required field "ImageObject.storage_key"`)}
	}
	if v, ok := _c.mutation.StorageKey(); ok {
		if err := imageobject.StorageKeyValidator(v); err != nil {
			return &ValidationError{Name: "storage_key", err: fmt.Errorf(`ent: validator failed for field "ImageObject.storage_key": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ContentType(); !ok {
		return &ValidationError{Name: "content_type", err: errors.New(`ent: missing required field "ImageObject.content_type"`)}
	}
	if v, ok := _c.mutation.ContentType(); ok {
		if err := imageobject.ContentTypeValidator(v); err != nil {
			return &ValidationError{Name: "content_type", err: fmt.Errorf(`ent: validator failed for field "ImageObject.content_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ByteSize(); !ok {
		return &ValidationError{Name: "byte_size", err: errors.New(`ent: missing required field "ImageObject.byte_size"`)}
	}
	if v, ok := _c.mutation.ByteSize(); ok {
		if err := imageobject.ByteSizeValidator(v); err != nil {
			return &ValidationError{Name: "byte_size", err: fmt.Errorf(`ent: validator failed for field "ImageObject.byte_size": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ImageObject.created_at"`)}
	}
	return nil
}

func (_c *ImageObjectCreate) sqlSave(ctx context.Context) (*ImageObject, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ImageObjectCreate) createSpec() (*ImageObject, *sqlgraph.CreateSpec) {
	var (
		_node = &ImageObject{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(imageobject.Table, sqlgraph.NewFieldSpec(imageobject.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.ObjectID(); ok {
		_spec.SetField(imageobject.FieldObjectID, field.TypeString, value)
		_node.ObjectID = value
	}
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(imageobject.FieldUserID, field.TypeInt64, value)
		_node.UserID = value
	}
	if value, ok := _c.mutation.APIKeyID(); ok {
		_spec.SetField(imageobject.FieldAPIKeyID, field.TypeInt64, value)
		_node.APIKeyID = value
	}
	if value, ok := _c.mutation.TaskID(); ok {
		_spec.SetField(imageobject.FieldTaskID, field.TypeString, value)
		_node.TaskID = value
	}
	if value, ok := _c.mutation.StorageKey(); ok {
		_spec.SetField(imageobject.FieldStorageKey, field.TypeString, value)
		_node.StorageKey = value
	}
	if value, ok := _c.mutation.ContentType(); ok {
		_spec.SetField(imageobject.FieldContentType, field.TypeString, value)
		_node.ContentType = value
	}
	if value, ok := _c.mutation.ByteSize(); ok {
		_spec.SetField(imageobject.FieldByteSize, field.TypeInt64, value)
		_node.ByteSize = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(imageobject.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ImageObject.Create().
//		SetObjectID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ImageObjectUpsert) {
//			SetObjectID(v+v).
//		}).
//		Exec(ctx)
func (_c *ImageObjectCreate) OnConflict(opts ...sql.ConflictOption) *ImageObjectUpsertOne {
	_c.conflict = opts
	return &ImageObjectUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ImageObject.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ImageObjectCreate) OnConflictColumns(columns ...string) *ImageObjectUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ImageObjectUpsertOne{
		create: _c,
	}
}

type (
	// ImageObjectUpsertOne is the builder for "upsert"-ing
	//  one ImageObject node.
	ImageObjectUpsertOne struct {
		create *ImageObjectCreate
	}

	// ImageObjectUpsert is the "OnConflict" setter.
	ImageObjectUpsert struct {
		*sql.UpdateSet
	}
)

// SetContentType sets the "content_type" field.
func (u *ImageObjectUpsert) SetContentType(v string) *ImageObjectUpsert {
	u.Set(imageobject.FieldContentType, v)
	return u
}

// UpdateContentType sets the "content_type" field to the value that was provided on create.
func (u *ImageObjectUpsert) UpdateContentType() *ImageObjectUpsert {
	u.SetExcluded(imageobject.FieldContentType)
	return u
}

// SetByteSize sets the "byte_size" field.
func (u *ImageObjectUpsert) SetByteSize(v int64) *ImageObjectUpsert {
	u.Set(imageobject.FieldByteSize, v)
	return u
}

// UpdateByteSize sets the "byte_size" field to the value that was provided on create.
func (u *ImageObjectUpsert) UpdateByteSize() *ImageObjectUpsert {
	u.SetExcluded(imageobject.FieldByteSize)
	return u
}

// AddByteSize adds v to the "byte_size" field.
func (u *ImageObjectUpsert) AddByteSize(v int64) *ImageObjectUpsert {
	u.Add(imageobject.FieldByteSize, v)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.ImageObject.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ImageObjectUpsertOne) UpdateNewValues() *ImageObjectUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ObjectID(); exists {
			s.SetIgnore(imageobject.FieldObjectID)
		}
		if _, exists := u.create.mutation.UserID(); exists {
			s.SetIgnore(imageobject.FieldUserID)
		}
		if _, exists := u.create.mutation.APIKeyID(); exists {
			s.SetIgnore(imageobject.FieldAPIKeyID)
		}
		if _, exists := u.create.mutation.TaskID(); exists {
			s.SetIgnore(imageobject.FieldTaskID)
		}
		if _, exists := u.create.mutation.StorageKey(); exists {
			s.SetIgnore(imageobject.FieldStorageKey)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(imageobject.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ImageObject.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ImageObjectUpsertOne) Ignore() *ImageObjectUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ImageObjectUpsertOne) DoNothing() *ImageObjectUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ImageObjectCreate.OnConflict
// documentation for more info.
func (u *ImageObjectUpsertOne) Update(set func(*ImageObjectUpsert)) *ImageObjectUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ImageObjectUpsert{UpdateSet: update})
	}))
	return u
}

// SetContentType sets the "content_type" field.
func (u *ImageObjectUpsertOne) SetContentType(v string) *ImageObjectUpsertOne {
	return u.Update(func(s *ImageObjectUpsert) {
		s.SetContentType(v)
	})
}

// UpdateContentType sets the "content_type" field to the value that was provided on create.
func (u *ImageObjectUpsertOne) UpdateContentType() *ImageObjectUpsertOne {
	return u.Update(func(s *ImageObjectUpsert) {
		s.UpdateContentType()
	})
}

// SetByteSize sets the "byte_size" field.
func (u *ImageObjectUpsertOne) SetByteSize(v int64) *ImageObjectUpsertOne {
	return u.Update(func(s *ImageObjectUpsert) {
		s.SetByteSize(v)
	})
}

// AddByteSize adds v to the "byte_size" field.
func (u *ImageObjectUpsertOne) AddByteSize(v int64) *ImageObjectUpsertOne {
	return u.Update(func(s *ImageObjectUpsert) {
		s.AddByteSize(v)
	})
}

// UpdateByteSize sets the "byte_size" field to the value that was provided on create.
func (u *ImageObjectUpsertOne) UpdateByteSize() *ImageObjectUpsertOne {
	return u.Update(func(s *ImageObjectUpsert) {
		s.UpdateByteSize()
	})
}

// Exec executes the query.
func (u *ImageObjectUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ImageObjectCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ImageObjectUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ImageObjectUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ImageObjectUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ImageObjectCreateBulk is the builder for creating many ImageObject entities in bulk.
type ImageObjectCreateBulk struct {
	config
	err      error
	builders []*ImageObjectCreate
	conflict []sql.ConflictOption
}

// Save creates the ImageObject entities in the database.
func (_c *ImageObjectCreateBulk) Save(ctx context.Context) ([]*ImageObject, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ImageObject, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ImageObjectMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ImageObjectCreateBulk) SaveX(ctx context.Context) []*ImageObject {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ImageObjectCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ImageObjectCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ImageObject.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ImageObjectUpsert) {
//			SetObjectID(v+v).
//		}).
//		Exec(ctx)
func (_c *ImageObjectCreateBulk) OnConflict(opts ...sql.ConflictOption) *ImageObjectUpsertBulk {
	_c.conflict = opts
	return &ImageObjectUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ImageObject.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ImageObjectCreateBulk) OnConflictColumns(columns ...string) *ImageObjectUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ImageObjectUpsertBulk{
		create: _c,
	}
}

// ImageObjectUpsertBulk is the builder for "upsert"-ing
// a bulk of ImageObject nodes.
type ImageObjectUpsertBulk struct {
	create *ImageObjectCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.ImageObject.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ImageObjectUpsertBulk) UpdateNewValues() *ImageObjectUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ObjectID(); exists {
				s.SetIgnore(imageobject.FieldObjectID)
			}
			if _, exists := b.mutation.UserID(); exists {
				s.SetIgnore(imageobject.FieldUserID)
			}
			if _, exists := b.mutation.APIKeyID(); exists {
				s.SetIgnore(imageobject.FieldAPIKeyID)
			}
			if _, exists := b.mutation.TaskID(); exists {
				s.SetIgnore(imageobject.FieldTaskID)
			}
			if _, exists := b.mutation.StorageKey(); exists {
				s.SetIgnore(imageobject.FieldStorageKey)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(imageobject.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ImageObject.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ImageObjectUpsertBulk) Ignore() *ImageObjectUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ImageObjectUpsertBulk) DoNothing() *ImageObjectUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ImageObjectCreateBulk.OnConflict
// documentation for more info.
func (u *ImageObjectUpsertBulk) Update(set func(*ImageObjectUpsert)) *ImageObjectUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ImageObjectUpsert{UpdateSet: update})
	}))
	return u
}

// SetContentType sets the "content_type" field.
func (u *ImageObjectUpsertBulk) SetContentType(v string) *ImageObjectUpsertBulk {
	return u.Update(func(s *ImageObjectUpsert) {
		s.SetContentType(v)
	})
}

// UpdateContentType sets the "content_type" field to the value that was provided on create.
func (u *ImageObjectUpsertBulk) UpdateContentType() *ImageObjectUpsertBulk {
	return u.Update(func(s *ImageObjectUpsert) {
		s.UpdateContentType()
	})
}

// SetByteSize sets the "byte_size" field.
func (u *ImageObjectUpsertBulk) SetByteSize(v int64) *ImageObjectUpsertBulk {
	return u.Update(func(s *ImageObjectUpsert) {
		s.SetByteSize(v)
	})
}

// AddByteSize adds v to the "byte_size" field.
func (u *ImageObjectUpsertBulk) AddByteSize(v int64) *ImageObjectUpsertBulk {
	return u.Update(func(s *ImageObjectUpsert) {
		s.AddByteSize(v)
	})
}

// UpdateByteSize sets the "byte_size" field to the value that was provided on create.
func (u *ImageObjectUpsertBulk) UpdateByteSize() *ImageObjectUpsertBulk {
	return u.Update(func(s *ImageObjectUpsert) {
		s.UpdateByteSize()
	})
}

// Exec executes the query.
func (u *ImageObjectUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ImageObjectCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ImageObjectCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ImageObjectUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
