// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/LuckyKuang/sub2api-plus/ent/openaivideotask"
	"github.com/LuckyKuang/sub2api-plus/ent/predicate"
)

// OpenAIVideoTaskDelete is the builder for deleting a OpenAIVideoTask entity.
type OpenAIVideoTaskDelete struct {
	config
	hooks    []Hook
	mutation *OpenAIVideoTaskMutation
}

// Where appends a list predicates to the OpenAIVideoTaskDelete builder.
func (_d *OpenAIVideoTaskDelete) Where(ps ...predicate.OpenAIVideoTask) *OpenAIVideoTaskDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *OpenAIVideoTaskDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *OpenAIVideoTaskDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *OpenAIVideoTaskDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(openaivideotask.Table, sqlgraph.NewFieldSpec(openaivideotask.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// OpenAIVideoTaskDeleteOne is the builder for deleting a single OpenAIVideoTask entity.
type OpenAIVideoTaskDeleteOne struct {
	_d *OpenAIVideoTaskDelete
}

// Where appends a list predicates to the OpenAIVideoTaskDelete builder.
func (_d *OpenAIVideoTaskDeleteOne) Where(ps ...predicate.OpenAIVideoTask) *OpenAIVideoTaskDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *OpenAIVideoTaskDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{openaivideotask.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *OpenAIVideoTaskDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
