// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/LuckyKuang/sub2api-plus/ent/predicate"
	"github.com/LuckyKuang/sub2api-plus/ent/reusableinvitationcode"
)

// ReusableInvitationCodeDelete is the builder for deleting a ReusableInvitationCode entity.
type ReusableInvitationCodeDelete struct {
	config
	hooks    []Hook
	mutation *ReusableInvitationCodeMutation
}

// Where appends a list predicates to the ReusableInvitationCodeDelete builder.
func (_d *ReusableInvitationCodeDelete) Where(ps ...predicate.ReusableInvitationCode) *ReusableInvitationCodeDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *ReusableInvitationCodeDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ReusableInvitationCodeDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *ReusableInvitationCodeDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(reusableinvitationcode.Table, sqlgraph.NewFieldSpec(reusableinvitationcode.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// ReusableInvitationCodeDeleteOne is the builder for deleting a single ReusableInvitationCode entity.
type ReusableInvitationCodeDeleteOne struct {
	_d *ReusableInvitationCodeDelete
}

// Where appends a list predicates to the ReusableInvitationCodeDelete builder.
func (_d *ReusableInvitationCodeDeleteOne) Where(ps ...predicate.ReusableInvitationCode) *ReusableInvitationCodeDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *ReusableInvitationCodeDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{reusableinvitationcode.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ReusableInvitationCodeDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
