// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/LuckyKuang/sub2api-plus/ent/reusableinvitationcode"
	"github.com/LuckyKuang/sub2api-plus/ent/reusableinvitationcodeuse"
	"github.com/LuckyKuang/sub2api-plus/ent/user"
)

// ReusableInvitationCodeUseCreate is the builder for creating a ReusableInvitationCodeUse entity.
type ReusableInvitationCodeUseCreate struct {
	config
	mutation *ReusableInvitationCodeUseMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCodeID sets the "code_id" field.
func (_c *ReusableInvitationCodeUseCreate) SetCodeID(v int64) *ReusableInvitationCodeUseCreate {
	_c.mutation.SetCodeID(v)
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *ReusableInvitationCodeUseCreate) SetUserID(v int64) *ReusableInvitationCodeUseCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetEmail sets the "email" field.
func (_c *ReusableInvitationCodeUseCreate) SetEmail(v string) *ReusableInvitationCodeUseCreate {
	_c.mutation.SetEmail(v)
	return _c
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (_c *ReusableInvitationCodeUseCreate) SetNillableEmail(v *string) *ReusableInvitationCodeUseCreate {
	if v != nil {
		_c.SetEmail(*v)
	}
	return _c
}

// SetAuthSource sets the "auth_source" field.
func (_c *ReusableInvitationCodeUseCreate) SetAuthSource(v string) *ReusableInvitationCodeUseCreate {
	_c.mutation.SetAuthSource(v)
	return _c
}

// SetNillableAuthSource sets the "auth_source" field if the given value is not nil.
func (_c *ReusableInvitationCodeUseCreate) SetNillableAuthSource(v *string) *ReusableInvitationCodeUseCreate {
	if v != nil {
		_c.SetAuthSource(*v)
	}
	return _c
}

// SetUsedAt sets the "used_at" field.
func (_c *ReusableInvitationCodeUseCreate) SetUsedAt(v time.Time) *ReusableInvitationCodeUseCreate {
	_c.mutation.SetUsedAt(v)
	return _c
}

// SetNillableUsedAt sets the "used_at" field if the given value is not nil.
func (_c *ReusableInvitationCodeUseCreate) SetNillableUsedAt(v *time.Time) *ReusableInvitationCodeUseCreate {
	if v != nil {
		_c.SetUsedAt(*v)
	}
	return _c
}

// SetCode sets the "code" edge to the ReusableInvitationCode entity.
func (_c *ReusableInvitationCodeUseCreate) SetCode(v *ReusableInvitationCode) *ReusableInvitationCodeUseCreate {
	return _c.SetCodeID(v.ID)
}

// SetUser sets the "user" edge to the User entity.
func (_c *ReusableInvitationCodeUseCreate) SetUser(v *User) *ReusableInvitationCodeUseCreate {
	return _c.SetUserID(v.ID)
}

// Mutation returns the ReusableInvitationCodeUseMutation object of the builder.
func (_c *ReusableInvitationCodeUseCreate) Mutation() *ReusableInvitationCodeUseMutation {
	return _c.mutation
}

// Save creates the ReusableInvitationCodeUse in the database.
func (_c *ReusableInvitationCodeUseCreate) Save(ctx context.Context) (*ReusableInvitationCodeUse, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ReusableInvitationCodeUseCreate) SaveX(ctx context.Context) *ReusableInvitationCodeUse {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ReusableInvitationCodeUseCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ReusableInvitationCodeUseCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ReusableInvitationCodeUseCreate) defaults() {
	if _, ok := _c.mutation.Email(); !ok {
		v := reusableinvitationcodeuse.DefaultEmail
		_c.mutation.SetEmail(v)
	}
	if _, ok := _c.mutation.AuthSource(); !ok {
		v := reusableinvitationcodeuse.DefaultAuthSource
		_c.mutation.SetAuthSource(v)
	}
	if _, ok := _c.mutation.UsedAt(); !ok {
		v := reusableinvitationcodeuse.DefaultUsedAt()
		_c.mutation.SetUsedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ReusableInvitationCodeUseCreate) check() error {
	if _, ok := _c.mutation.CodeID(); !ok {
		return &ValidationError{Name: "code_id", err: errors.New(`ent: missing required field "ReusableInvitationCodeUse.code_id"`)}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "ReusableInvitationCodeUse.user_id"`)}
	}
	if _, ok := _c.mutation.Email(); !ok {
		return &ValidationError{Name: "email", err: errors.New(`ent: missing required field "ReusableInvitationCodeUse.email"`)}
	}
	if v, ok := _c.mutation.Email(); ok {
		if err := reusableinvitationcodeuse.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "ReusableInvitationCodeUse.email": %w`, err)}
		}
	}
	if _, ok := _c.mutation.AuthSource(); !ok {
		return &ValidationError{Name: "auth_source", err: errors.New(`ent: missing required field "ReusableInvitationCodeUse.auth_source"`)}
	}
	if v, ok := _c.mutation.AuthSource(); ok {
		if err := reusableinvitationcodeuse.AuthSourceValidator(v); err != nil {
			return &ValidationError{Name: "auth_source", err: fmt.Errorf(`ent: validator failed for field "ReusableInvitationCodeUse.auth_source": %w`, err)}
		}
	}
	if _, ok := _c.mutation.UsedAt(); !ok {
		return &ValidationError{Name: "used_at", err: errors.New(`ent: missing required field "ReusableInvitationCodeUse.used_at"`)}
	}
	if len(_c.mutation.CodeIDs()) == 0 {
		return &ValidationError{Name: "code", err: errors.New(`ent: missing required edge "ReusableInvitationCodeUse.code"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "ReusableInvitationCodeUse.user"`)}
	}
	return nil
}

func (_c *ReusableInvitationCodeUseCreate) sqlSave(ctx context.Context) (*ReusableInvitationCodeUse, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ReusableInvitationCodeUseCreate) createSpec() (*ReusableInvitationCodeUse, *sqlgraph.CreateSpec) {
	var (
		_node = &ReusableInvitationCodeUse{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(reusableinvitationcodeuse.Table, sqlgraph.NewFieldSpec(reusableinvitationcodeuse.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.Email(); ok {
		_spec.SetField(reusableinvitationcodeuse.FieldEmail, field.TypeString, value)
		_node.Email = value
	}
	if value, ok := _c.mutation.AuthSource(); ok {
		_spec.SetField(reusableinvitationcodeuse.FieldAuthSource, field.TypeString, value)
		_node.AuthSource = value
	}
	if value, ok := _c.mutation.UsedAt(); ok {
		_spec.SetField(reusableinvitationcodeuse.FieldUsedAt, field.TypeTime, value)
		_node.UsedAt = value
	}
	if nodes := _c.mutation.CodeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   reusableinvitationcodeuse.CodeTable,
			Columns: []string{reusableinvitationcodeuse.CodeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(reusableinvitationcode.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.CodeID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   reusableinvitationcodeuse.UserTable,
			Columns: []string{reusableinvitationcodeuse.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ReusableInvitationCodeUse.Create().
//		SetCodeID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ReusableInvitationCodeUseUpsert) {
//			SetCodeID(v+v).
//		}).
//		Exec(ctx)
func (_c *ReusableInvitationCodeUseCreate) OnConflict(opts ...sql.ConflictOption) *ReusableInvitationCodeUseUpsertOne {
	_c.conflict = opts
	return &ReusableInvitationCodeUseUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ReusableInvitationCodeUse.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ReusableInvitationCodeUseCreate) OnConflictColumns(columns ...string) *ReusableInvitationCodeUseUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ReusableInvitationCodeUseUpsertOne{
		create: _c,
	}
}

type (
	// ReusableInvitationCodeUseUpsertOne is the builder for "upsert"-ing
	//  one ReusableInvitationCodeUse node.
	ReusableInvitationCodeUseUpsertOne struct {
		create *ReusableInvitationCodeUseCreate
	}

	// ReusableInvitationCodeUseUpsert is the "OnConflict" setter.
	ReusableInvitationCodeUseUpsert struct {
		*sql.UpdateSet
	}
)

// SetCodeID sets the "code_id" field.
func (u *ReusableInvitationCodeUseUpsert) SetCodeID(v int64) *ReusableInvitationCodeUseUpsert {
	u.Set(reusableinvitationcodeuse.FieldCodeID, v)
	return u
}

// UpdateCodeID sets the "code_id" field to the value that was provided on create.
func (u *ReusableInvitationCodeUseUpsert) UpdateCodeID() *ReusableInvitationCodeUseUpsert {
	u.SetExcluded(reusableinvitationcodeuse.FieldCodeID)
	return u
}

// SetUserID sets the "user_id" field.
func (u *ReusableInvitationCodeUseUpsert) SetUserID(v int64) *ReusableInvitationCodeUseUpsert {
	u.Set(reusableinvitationcodeuse.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *ReusableInvitationCodeUseUpsert) UpdateUserID() *ReusableInvitationCodeUseUpsert {
	u.SetExcluded(reusableinvitationcodeuse.FieldUserID)
	return u
}

// SetEmail sets the "email" field.
func (u *ReusableInvitationCodeUseUpsert) SetEmail(v string) *ReusableInvitationCodeUseUpsert {
	u.Set(reusableinvitationcodeuse.FieldEmail, v)
	return u
}

// UpdateEmail sets the "email" field to the value that was provided on create.
func (u *ReusableInvitationCodeUseUpsert) UpdateEmail() *ReusableInvitationCodeUseUpsert {
	u.SetExcluded(reusableinvitationcodeuse.FieldEmail)
	return u
}

// SetAuthSource sets the "auth_source" field.
func (u *ReusableInvitationCodeUseUpsert) SetAuthSource(v string) *ReusableInvitationCodeUseUpsert {
	u.Set(reusableinvitationcodeuse.FieldAuthSource, v)
	return u
}

// UpdateAuthSource sets the "auth_source" field to the value that was provided on create.
func (u *ReusableInvitationCodeUseUpsert) UpdateAuthSource() *ReusableInvitationCodeUseUpsert {
	u.SetExcluded(reusableinvitationcodeuse.FieldAuthSource)
	return u
}

// SetUsedAt sets the "used_at" field.
func (u *ReusableInvitationCodeUseUpsert) SetUsedAt(v time.Time) *ReusableInvitationCodeUseUpsert {
	u.Set(reusableinvitationcodeuse.FieldUsedAt, v)
	return u
}

// UpdateUsedAt sets the "used_at" field to the value that was provided on create.
func (u *ReusableInvitationCodeUseUpsert) UpdateUsedAt() *ReusableInvitationCodeUseUpsert {
	u.SetExcluded(reusableinvitationcodeuse.FieldUsedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.ReusableInvitationCodeUse.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ReusableInvitationCodeUseUpsertOne) UpdateNewValues() *ReusableInvitationCodeUseUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ReusableInvitationCodeUse.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ReusableInvitationCodeUseUpsertOne) Ignore() *ReusableInvitationCodeUseUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ReusableInvitationCodeUseUpsertOne) DoNothing() *ReusableInvitationCodeUseUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ReusableInvitationCodeUseCreate.OnConflict
// documentation for more info.
func (u *ReusableInvitationCodeUseUpsertOne) Update(set func(*ReusableInvitationCodeUseUpsert)) *ReusableInvitationCodeUseUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ReusableInvitationCodeUseUpsert{UpdateSet: update})
	}))
	return u
}

// SetCodeID sets the "code_id" field.
func (u *ReusableInvitationCodeUseUpsertOne) SetCodeID(v int64) *ReusableInvitationCodeUseUpsertOne {
	return u.Update(func(s *ReusableInvitationCodeUseUpsert) {
		s.SetCodeID(v)
	})
}

// UpdateCodeID sets the "code_id" field to the value that was provided on create.
func (u *ReusableInvitationCodeUseUpsertOne) UpdateCodeID() *ReusableInvitationCodeUseUpsertOne {
	return u.Update(func(s *ReusableInvitationCodeUseUpsert) {
		s.UpdateCodeID()
	})
}

// SetUserID sets the "user_id" field.
func (u *ReusableInvitationCodeUseUpsertOne) SetUserID(v int64) *ReusableInvitationCodeUseUpsertOne {
	return u.Update(func(s *ReusableInvitationCodeUseUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *ReusableInvitationCodeUseUpsertOne) UpdateUserID() *ReusableInvitationCodeUseUpsertOne {
	return u.Update(func(s *ReusableInvitationCodeUseUpsert) {
		s.UpdateUserID()
	})
}

// SetEmail sets the "email" field.
func (u *ReusableInvitationCodeUseUpsertOne) SetEmail(v string) *ReusableInvitationCodeUseUpsertOne {
	return u.Update(func(s *ReusableInvitationCodeUseUpsert) {
		s.SetEmail(v)
	})
}

// UpdateEmail sets the "email" field to the value that was provided on create.
func (u *ReusableInvitationCodeUseUpsertOne) UpdateEmail() *ReusableInvitationCodeUseUpsertOne {
	return u.Update(func(s *ReusableInvitationCodeUseUpsert) {
		s.UpdateEmail()
	})
}

// SetAuthSource sets the "auth_source" field.
func (u *ReusableInvitationCodeUseUpsertOne) SetAuthSource(v string) *ReusableInvitationCodeUseUpsertOne {
	return u.Update(func(s *ReusableInvitationCodeUseUpsert) {
		s.SetAuthSource(v)
	})
}

// UpdateAuthSource sets the "auth_source" field to the value that was provided on create.
func (u *ReusableInvitationCodeUseUpsertOne) UpdateAuthSource() *ReusableInvitationCodeUseUpsertOne {
	return u.Update(func(s *ReusableInvitationCodeUseUpsert) {
		s.UpdateAuthSource()
	})
}

// SetUsedAt sets the "used_at" field.
func (u *ReusableInvitationCodeUseUpsertOne) SetUsedAt(v time.Time) *ReusableInvitationCodeUseUpsertOne {
	return u.Update(func(s *ReusableInvitationCodeUseUpsert) {
		s.SetUsedAt(v)
	})
}

// UpdateUsedAt sets the "used_at" field to the value that was provided on create.
func (u *ReusableInvitationCodeUseUpsertOne) UpdateUsedAt() *ReusableInvitationCodeUseUpsertOne {
	return u.Update(func(s *ReusableInvitationCodeUseUpsert) {
		s.UpdateUsedAt()
	})
}

// Exec executes the query.
func (u *ReusableInvitationCodeUseUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ReusableInvitationCodeUseCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ReusableInvitationCodeUseUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ReusableInvitationCodeUseUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ReusableInvitationCodeUseUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ReusableInvitationCodeUseCreateBulk is the builder for creating many ReusableInvitationCodeUse entities in bulk.
type ReusableInvitationCodeUseCreateBulk struct {
	config
	err      error
	builders []*ReusableInvitationCodeUseCreate
	conflict []sql.ConflictOption
}

// Save creates the ReusableInvitationCodeUse entities in the database.
func (_c *ReusableInvitationCodeUseCreateBulk) Save(ctx context.Context) ([]*ReusableInvitationCodeUse, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ReusableInvitationCodeUse, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ReusableInvitationCodeUseMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ReusableInvitationCodeUseCreateBulk) SaveX(ctx context.Context) []*ReusableInvitationCodeUse {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ReusableInvitationCodeUseCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ReusableInvitationCodeUseCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ReusableInvitationCodeUse.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ReusableInvitationCodeUseUpsert) {
//			SetCodeID(v+v).
//		}).
//		Exec(ctx)
func (_c *ReusableInvitationCodeUseCreateBulk) OnConflict(opts ...sql.ConflictOption) *ReusableInvitationCodeUseUpsertBulk {
	_c.conflict = opts
	return &ReusableInvitationCodeUseUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ReusableInvitationCodeUse.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ReusableInvitationCodeUseCreateBulk) OnConflictColumns(columns ...string) *ReusableInvitationCodeUseUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ReusableInvitationCodeUseUpsertBulk{
		create: _c,
	}
}

// ReusableInvitationCodeUseUpsertBulk is the builder for "upsert"-ing
// a bulk of ReusableInvitationCodeUse nodes.
type ReusableInvitationCodeUseUpsertBulk struct {
	create *ReusableInvitationCodeUseCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.ReusableInvitationCodeUse.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ReusableInvitationCodeUseUpsertBulk) UpdateNewValues() *ReusableInvitationCodeUseUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ReusableInvitationCodeUse.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ReusableInvitationCodeUseUpsertBulk) Ignore() *ReusableInvitationCodeUseUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ReusableInvitationCodeUseUpsertBulk) DoNothing() *ReusableInvitationCodeUseUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ReusableInvitationCodeUseCreateBulk.OnConflict
// documentation for more info.
func (u *ReusableInvitationCodeUseUpsertBulk) Update(set func(*ReusableInvitationCodeUseUpsert)) *ReusableInvitationCodeUseUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ReusableInvitationCodeUseUpsert{UpdateSet: update})
	}))
	return u
}

// SetCodeID sets the "code_id" field.
func (u *ReusableInvitationCodeUseUpsertBulk) SetCodeID(v int64) *ReusableInvitationCodeUseUpsertBulk {
	return u.Update(func(s *ReusableInvitationCodeUseUpsert) {
		s.SetCodeID(v)
	})
}

// UpdateCodeID sets the "code_id" field to the value that was provided on create.
func (u *ReusableInvitationCodeUseUpsertBulk) UpdateCodeID() *ReusableInvitationCodeUseUpsertBulk {
	return u.Update(func(s *ReusableInvitationCodeUseUpsert) {
		s.UpdateCodeID()
	})
}

// SetUserID sets the "user_id" field.
func (u *ReusableInvitationCodeUseUpsertBulk) SetUserID(v int64) *ReusableInvitationCodeUseUpsertBulk {
	return u.Update(func(s *ReusableInvitationCodeUseUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *ReusableInvitationCodeUseUpsertBulk) UpdateUserID() *ReusableInvitationCodeUseUpsertBulk {
	return u.Update(func(s *ReusableInvitationCodeUseUpsert) {
		s.UpdateUserID()
	})
}

// SetEmail sets the "email" field.
func (u *ReusableInvitationCodeUseUpsertBulk) SetEmail(v string) *ReusableInvitationCodeUseUpsertBulk {
	return u.Update(func(s *ReusableInvitationCodeUseUpsert) {
		s.SetEmail(v)
	})
}

// UpdateEmail sets the "email" field to the value that was provided on create.
func (u *ReusableInvitationCodeUseUpsertBulk) UpdateEmail() *ReusableInvitationCodeUseUpsertBulk {
	return u.Update(func(s *ReusableInvitationCodeUseUpsert) {
		s.UpdateEmail()
	})
}

// SetAuthSource sets the "auth_source" field.
func (u *ReusableInvitationCodeUseUpsertBulk) SetAuthSource(v string) *ReusableInvitationCodeUseUpsertBulk {
	return u.Update(func(s *ReusableInvitationCodeUseUpsert) {
		s.SetAuthSource(v)
	})
}

// UpdateAuthSource sets the "auth_source" field to the value that was provided on create.
func (u *ReusableInvitationCodeUseUpsertBulk) UpdateAuthSource() *ReusableInvitationCodeUseUpsertBulk {
	return u.Update(func(s *ReusableInvitationCodeUseUpsert) {
		s.UpdateAuthSource()
	})
}

// SetUsedAt sets the "used_at" field.
func (u *ReusableInvitationCodeUseUpsertBulk) SetUsedAt(v time.Time) *ReusableInvitationCodeUseUpsertBulk {
	return u.Update(func(s *ReusableInvitationCodeUseUpsert) {
		s.SetUsedAt(v)
	})
}

// UpdateUsedAt sets the "used_at" field to the value that was provided on create.
func (u *ReusableInvitationCodeUseUpsertBulk) UpdateUsedAt() *ReusableInvitationCodeUseUpsertBulk {
	return u.Update(func(s *ReusableInvitationCodeUseUpsert) {
		s.UpdateUsedAt()
	})
}

// Exec executes the query.
func (u *ReusableInvitationCodeUseUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ReusableInvitationCodeUseCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ReusableInvitationCodeUseCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ReusableInvitationCodeUseUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
