// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/LuckyKuang/sub2api-plus/ent/reusableinvitationcode"
	"github.com/LuckyKuang/sub2api-plus/ent/reusableinvitationcodeuse"
	"github.com/LuckyKuang/sub2api-plus/ent/user"
)

// ReusableInvitationCodeUse is the model entity for the ReusableInvitationCodeUse schema.
type ReusableInvitationCodeUse struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CodeID holds the value of the "code_id" field.
	CodeID int64 `json:"code_id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int64 `json:"user_id,omitempty"`
	// Email holds the value of the "email" field.
	Email string `json:"email,omitempty"`
	// AuthSource holds the value of the "auth_source" field.
	AuthSource string `json:"auth_source,omitempty"`
	// UsedAt holds the value of the "used_at" field.
	UsedAt time.Time `json:"used_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ReusableInvitationCodeUseQuery when eager-loading is set.
	Edges        ReusableInvitationCodeUseEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ReusableInvitationCodeUseEdges holds the relations/edges for other nodes in the graph.
type ReusableInvitationCodeUseEdges struct {
	// Code holds the value of the code edge.
	Code *ReusableInvitationCode `json:"code,omitempty"`
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// CodeOrErr returns the Code value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ReusableInvitationCodeUseEdges) CodeOrErr() (*ReusableInvitationCode, error) {
	if e.Code != nil {
		return e.Code, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: reusableinvitationcode.Label}
	}
	return nil, &NotLoadedError{edge: "code"}
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ReusableInvitationCodeUseEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ReusableInvitationCodeUse) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case reusableinvitationcodeuse.FieldID, reusableinvitationcodeuse.FieldCodeID, reusableinvitationcodeuse.FieldUserID:
			values[i] = new(sql.NullInt64)
		case reusableinvitationcodeuse.FieldEmail, reusableinvitationcodeuse.FieldAuthSource:
			values[i] = new(sql.NullString)
		case reusableinvitationcodeuse.FieldUsedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ReusableInvitationCodeUse fields.
func (_m *ReusableInvitationCodeUse) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case reusableinvitationcodeuse.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case reusableinvitationcodeuse.FieldCodeID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field code_id", values[i])
			} else if value.Valid {
				_m.CodeID = value.Int64
			}
		case reusableinvitationcodeuse.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.Int64
			}
		case reusableinvitationcodeuse.FieldEmail:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field email", values[i])
			} else if value.Valid {
				_m.Email = value.String
			}
		case reusableinvitationcodeuse.FieldAuthSource:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field auth_source", values[i])
			} else if value.Valid {
				_m.AuthSource = value.String
			}
		case reusableinvitationcodeuse.FieldUsedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field used_at", values[i])
			} else if value.Valid {
				_m.UsedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ReusableInvitationCodeUse.
// This includes values selected through modifiers, order, etc.
func (_m *ReusableInvitationCodeUse) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryCode queries the "code" edge of the ReusableInvitationCodeUse entity.
func (_m *ReusableInvitationCodeUse) QueryCode() *ReusableInvitationCodeQuery {
	return NewReusableInvitationCodeUseClient(_m.config).QueryCode(_m)
}

// QueryUser queries the "user" edge of the ReusableInvitationCodeUse entity.
func (_m *ReusableInvitationCodeUse) QueryUser() *UserQuery {
	return NewReusableInvitationCodeUseClient(_m.config).QueryUser(_m)
}

// Update returns a builder for updating this ReusableInvitationCodeUse.
// Note that you need to call ReusableInvitationCodeUse.Unwrap() before calling this method if this ReusableInvitationCodeUse
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ReusableInvitationCodeUse) Update() *ReusableInvitationCodeUseUpdateOne {
	return NewReusableInvitationCodeUseClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ReusableInvitationCodeUse entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ReusableInvitationCodeUse) Unwrap() *ReusableInvitationCodeUse {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ReusableInvitationCodeUse is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ReusableInvitationCodeUse) String() string {
	var builder strings.Builder
	builder.WriteString("ReusableInvitationCodeUse(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("code_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.CodeID))
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("email=")
	builder.WriteString(_m.Email)
	builder.WriteString(", ")
	builder.WriteString("auth_source=")
	builder.WriteString(_m.AuthSource)
	builder.WriteString(", ")
	builder.WriteString("used_at=")
	builder.WriteString(_m.UsedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// ReusableInvitationCodeUses is a parsable slice of ReusableInvitationCodeUse.
type ReusableInvitationCodeUses []*ReusableInvitationCodeUse
