// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/LuckyKuang/sub2api-plus/ent/reusableinvitationcode"
	"github.com/LuckyKuang/sub2api-plus/ent/reusableinvitationcodeuse"
)

// ReusableInvitationCodeCreate is the builder for creating a ReusableInvitationCode entity.
type ReusableInvitationCodeCreate struct {
	config
	mutation *ReusableInvitationCodeMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCode sets the "code" field.
func (_c *ReusableInvitationCodeCreate) SetCode(v string) *ReusableInvitationCodeCreate {
	_c.mutation.SetCode(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *ReusableInvitationCodeCreate) SetStatus(v string) *ReusableInvitationCodeCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *ReusableInvitationCodeCreate) SetNillableStatus(v *string) *ReusableInvitationCodeCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetMaxUses sets the "max_uses" field.
func (_c *ReusableInvitationCodeCreate) SetMaxUses(v int) *ReusableInvitationCodeCreate {
	_c.mutation.SetMaxUses(v)
	return _c
}

// SetNillableMaxUses sets the "max_uses" field if the given value is not nil.
func (_c *ReusableInvitationCodeCreate) SetNillableMaxUses(v *int) *ReusableInvitationCodeCreate {
	if v != nil {
		_c.SetMaxUses(*v)
	}
	return _c
}

// SetUsedCount sets the "used_count" field.
func (_c *ReusableInvitationCodeCreate) SetUsedCount(v int) *ReusableInvitationCodeCreate {
	_c.mutation.SetUsedCount(v)
	return _c
}

// SetNillableUsedCount sets the "used_count" field if the given value is not nil.
func (_c *ReusableInvitationCodeCreate) SetNillableUsedCount(v *int) *ReusableInvitationCodeCreate {
	if v != nil {
		_c.SetUsedCount(*v)
	}
	return _c
}

// SetExpiresAt sets the "expires_at" field.
func (_c *ReusableInvitationCodeCreate) SetExpiresAt(v time.Time) *ReusableInvitationCodeCreate {
	_c.mutation.SetExpiresAt(v)
	return _c
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_c *ReusableInvitationCodeCreate) SetNillableExpiresAt(v *time.Time) *ReusableInvitationCodeCreate {
	if v != nil {
		_c.SetExpiresAt(*v)
	}
	return _c
}

// SetNotes sets the "notes" field.
func (_c *ReusableInvitationCodeCreate) SetNotes(v string) *ReusableInvitationCodeCreate {
	_c.mutation.SetNotes(v)
	return _c
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_c *ReusableInvitationCodeCreate) SetNillableNotes(v *string) *ReusableInvitationCodeCreate {
	if v != nil {
		_c.SetNotes(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *ReusableInvitationCodeCreate) SetCreatedAt(v time.Time) *ReusableInvitationCodeCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ReusableInvitationCodeCreate) SetNillableCreatedAt(v *time.Time) *ReusableInvitationCodeCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ReusableInvitationCodeCreate) SetUpdatedAt(v time.Time) *ReusableInvitationCodeCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ReusableInvitationCodeCreate) SetNillableUpdatedAt(v *time.Time) *ReusableInvitationCodeCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// AddUseIDs adds the "uses" edge to the ReusableInvitationCodeUse entity by IDs.
func (_c *ReusableInvitationCodeCreate) AddUseIDs(ids ...int64) *ReusableInvitationCodeCreate {
	_c.mutation.AddUseIDs(ids...)
	return _c
}

// AddUses adds the "uses" edges to the ReusableInvitationCodeUse entity.
func (_c *ReusableInvitationCodeCreate) AddUses(v ...*ReusableInvitationCodeUse) *ReusableInvitationCodeCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddUseIDs(ids...)
}

// Mutation returns the ReusableInvitationCodeMutation object of the builder.
func (_c *ReusableInvitationCodeCreate) Mutation() *ReusableInvitationCodeMutation {
	return _c.mutation
}

// Save creates the ReusableInvitationCode in the database.
func (_c *ReusableInvitationCodeCreate) Save(ctx context.Context) (*ReusableInvitationCode, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ReusableInvitationCodeCreate) SaveX(ctx context.Context) *ReusableInvitationCode {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ReusableInvitationCodeCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ReusableInvitationCodeCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ReusableInvitationCodeCreate) defaults() {
	if _, ok := _c.mutation.Status(); !ok {
		v := reusableinvitationcode.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.MaxUses(); !ok {
		v := reusableinvitationcode.DefaultMaxUses
		_c.mutation.SetMaxUses(v)
	}
	if _, ok := _c.mutation.UsedCount(); !ok {
		v := reusableinvitationcode.DefaultUsedCount
		_c.mutation.SetUsedCount(v)
	}
	if _, ok := _c.mutation.Notes(); !ok {
		v := reusableinvitationcode.DefaultNotes
		_c.mutation.SetNotes(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := reusableinvitationcode.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := reusableinvitationcode.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ReusableInvitationCodeCreate) check() error {
	if _, ok := _c.mutation.Code(); !ok {
		return &ValidationError{Name: "code", err: errors.New(`ent: missing required field "ReusableInvitationCode.code"`)}
	}
	if v, ok := _c.mutation.Code(); ok {
		if err := reusableinvitationcode.CodeValidator(v); err != nil {
			return &ValidationError{Name: "code", err: fmt.Errorf(`ent: validator failed for field "ReusableInvitationCode.code": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "ReusableInvitationCode.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := reusableinvitationcode.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "ReusableInvitationCode.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.MaxUses(); !ok {
		return &ValidationError{Name: "max_uses", err: errors.New(`ent: missing required field "ReusableInvitationCode.max_uses"`)}
	}
	if v, ok := _c.mutation.MaxUses(); ok {
		if err := reusableinvitationcode.MaxUsesValidator(v); err != nil {
			return &ValidationError{Name: "max_uses", err: fmt.Errorf(`ent: validator failed for field "ReusableInvitationCode.max_uses": %w`, err)}
		}
	}
	if _, ok := _c.mutation.UsedCount(); !ok {
		return &ValidationError{Name: "used_count", err: errors.New(`ent: missing required field "ReusableInvitationCode.used_count"`)}
	}
	if v, ok := _c.mutation.UsedCount(); ok {
		if err := reusableinvitationcode.UsedCountValidator(v); err != nil {
			return &ValidationError{Name: "used_count", err: fmt.Errorf(`ent: validator failed for field "ReusableInvitationCode.used_count": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Notes(); !ok {
		return &ValidationError{Name: "notes", err: errors.New(`ent: missing required field "ReusableInvitationCode.notes"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ReusableInvitationCode.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "ReusableInvitationCode.updated_at"`)}
	}
	return nil
}

func (_c *ReusableInvitationCodeCreate) sqlSave(ctx context.Context) (*ReusableInvitationCode, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ReusableInvitationCodeCreate) createSpec() (*ReusableInvitationCode, *sqlgraph.CreateSpec) {
	var (
		_node = &ReusableInvitationCode{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(reusableinvitationcode.Table, sqlgraph.NewFieldSpec(reusableinvitationcode.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.Code(); ok {
		_spec.SetField(reusableinvitationcode.FieldCode, field.TypeString, value)
		_node.Code = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(reusableinvitationcode.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.MaxUses(); ok {
		_spec.SetField(reusableinvitationcode.FieldMaxUses, field.TypeInt, value)
		_node.MaxUses = value
	}
	if value, ok := _c.mutation.UsedCount(); ok {
		_spec.SetField(reusableinvitationcode.FieldUsedCount, field.TypeInt, value)
		_node.UsedCount = value
	}
	if value, ok := _c.mutation.ExpiresAt(); ok {
		_spec.SetField(reusableinvitationcode.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = &value
	}
	if value, ok := _c.mutation.Notes(); ok {
		_spec.SetField(reusableinvitationcode.FieldNotes, field.TypeString, value)
		_node.Notes = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(reusableinvitationcode.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(reusableinvitationcode.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.UsesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   reusableinvitationcode.UsesTable,
			Columns: []string{reusableinvitationcode.UsesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(reusableinvitationcodeuse.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ReusableInvitationCode.Create().
//		SetCode(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ReusableInvitationCodeUpsert) {
//			SetCode(v+v).
//		}).
//		Exec(ctx)
func (_c *ReusableInvitationCodeCreate) OnConflict(opts ...sql.ConflictOption) *ReusableInvitationCodeUpsertOne {
	_c.conflict = opts
	return &ReusableInvitationCodeUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ReusableInvitationCode.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ReusableInvitationCodeCreate) OnConflictColumns(columns ...string) *ReusableInvitationCodeUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ReusableInvitationCodeUpsertOne{
		create: _c,
	}
}

type (
	// ReusableInvitationCodeUpsertOne is the builder for "upsert"-ing
	//  one ReusableInvitationCode node.
	ReusableInvitationCodeUpsertOne struct {
		create *ReusableInvitationCodeCreate
	}

	// ReusableInvitationCodeUpsert is the "OnConflict" setter.
	ReusableInvitationCodeUpsert struct {
		*sql.UpdateSet
	}
)

// SetCode sets the "code" field.
func (u *ReusableInvitationCodeUpsert) SetCode(v string) *ReusableInvitationCodeUpsert {
	u.Set(reusableinvitationcode.FieldCode, v)
	return u
}

// UpdateCode sets the "code" field to the value that was provided on create.
func (u *ReusableInvitationCodeUpsert) UpdateCode() *ReusableInvitationCodeUpsert {
	u.SetExcluded(reusableinvitationcode.FieldCode)
	return u
}

// SetStatus sets the "status" field.
func (u *ReusableInvitationCodeUpsert) SetStatus(v string) *ReusableInvitationCodeUpsert {
	u.Set(reusableinvitationcode.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *ReusableInvitationCodeUpsert) UpdateStatus() *ReusableInvitationCodeUpsert {
	u.SetExcluded(reusableinvitationcode.FieldStatus)
	return u
}

// SetMaxUses sets the "max_uses" field.
func (u *ReusableInvitationCodeUpsert) SetMaxUses(v int) *ReusableInvitationCodeUpsert {
	u.Set(reusableinvitationcode.FieldMaxUses, v)
	return u
}

// UpdateMaxUses sets the "max_uses" field to the value that was provided on create.
func (u *ReusableInvitationCodeUpsert) UpdateMaxUses() *ReusableInvitationCodeUpsert {
	u.SetExcluded(reusableinvitationcode.FieldMaxUses)
	return u
}

// AddMaxUses adds v to the "max_uses" field.
func (u *ReusableInvitationCodeUpsert) AddMaxUses(v int) *ReusableInvitationCodeUpsert {
	u.Add(reusableinvitationcode.FieldMaxUses, v)
	return u
}

// SetUsedCount sets the "used_count" field.
func (u *ReusableInvitationCodeUpsert) SetUsedCount(v int) *ReusableInvitationCodeUpsert {
	u.Set(reusableinvitationcode.FieldUsedCount, v)
	return u
}

// UpdateUsedCount sets the "used_count" field to the value that was provided on create.
func (u *ReusableInvitationCodeUpsert) UpdateUsedCount() *ReusableInvitationCodeUpsert {
	u.SetExcluded(reusableinvitationcode.FieldUsedCount)
	return u
}

// AddUsedCount adds v to the "used_count" field.
func (u *ReusableInvitationCodeUpsert) AddUsedCount(v int) *ReusableInvitationCodeUpsert {
	u.Add(reusableinvitationcode.FieldUsedCount, v)
	return u
}

// SetExpiresAt sets the "expires_at" field.
func (u *ReusableInvitationCodeUpsert) SetExpiresAt(v time.Time) *ReusableInvitationCodeUpsert {
	u.Set(reusableinvitationcode.FieldExpiresAt, v)
	return u
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *ReusableInvitationCodeUpsert) UpdateExpiresAt() *ReusableInvitationCodeUpsert {
	u.SetExcluded(reusableinvitationcode.FieldExpiresAt)
	return u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (u *ReusableInvitationCodeUpsert) ClearExpiresAt() *ReusableInvitationCodeUpsert {
	u.SetNull(reusableinvitationcode.FieldExpiresAt)
	return u
}

// SetNotes sets the "notes" field.
func (u *ReusableInvitationCodeUpsert) SetNotes(v string) *ReusableInvitationCodeUpsert {
	u.Set(reusableinvitationcode.FieldNotes, v)
	return u
}

// UpdateNotes sets the "notes" field to the value that was provided on create.
func (u *ReusableInvitationCodeUpsert) UpdateNotes() *ReusableInvitationCodeUpsert {
	u.SetExcluded(reusableinvitationcode.FieldNotes)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ReusableInvitationCodeUpsert) SetUpdatedAt(v time.Time) *ReusableInvitationCodeUpsert {
	u.Set(reusableinvitationcode.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ReusableInvitationCodeUpsert) UpdateUpdatedAt() *ReusableInvitationCodeUpsert {
	u.SetExcluded(reusableinvitationcode.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.ReusableInvitationCode.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ReusableInvitationCodeUpsertOne) UpdateNewValues() *ReusableInvitationCodeUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(reusableinvitationcode.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ReusableInvitationCode.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ReusableInvitationCodeUpsertOne) Ignore() *ReusableInvitationCodeUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ReusableInvitationCodeUpsertOne) DoNothing() *ReusableInvitationCodeUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ReusableInvitationCodeCreate.OnConflict
// documentation for more info.
func (u *ReusableInvitationCodeUpsertOne) Update(set func(*ReusableInvitationCodeUpsert)) *ReusableInvitationCodeUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ReusableInvitationCodeUpsert{UpdateSet: update})
	}))
	return u
}

// SetCode sets the "code" field.
func (u *ReusableInvitationCodeUpsertOne) SetCode(v string) *ReusableInvitationCodeUpsertOne {
	return u.Update(func(s *ReusableInvitationCodeUpsert) {
		s.SetCode(v)
	})
}

// UpdateCode sets the "code" field to the value that was provided on create.
func (u *ReusableInvitationCodeUpsertOne) UpdateCode() *ReusableInvitationCodeUpsertOne {
	return u.Update(func(s *ReusableInvitationCodeUpsert) {
		s.UpdateCode()
	})
}

// SetStatus sets the "status" field.
func (u *ReusableInvitationCodeUpsertOne) SetStatus(v string) *ReusableInvitationCodeUpsertOne {
	return u.Update(func(s *ReusableInvitationCodeUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *ReusableInvitationCodeUpsertOne) UpdateStatus() *ReusableInvitationCodeUpsertOne {
	return u.Update(func(s *ReusableInvitationCodeUpsert) {
		s.UpdateStatus()
	})
}

// SetMaxUses sets the "max_uses" field.
func (u *ReusableInvitationCodeUpsertOne) SetMaxUses(v int) *ReusableInvitationCodeUpsertOne {
	return u.Update(func(s *ReusableInvitationCodeUpsert) {
		s.SetMaxUses(v)
	})
}

// AddMaxUses adds v to the "max_uses" field.
func (u *ReusableInvitationCodeUpsertOne) AddMaxUses(v int) *ReusableInvitationCodeUpsertOne {
	return u.Update(func(s *ReusableInvitationCodeUpsert) {
		s.AddMaxUses(v)
	})
}

// UpdateMaxUses sets the "max_uses" field to the value that was provided on create.
func (u *ReusableInvitationCodeUpsertOne) UpdateMaxUses() *ReusableInvitationCodeUpsertOne {
	return u.Update(func(s *ReusableInvitationCodeUpsert) {
		s.UpdateMaxUses()
	})
}

// SetUsedCount sets the "used_count" field.
func (u *ReusableInvitationCodeUpsertOne) SetUsedCount(v int) *ReusableInvitationCodeUpsertOne {
	return u.Update(func(s *ReusableInvitationCodeUpsert) {
		s.SetUsedCount(v)
	})
}

// AddUsedCount adds v to the "used_count" field.
func (u *ReusableInvitationCodeUpsertOne) AddUsedCount(v int) *ReusableInvitationCodeUpsertOne {
	return u.Update(func(s *ReusableInvitationCodeUpsert) {
		s.AddUsedCount(v)
	})
}

// UpdateUsedCount sets the "used_count" field to the value that was provided on create.
func (u *ReusableInvitationCodeUpsertOne) UpdateUsedCount() *ReusableInvitationCodeUpsertOne {
	return u.Update(func(s *ReusableInvitationCodeUpsert) {
		s.UpdateUsedCount()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *ReusableInvitationCodeUpsertOne) SetExpiresAt(v time.Time) *ReusableInvitationCodeUpsertOne {
	return u.Update(func(s *ReusableInvitationCodeUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *ReusableInvitationCodeUpsertOne) UpdateExpiresAt() *ReusableInvitationCodeUpsertOne {
	return u.Update(func(s *ReusableInvitationCodeUpsert) {
		s.UpdateExpiresAt()
	})
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (u *ReusableInvitationCodeUpsertOne) ClearExpiresAt() *ReusableInvitationCodeUpsertOne {
	return u.Update(func(s *ReusableInvitationCodeUpsert) {
		s.ClearExpiresAt()
	})
}

// SetNotes sets the "notes" field.
func (u *ReusableInvitationCodeUpsertOne) SetNotes(v string) *ReusableInvitationCodeUpsertOne {
	return u.Update(func(s *ReusableInvitationCodeUpsert) {
		s.SetNotes(v)
	})
}

// UpdateNotes sets the "notes" field to the value that was provided on create.
func (u *ReusableInvitationCodeUpsertOne) UpdateNotes() *ReusableInvitationCodeUpsertOne {
	return u.Update(func(s *ReusableInvitationCodeUpsert) {
		s.UpdateNotes()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ReusableInvitationCodeUpsertOne) SetUpdatedAt(v time.Time) *ReusableInvitationCodeUpsertOne {
	return u.Update(func(s *ReusableInvitationCodeUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ReusableInvitationCodeUpsertOne) UpdateUpdatedAt() *ReusableInvitationCodeUpsertOne {
	return u.Update(func(s *ReusableInvitationCodeUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *ReusableInvitationCodeUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ReusableInvitationCodeCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ReusableInvitationCodeUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ReusableInvitationCodeUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ReusableInvitationCodeUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ReusableInvitationCodeCreateBulk is the builder for creating many ReusableInvitationCode entities in bulk.
type ReusableInvitationCodeCreateBulk struct {
	config
	err      error
	builders []*ReusableInvitationCodeCreate
	conflict []sql.ConflictOption
}

// Save creates the ReusableInvitationCode entities in the database.
func (_c *ReusableInvitationCodeCreateBulk) Save(ctx context.Context) ([]*ReusableInvitationCode, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ReusableInvitationCode, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ReusableInvitationCodeMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ReusableInvitationCodeCreateBulk) SaveX(ctx context.Context) []*ReusableInvitationCode {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ReusableInvitationCodeCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ReusableInvitationCodeCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ReusableInvitationCode.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ReusableInvitationCodeUpsert) {
//			SetCode(v+v).
//		}).
//		Exec(ctx)
func (_c *ReusableInvitationCodeCreateBulk) OnConflict(opts ...sql.ConflictOption) *ReusableInvitationCodeUpsertBulk {
	_c.conflict = opts
	return &ReusableInvitationCodeUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ReusableInvitationCode.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ReusableInvitationCodeCreateBulk) OnConflictColumns(columns ...string) *ReusableInvitationCodeUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ReusableInvitationCodeUpsertBulk{
		create: _c,
	}
}

// ReusableInvitationCodeUpsertBulk is the builder for "upsert"-ing
// a bulk of ReusableInvitationCode nodes.
type ReusableInvitationCodeUpsertBulk struct {
	create *ReusableInvitationCodeCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.ReusableInvitationCode.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ReusableInvitationCodeUpsertBulk) UpdateNewValues() *ReusableInvitationCodeUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(reusableinvitationcode.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ReusableInvitationCode.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ReusableInvitationCodeUpsertBulk) Ignore() *ReusableInvitationCodeUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ReusableInvitationCodeUpsertBulk) DoNothing() *ReusableInvitationCodeUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ReusableInvitationCodeCreateBulk.OnConflict
// documentation for more info.
func (u *ReusableInvitationCodeUpsertBulk) Update(set func(*ReusableInvitationCodeUpsert)) *ReusableInvitationCodeUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ReusableInvitationCodeUpsert{UpdateSet: update})
	}))
	return u
}

// SetCode sets the "code" field.
func (u *ReusableInvitationCodeUpsertBulk) SetCode(v string) *ReusableInvitationCodeUpsertBulk {
	return u.Update(func(s *ReusableInvitationCodeUpsert) {
		s.SetCode(v)
	})
}

// UpdateCode sets the "code" field to the value that was provided on create.
func (u *ReusableInvitationCodeUpsertBulk) UpdateCode() *ReusableInvitationCodeUpsertBulk {
	return u.Update(func(s *ReusableInvitationCodeUpsert) {
		s.UpdateCode()
	})
}

// SetStatus sets the "status" field.
func (u *ReusableInvitationCodeUpsertBulk) SetStatus(v string) *ReusableInvitationCodeUpsertBulk {
	return u.Update(func(s *ReusableInvitationCodeUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *ReusableInvitationCodeUpsertBulk) UpdateStatus() *ReusableInvitationCodeUpsertBulk {
	return u.Update(func(s *ReusableInvitationCodeUpsert) {
		s.UpdateStatus()
	})
}

// SetMaxUses sets the "max_uses" field.
func (u *ReusableInvitationCodeUpsertBulk) SetMaxUses(v int) *ReusableInvitationCodeUpsertBulk {
	return u.Update(func(s *ReusableInvitationCodeUpsert) {
		s.SetMaxUses(v)
	})
}

// AddMaxUses adds v to the "max_uses" field.
func (u *ReusableInvitationCodeUpsertBulk) AddMaxUses(v int) *ReusableInvitationCodeUpsertBulk {
	return u.Update(func(s *ReusableInvitationCodeUpsert) {
		s.AddMaxUses(v)
	})
}

// UpdateMaxUses sets the "max_uses" field to the value that was provided on create.
func (u *ReusableInvitationCodeUpsertBulk) UpdateMaxUses() *ReusableInvitationCodeUpsertBulk {
	return u.Update(func(s *ReusableInvitationCodeUpsert) {
		s.UpdateMaxUses()
	})
}

// SetUsedCount sets the "used_count" field.
func (u *ReusableInvitationCodeUpsertBulk) SetUsedCount(v int) *ReusableInvitationCodeUpsertBulk {
	return u.Update(func(s *ReusableInvitationCodeUpsert) {
		s.SetUsedCount(v)
	})
}

// AddUsedCount adds v to the "used_count" field.
func (u *ReusableInvitationCodeUpsertBulk) AddUsedCount(v int) *ReusableInvitationCodeUpsertBulk {
	return u.Update(func(s *ReusableInvitationCodeUpsert) {
		s.AddUsedCount(v)
	})
}

// UpdateUsedCount sets the "used_count" field to the value that was provided on create.
func (u *ReusableInvitationCodeUpsertBulk) UpdateUsedCount() *ReusableInvitationCodeUpsertBulk {
	return u.Update(func(s *ReusableInvitationCodeUpsert) {
		s.UpdateUsedCount()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *ReusableInvitationCodeUpsertBulk) SetExpiresAt(v time.Time) *ReusableInvitationCodeUpsertBulk {
	return u.Update(func(s *ReusableInvitationCodeUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *ReusableInvitationCodeUpsertBulk) UpdateExpiresAt() *ReusableInvitationCodeUpsertBulk {
	return u.Update(func(s *ReusableInvitationCodeUpsert) {
		s.UpdateExpiresAt()
	})
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (u *ReusableInvitationCodeUpsertBulk) ClearExpiresAt() *ReusableInvitationCodeUpsertBulk {
	return u.Update(func(s *ReusableInvitationCodeUpsert) {
		s.ClearExpiresAt()
	})
}

// SetNotes sets the "notes" field.
func (u *ReusableInvitationCodeUpsertBulk) SetNotes(v string) *ReusableInvitationCodeUpsertBulk {
	return u.Update(func(s *ReusableInvitationCodeUpsert) {
		s.SetNotes(v)
	})
}

// UpdateNotes sets the "notes" field to the value that was provided on create.
func (u *ReusableInvitationCodeUpsertBulk) UpdateNotes() *ReusableInvitationCodeUpsertBulk {
	return u.Update(func(s *ReusableInvitationCodeUpsert) {
		s.UpdateNotes()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ReusableInvitationCodeUpsertBulk) SetUpdatedAt(v time.Time) *ReusableInvitationCodeUpsertBulk {
	return u.Update(func(s *ReusableInvitationCodeUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ReusableInvitationCodeUpsertBulk) UpdateUpdatedAt() *ReusableInvitationCodeUpsertBulk {
	return u.Update(func(s *ReusableInvitationCodeUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *ReusableInvitationCodeUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ReusableInvitationCodeCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ReusableInvitationCodeCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ReusableInvitationCodeUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
