// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/LuckyKuang/sub2api-plus/ent/predicate"
	"github.com/LuckyKuang/sub2api-plus/ent/reusableinvitationcode"
	"github.com/LuckyKuang/sub2api-plus/ent/reusableinvitationcodeuse"
	"github.com/LuckyKuang/sub2api-plus/ent/user"
)

// ReusableInvitationCodeUseUpdate is the builder for updating ReusableInvitationCodeUse entities.
type ReusableInvitationCodeUseUpdate struct {
	config
	hooks    []Hook
	mutation *ReusableInvitationCodeUseMutation
}

// Where appends a list predicates to the ReusableInvitationCodeUseUpdate builder.
func (_u *ReusableInvitationCodeUseUpdate) Where(ps ...predicate.ReusableInvitationCodeUse) *ReusableInvitationCodeUseUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetCodeID sets the "code_id" field.
func (_u *ReusableInvitationCodeUseUpdate) SetCodeID(v int64) *ReusableInvitationCodeUseUpdate {
	_u.mutation.SetCodeID(v)
	return _u
}

// SetNillableCodeID sets the "code_id" field if the given value is not nil.
func (_u *ReusableInvitationCodeUseUpdate) SetNillableCodeID(v *int64) *ReusableInvitationCodeUseUpdate {
	if v != nil {
		_u.SetCodeID(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *ReusableInvitationCodeUseUpdate) SetUserID(v int64) *ReusableInvitationCodeUseUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *ReusableInvitationCodeUseUpdate) SetNillableUserID(v *int64) *ReusableInvitationCodeUseUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetEmail sets the "email" field.
func (_u *ReusableInvitationCodeUseUpdate) SetEmail(v string) *ReusableInvitationCodeUseUpdate {
	_u.mutation.SetEmail(v)
	return _u
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (_u *ReusableInvitationCodeUseUpdate) SetNillableEmail(v *string) *ReusableInvitationCodeUseUpdate {
	if v != nil {
		_u.SetEmail(*v)
	}
	return _u
}

// SetAuthSource sets the "auth_source" field.
func (_u *ReusableInvitationCodeUseUpdate) SetAuthSource(v string) *ReusableInvitationCodeUseUpdate {
	_u.mutation.SetAuthSource(v)
	return _u
}

// SetNillableAuthSource sets the "auth_source" field if the given value is not nil.
func (_u *ReusableInvitationCodeUseUpdate) SetNillableAuthSource(v *string) *ReusableInvitationCodeUseUpdate {
	if v != nil {
		_u.SetAuthSource(*v)
	}
	return _u
}

// SetUsedAt sets the "used_at" field.
func (_u *ReusableInvitationCodeUseUpdate) SetUsedAt(v time.Time) *ReusableInvitationCodeUseUpdate {
	_u.mutation.SetUsedAt(v)
	return _u
}

// SetNillableUsedAt sets the "used_at" field if the given value is not nil.
func (_u *ReusableInvitationCodeUseUpdate) SetNillableUsedAt(v *time.Time) *ReusableInvitationCodeUseUpdate {
	if v != nil {
		_u.SetUsedAt(*v)
	}
	return _u
}

// SetCode sets the "code" edge to the ReusableInvitationCode entity.
func (_u *ReusableInvitationCodeUseUpdate) SetCode(v *ReusableInvitationCode) *ReusableInvitationCodeUseUpdate {
	return _u.SetCodeID(v.ID)
}

// SetUser sets the "user" edge to the User entity.
func (_u *ReusableInvitationCodeUseUpdate) SetUser(v *User) *ReusableInvitationCodeUseUpdate {
	return _u.SetUserID(v.ID)
}

// Mutation returns the ReusableInvitationCodeUseMutation object of the builder.
func (_u *ReusableInvitationCodeUseUpdate) Mutation() *ReusableInvitationCodeUseMutation {
	return _u.mutation
}

// ClearCode clears the "code" edge to the ReusableInvitationCode entity.
func (_u *ReusableInvitationCodeUseUpdate) ClearCode() *ReusableInvitationCodeUseUpdate {
	_u.mutation.ClearCode()
	return _u
}

// ClearUser clears the "user" edge to the User entity.
func (_u *ReusableInvitationCodeUseUpdate) ClearUser() *ReusableInvitationCodeUseUpdate {
	_u.mutation.ClearUser()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ReusableInvitationCodeUseUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ReusableInvitationCodeUseUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ReusableInvitationCodeUseUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ReusableInvitationCodeUseUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ReusableInvitationCodeUseUpdate) check() error {
	if v, ok := _u.mutation.Email(); ok {
		if err := reusableinvitationcodeuse.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "ReusableInvitationCodeUse.email": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AuthSource(); ok {
		if err := reusableinvitationcodeuse.AuthSourceValidator(v); err != nil {
			return &ValidationError{Name: "auth_source", err: fmt.Errorf(`ent: validator failed for field "ReusableInvitationCodeUse.auth_source": %w`, err)}
		}
	}
	if _u.mutation.CodeCleared() && len(_u.mutation.CodeIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ReusableInvitationCodeUse.code"`)
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ReusableInvitationCodeUse.user"`)
	}
	return nil
}

func (_u *ReusableInvitationCodeUseUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(reusableinvitationcodeuse.Table, reusableinvitationcodeuse.Columns, sqlgraph.NewFieldSpec(reusableinvitationcodeuse.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Email(); ok {
		_spec.SetField(reusableinvitationcodeuse.FieldEmail, field.TypeString, value)
	}
	if value, ok := _u.mutation.AuthSource(); ok {
		_spec.SetField(reusableinvitationcodeuse.FieldAuthSource, field.TypeString, value)
	}
	if value, ok := _u.mutation.UsedAt(); ok {
		_spec.SetField(reusableinvitationcodeuse.FieldUsedAt, field.TypeTime, value)
	}
	if _u.mutation.CodeCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   reusableinvitationcodeuse.CodeTable,
			Columns: []string{reusableinvitationcodeuse.CodeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(reusableinvitationcode.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CodeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   reusableinvitationcodeuse.CodeTable,
			Columns: []string{reusableinvitationcodeuse.CodeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(reusableinvitationcode.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   reusableinvitationcodeuse.UserTable,
			Columns: []string{reusableinvitationcodeuse.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   reusableinvitationcodeuse.UserTable,
			Columns: []string{reusableinvitationcodeuse.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{reusableinvitationcodeuse.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ReusableInvitationCodeUseUpdateOne is the builder for updating a single ReusableInvitationCodeUse entity.
type ReusableInvitationCodeUseUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ReusableInvitationCodeUseMutation
}

// SetCodeID sets the "code_id" field.
func (_u *ReusableInvitationCodeUseUpdateOne) SetCodeID(v int64) *ReusableInvitationCodeUseUpdateOne {
	_u.mutation.SetCodeID(v)
	return _u
}

// SetNillableCodeID sets the "code_id" field if the given value is not nil.
func (_u *ReusableInvitationCodeUseUpdateOne) SetNillableCodeID(v *int64) *ReusableInvitationCodeUseUpdateOne {
	if v != nil {
		_u.SetCodeID(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *ReusableInvitationCodeUseUpdateOne) SetUserID(v int64) *ReusableInvitationCodeUseUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *ReusableInvitationCodeUseUpdateOne) SetNillableUserID(v *int64) *ReusableInvitationCodeUseUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetEmail sets the "email" field.
func (_u *ReusableInvitationCodeUseUpdateOne) SetEmail(v string) *ReusableInvitationCodeUseUpdateOne {
	_u.mutation.SetEmail(v)
	return _u
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (_u *ReusableInvitationCodeUseUpdateOne) SetNillableEmail(v *string) *ReusableInvitationCodeUseUpdateOne {
	if v != nil {
		_u.SetEmail(*v)
	}
	return _u
}

// SetAuthSource sets the "auth_source" field.
func (_u *ReusableInvitationCodeUseUpdateOne) SetAuthSource(v string) *ReusableInvitationCodeUseUpdateOne {
	_u.mutation.SetAuthSource(v)
	return _u
}

// SetNillableAuthSource sets the "auth_source" field if the given value is not nil.
func (_u *ReusableInvitationCodeUseUpdateOne) SetNillableAuthSource(v *string) *ReusableInvitationCodeUseUpdateOne {
	if v != nil {
		_u.SetAuthSource(*v)
	}
	return _u
}

// SetUsedAt sets the "used_at" field.
func (_u *ReusableInvitationCodeUseUpdateOne) SetUsedAt(v time.Time) *ReusableInvitationCodeUseUpdateOne {
	_u.mutation.SetUsedAt(v)
	return _u
}

// SetNillableUsedAt sets the "used_at" field if the given value is not nil.
func (_u *ReusableInvitationCodeUseUpdateOne) SetNillableUsedAt(v *time.Time) *ReusableInvitationCodeUseUpdateOne {
	if v != nil {
		_u.SetUsedAt(*v)
	}
	return _u
}

// SetCode sets the "code" edge to the ReusableInvitationCode entity.
func (_u *ReusableInvitationCodeUseUpdateOne) SetCode(v *ReusableInvitationCode) *ReusableInvitationCodeUseUpdateOne {
	return _u.SetCodeID(v.ID)
}

// SetUser sets the "user" edge to the User entity.
func (_u *ReusableInvitationCodeUseUpdateOne) SetUser(v *User) *ReusableInvitationCodeUseUpdateOne {
	return _u.SetUserID(v.ID)
}

// Mutation returns the ReusableInvitationCodeUseMutation object of the builder.
func (_u *ReusableInvitationCodeUseUpdateOne) Mutation() *ReusableInvitationCodeUseMutation {
	return _u.mutation
}

// ClearCode clears the "code" edge to the ReusableInvitationCode entity.
func (_u *ReusableInvitationCodeUseUpdateOne) ClearCode() *ReusableInvitationCodeUseUpdateOne {
	_u.mutation.ClearCode()
	return _u
}

// ClearUser clears the "user" edge to the User entity.
func (_u *ReusableInvitationCodeUseUpdateOne) ClearUser() *ReusableInvitationCodeUseUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// Where appends a list predicates to the ReusableInvitationCodeUseUpdate builder.
func (_u *ReusableInvitationCodeUseUpdateOne) Where(ps ...predicate.ReusableInvitationCodeUse) *ReusableInvitationCodeUseUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ReusableInvitationCodeUseUpdateOne) Select(field string, fields ...string) *ReusableInvitationCodeUseUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ReusableInvitationCodeUse entity.
func (_u *ReusableInvitationCodeUseUpdateOne) Save(ctx context.Context) (*ReusableInvitationCodeUse, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ReusableInvitationCodeUseUpdateOne) SaveX(ctx context.Context) *ReusableInvitationCodeUse {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ReusableInvitationCodeUseUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ReusableInvitationCodeUseUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ReusableInvitationCodeUseUpdateOne) check() error {
	if v, ok := _u.mutation.Email(); ok {
		if err := reusableinvitationcodeuse.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "ReusableInvitationCodeUse.email": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AuthSource(); ok {
		if err := reusableinvitationcodeuse.AuthSourceValidator(v); err != nil {
			return &ValidationError{Name: "auth_source", err: fmt.Errorf(`ent: validator failed for field "ReusableInvitationCodeUse.auth_source": %w`, err)}
		}
	}
	if _u.mutation.CodeCleared() && len(_u.mutation.CodeIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ReusableInvitationCodeUse.code"`)
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ReusableInvitationCodeUse.user"`)
	}
	return nil
}

func (_u *ReusableInvitationCodeUseUpdateOne) sqlSave(ctx context.Context) (_node *ReusableInvitationCodeUse, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(reusableinvitationcodeuse.Table, reusableinvitationcodeuse.Columns, sqlgraph.NewFieldSpec(reusableinvitationcodeuse.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ReusableInvitationCodeUse.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, reusableinvitationcodeuse.FieldID)
		for _, f := range fields {
			if !reusableinvitationcodeuse.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != reusableinvitationcodeuse.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Email(); ok {
		_spec.SetField(reusableinvitationcodeuse.FieldEmail, field.TypeString, value)
	}
	if value, ok := _u.mutation.AuthSource(); ok {
		_spec.SetField(reusableinvitationcodeuse.FieldAuthSource, field.TypeString, value)
	}
	if value, ok := _u.mutation.UsedAt(); ok {
		_spec.SetField(reusableinvitationcodeuse.FieldUsedAt, field.TypeTime, value)
	}
	if _u.mutation.CodeCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   reusableinvitationcodeuse.CodeTable,
			Columns: []string{reusableinvitationcodeuse.CodeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(reusableinvitationcode.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CodeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   reusableinvitationcodeuse.CodeTable,
			Columns: []string{reusableinvitationcodeuse.CodeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(reusableinvitationcode.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   reusableinvitationcodeuse.UserTable,
			Columns: []string{reusableinvitationcodeuse.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   reusableinvitationcodeuse.UserTable,
			Columns: []string{reusableinvitationcodeuse.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &ReusableInvitationCodeUse{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{reusableinvitationcodeuse.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
