// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/LuckyKuang/sub2api-plus/ent/predicate"
	"github.com/LuckyKuang/sub2api-plus/ent/team"
	"github.com/LuckyKuang/sub2api-plus/ent/teaminvitation"
)

// TeamInvitationUpdate is the builder for updating TeamInvitation entities.
type TeamInvitationUpdate struct {
	config
	hooks    []Hook
	mutation *TeamInvitationMutation
}

// Where appends a list predicates to the TeamInvitationUpdate builder.
func (_u *TeamInvitationUpdate) Where(ps ...predicate.TeamInvitation) *TeamInvitationUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *TeamInvitationUpdate) SetUpdatedAt(v time.Time) *TeamInvitationUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetTeamID sets the "team_id" field.
func (_u *TeamInvitationUpdate) SetTeamID(v int64) *TeamInvitationUpdate {
	_u.mutation.SetTeamID(v)
	return _u
}

// SetNillableTeamID sets the "team_id" field if the given value is not nil.
func (_u *TeamInvitationUpdate) SetNillableTeamID(v *int64) *TeamInvitationUpdate {
	if v != nil {
		_u.SetTeamID(*v)
	}
	return _u
}

// SetInviterUserID sets the "inviter_user_id" field.
func (_u *TeamInvitationUpdate) SetInviterUserID(v int64) *TeamInvitationUpdate {
	_u.mutation.ResetInviterUserID()
	_u.mutation.SetInviterUserID(v)
	return _u
}

// SetNillableInviterUserID sets the "inviter_user_id" field if the given value is not nil.
func (_u *TeamInvitationUpdate) SetNillableInviterUserID(v *int64) *TeamInvitationUpdate {
	if v != nil {
		_u.SetInviterUserID(*v)
	}
	return _u
}

// AddInviterUserID adds value to the "inviter_user_id" field.
func (_u *TeamInvitationUpdate) AddInviterUserID(v int64) *TeamInvitationUpdate {
	_u.mutation.AddInviterUserID(v)
	return _u
}

// SetEmail sets the "email" field.
func (_u *TeamInvitationUpdate) SetEmail(v string) *TeamInvitationUpdate {
	_u.mutation.SetEmail(v)
	return _u
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (_u *TeamInvitationUpdate) SetNillableEmail(v *string) *TeamInvitationUpdate {
	if v != nil {
		_u.SetEmail(*v)
	}
	return _u
}

// SetTokenHash sets the "token_hash" field.
func (_u *TeamInvitationUpdate) SetTokenHash(v string) *TeamInvitationUpdate {
	_u.mutation.SetTokenHash(v)
	return _u
}

// SetNillableTokenHash sets the "token_hash" field if the given value is not nil.
func (_u *TeamInvitationUpdate) SetNillableTokenHash(v *string) *TeamInvitationUpdate {
	if v != nil {
		_u.SetTokenHash(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *TeamInvitationUpdate) SetStatus(v string) *TeamInvitationUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *TeamInvitationUpdate) SetNillableStatus(v *string) *TeamInvitationUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *TeamInvitationUpdate) SetExpiresAt(v time.Time) *TeamInvitationUpdate {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *TeamInvitationUpdate) SetNillableExpiresAt(v *time.Time) *TeamInvitationUpdate {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// SetAcceptedByUserID sets the "accepted_by_user_id" field.
func (_u *TeamInvitationUpdate) SetAcceptedByUserID(v int64) *TeamInvitationUpdate {
	_u.mutation.ResetAcceptedByUserID()
	_u.mutation.SetAcceptedByUserID(v)
	return _u
}

// SetNillableAcceptedByUserID sets the "accepted_by_user_id" field if the given value is not nil.
func (_u *TeamInvitationUpdate) SetNillableAcceptedByUserID(v *int64) *TeamInvitationUpdate {
	if v != nil {
		_u.SetAcceptedByUserID(*v)
	}
	return _u
}

// AddAcceptedByUserID adds value to the "accepted_by_user_id" field.
func (_u *TeamInvitationUpdate) AddAcceptedByUserID(v int64) *TeamInvitationUpdate {
	_u.mutation.AddAcceptedByUserID(v)
	return _u
}

// ClearAcceptedByUserID clears the value of the "accepted_by_user_id" field.
func (_u *TeamInvitationUpdate) ClearAcceptedByUserID() *TeamInvitationUpdate {
	_u.mutation.ClearAcceptedByUserID()
	return _u
}

// SetAcceptedAt sets the "accepted_at" field.
func (_u *TeamInvitationUpdate) SetAcceptedAt(v time.Time) *TeamInvitationUpdate {
	_u.mutation.SetAcceptedAt(v)
	return _u
}

// SetNillableAcceptedAt sets the "accepted_at" field if the given value is not nil.
func (_u *TeamInvitationUpdate) SetNillableAcceptedAt(v *time.Time) *TeamInvitationUpdate {
	if v != nil {
		_u.SetAcceptedAt(*v)
	}
	return _u
}

// ClearAcceptedAt clears the value of the "accepted_at" field.
func (_u *TeamInvitationUpdate) ClearAcceptedAt() *TeamInvitationUpdate {
	_u.mutation.ClearAcceptedAt()
	return _u
}

// SetTeam sets the "team" edge to the Team entity.
func (_u *TeamInvitationUpdate) SetTeam(v *Team) *TeamInvitationUpdate {
	return _u.SetTeamID(v.ID)
}

// Mutation returns the TeamInvitationMutation object of the builder.
func (_u *TeamInvitationUpdate) Mutation() *TeamInvitationMutation {
	return _u.mutation
}

// ClearTeam clears the "team" edge to the Team entity.
func (_u *TeamInvitationUpdate) ClearTeam() *TeamInvitationUpdate {
	_u.mutation.ClearTeam()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *TeamInvitationUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TeamInvitationUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *TeamInvitationUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TeamInvitationUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *TeamInvitationUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := teaminvitation.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TeamInvitationUpdate) check() error {
	if v, ok := _u.mutation.Email(); ok {
		if err := teaminvitation.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "TeamInvitation.email": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TokenHash(); ok {
		if err := teaminvitation.TokenHashValidator(v); err != nil {
			return &ValidationError{Name: "token_hash", err: fmt.Errorf(`ent: validator failed for field "TeamInvitation.token_hash": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := teaminvitation.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "TeamInvitation.status": %w`, err)}
		}
	}
	if _u.mutation.TeamCleared() && len(_u.mutation.TeamIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "TeamInvitation.team"`)
	}
	return nil
}

func (_u *TeamInvitationUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(teaminvitation.Table, teaminvitation.Columns, sqlgraph.NewFieldSpec(teaminvitation.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(teaminvitation.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.InviterUserID(); ok {
		_spec.SetField(teaminvitation.FieldInviterUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedInviterUserID(); ok {
		_spec.AddField(teaminvitation.FieldInviterUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Email(); ok {
		_spec.SetField(teaminvitation.FieldEmail, field.TypeString, value)
	}
	if value, ok := _u.mutation.TokenHash(); ok {
		_spec.SetField(teaminvitation.FieldTokenHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(teaminvitation.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(teaminvitation.FieldExpiresAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.AcceptedByUserID(); ok {
		_spec.SetField(teaminvitation.FieldAcceptedByUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAcceptedByUserID(); ok {
		_spec.AddField(teaminvitation.FieldAcceptedByUserID, field.TypeInt64, value)
	}
	if _u.mutation.AcceptedByUserIDCleared() {
		_spec.ClearField(teaminvitation.FieldAcceptedByUserID, field.TypeInt64)
	}
	if value, ok := _u.mutation.AcceptedAt(); ok {
		_spec.SetField(teaminvitation.FieldAcceptedAt, field.TypeTime, value)
	}
	if _u.mutation.AcceptedAtCleared() {
		_spec.ClearField(teaminvitation.FieldAcceptedAt, field.TypeTime)
	}
	if _u.mutation.TeamCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   teaminvitation.TeamTable,
			Columns: []string{teaminvitation.TeamColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(team.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TeamIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   teaminvitation.TeamTable,
			Columns: []string{teaminvitation.TeamColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(team.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{teaminvitation.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// TeamInvitationUpdateOne is the builder for updating a single TeamInvitation entity.
type TeamInvitationUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *TeamInvitationMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *TeamInvitationUpdateOne) SetUpdatedAt(v time.Time) *TeamInvitationUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetTeamID sets the "team_id" field.
func (_u *TeamInvitationUpdateOne) SetTeamID(v int64) *TeamInvitationUpdateOne {
	_u.mutation.SetTeamID(v)
	return _u
}

// SetNillableTeamID sets the "team_id" field if the given value is not nil.
func (_u *TeamInvitationUpdateOne) SetNillableTeamID(v *int64) *TeamInvitationUpdateOne {
	if v != nil {
		_u.SetTeamID(*v)
	}
	return _u
}

// SetInviterUserID sets the "inviter_user_id" field.
func (_u *TeamInvitationUpdateOne) SetInviterUserID(v int64) *TeamInvitationUpdateOne {
	_u.mutation.ResetInviterUserID()
	_u.mutation.SetInviterUserID(v)
	return _u
}

// SetNillableInviterUserID sets the "inviter_user_id" field if the given value is not nil.
func (_u *TeamInvitationUpdateOne) SetNillableInviterUserID(v *int64) *TeamInvitationUpdateOne {
	if v != nil {
		_u.SetInviterUserID(*v)
	}
	return _u
}

// AddInviterUserID adds value to the "inviter_user_id" field.
func (_u *TeamInvitationUpdateOne) AddInviterUserID(v int64) *TeamInvitationUpdateOne {
	_u.mutation.AddInviterUserID(v)
	return _u
}

// SetEmail sets the "email" field.
func (_u *TeamInvitationUpdateOne) SetEmail(v string) *TeamInvitationUpdateOne {
	_u.mutation.SetEmail(v)
	return _u
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (_u *TeamInvitationUpdateOne) SetNillableEmail(v *string) *TeamInvitationUpdateOne {
	if v != nil {
		_u.SetEmail(*v)
	}
	return _u
}

// SetTokenHash sets the "token_hash" field.
func (_u *TeamInvitationUpdateOne) SetTokenHash(v string) *TeamInvitationUpdateOne {
	_u.mutation.SetTokenHash(v)
	return _u
}

// SetNillableTokenHash sets the "token_hash" field if the given value is not nil.
func (_u *TeamInvitationUpdateOne) SetNillableTokenHash(v *string) *TeamInvitationUpdateOne {
	if v != nil {
		_u.SetTokenHash(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *TeamInvitationUpdateOne) SetStatus(v string) *TeamInvitationUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *TeamInvitationUpdateOne) SetNillableStatus(v *string) *TeamInvitationUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *TeamInvitationUpdateOne) SetExpiresAt(v time.Time) *TeamInvitationUpdateOne {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *TeamInvitationUpdateOne) SetNillableExpiresAt(v *time.Time) *TeamInvitationUpdateOne {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// SetAcceptedByUserID sets the "accepted_by_user_id" field.
func (_u *TeamInvitationUpdateOne) SetAcceptedByUserID(v int64) *TeamInvitationUpdateOne {
	_u.mutation.ResetAcceptedByUserID()
	_u.mutation.SetAcceptedByUserID(v)
	return _u
}

// SetNillableAcceptedByUserID sets the "accepted_by_user_id" field if the given value is not nil.
func (_u *TeamInvitationUpdateOne) SetNillableAcceptedByUserID(v *int64) *TeamInvitationUpdateOne {
	if v != nil {
		_u.SetAcceptedByUserID(*v)
	}
	return _u
}

// AddAcceptedByUserID adds value to the "accepted_by_user_id" field.
func (_u *TeamInvitationUpdateOne) AddAcceptedByUserID(v int64) *TeamInvitationUpdateOne {
	_u.mutation.AddAcceptedByUserID(v)
	return _u
}

// ClearAcceptedByUserID clears the value of the "accepted_by_user_id" field.
func (_u *TeamInvitationUpdateOne) ClearAcceptedByUserID() *TeamInvitationUpdateOne {
	_u.mutation.ClearAcceptedByUserID()
	return _u
}

// SetAcceptedAt sets the "accepted_at" field.
func (_u *TeamInvitationUpdateOne) SetAcceptedAt(v time.Time) *TeamInvitationUpdateOne {
	_u.mutation.SetAcceptedAt(v)
	return _u
}

// SetNillableAcceptedAt sets the "accepted_at" field if the given value is not nil.
func (_u *TeamInvitationUpdateOne) SetNillableAcceptedAt(v *time.Time) *TeamInvitationUpdateOne {
	if v != nil {
		_u.SetAcceptedAt(*v)
	}
	return _u
}

// ClearAcceptedAt clears the value of the "accepted_at" field.
func (_u *TeamInvitationUpdateOne) ClearAcceptedAt() *TeamInvitationUpdateOne {
	_u.mutation.ClearAcceptedAt()
	return _u
}

// SetTeam sets the "team" edge to the Team entity.
func (_u *TeamInvitationUpdateOne) SetTeam(v *Team) *TeamInvitationUpdateOne {
	return _u.SetTeamID(v.ID)
}

// Mutation returns the TeamInvitationMutation object of the builder.
func (_u *TeamInvitationUpdateOne) Mutation() *TeamInvitationMutation {
	return _u.mutation
}

// ClearTeam clears the "team" edge to the Team entity.
func (_u *TeamInvitationUpdateOne) ClearTeam() *TeamInvitationUpdateOne {
	_u.mutation.ClearTeam()
	return _u
}

// Where appends a list predicates to the TeamInvitationUpdate builder.
func (_u *TeamInvitationUpdateOne) Where(ps ...predicate.TeamInvitation) *TeamInvitationUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *TeamInvitationUpdateOne) Select(field string, fields ...string) *TeamInvitationUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated TeamInvitation entity.
func (_u *TeamInvitationUpdateOne) Save(ctx context.Context) (*TeamInvitation, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TeamInvitationUpdateOne) SaveX(ctx context.Context) *TeamInvitation {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *TeamInvitationUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TeamInvitationUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *TeamInvitationUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := teaminvitation.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TeamInvitationUpdateOne) check() error {
	if v, ok := _u.mutation.Email(); ok {
		if err := teaminvitation.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "TeamInvitation.email": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TokenHash(); ok {
		if err := teaminvitation.TokenHashValidator(v); err != nil {
			return &ValidationError{Name: "token_hash", err: fmt.Errorf(`ent: validator failed for field "TeamInvitation.token_hash": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := teaminvitation.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "TeamInvitation.status": %w`, err)}
		}
	}
	if _u.mutation.TeamCleared() && len(_u.mutation.TeamIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "TeamInvitation.team"`)
	}
	return nil
}

func (_u *TeamInvitationUpdateOne) sqlSave(ctx context.Context) (_node *TeamInvitation, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(teaminvitation.Table, teaminvitation.Columns, sqlgraph.NewFieldSpec(teaminvitation.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "TeamInvitation.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, teaminvitation.FieldID)
		for _, f := range fields {
			if !teaminvitation.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != teaminvitation.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(teaminvitation.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.InviterUserID(); ok {
		_spec.SetField(teaminvitation.FieldInviterUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedInviterUserID(); ok {
		_spec.AddField(teaminvitation.FieldInviterUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Email(); ok {
		_spec.SetField(teaminvitation.FieldEmail, field.TypeString, value)
	}
	if value, ok := _u.mutation.TokenHash(); ok {
		_spec.SetField(teaminvitation.FieldTokenHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(teaminvitation.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(teaminvitation.FieldExpiresAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.AcceptedByUserID(); ok {
		_spec.SetField(teaminvitation.FieldAcceptedByUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAcceptedByUserID(); ok {
		_spec.AddField(teaminvitation.FieldAcceptedByUserID, field.TypeInt64, value)
	}
	if _u.mutation.AcceptedByUserIDCleared() {
		_spec.ClearField(teaminvitation.FieldAcceptedByUserID, field.TypeInt64)
	}
	if value, ok := _u.mutation.AcceptedAt(); ok {
		_spec.SetField(teaminvitation.FieldAcceptedAt, field.TypeTime, value)
	}
	if _u.mutation.AcceptedAtCleared() {
		_spec.ClearField(teaminvitation.FieldAcceptedAt, field.TypeTime)
	}
	if _u.mutation.TeamCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   teaminvitation.TeamTable,
			Columns: []string{teaminvitation.TeamColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(team.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TeamIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   teaminvitation.TeamTable,
			Columns: []string{teaminvitation.TeamColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(team.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &TeamInvitation{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{teaminvitation.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
