// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/LuckyKuang/sub2api-plus/ent/apikey"
	"github.com/LuckyKuang/sub2api-plus/ent/predicate"
	"github.com/LuckyKuang/sub2api-plus/ent/team"
	"github.com/LuckyKuang/sub2api-plus/ent/teaminvitation"
	"github.com/LuckyKuang/sub2api-plus/ent/teammembership"
	"github.com/LuckyKuang/sub2api-plus/ent/teamownershiptransfer"
	"github.com/LuckyKuang/sub2api-plus/ent/usagelog"
)

// TeamUpdate is the builder for updating Team entities.
type TeamUpdate struct {
	config
	hooks    []Hook
	mutation *TeamMutation
}

// Where appends a list predicates to the TeamUpdate builder.
func (_u *TeamUpdate) Where(ps ...predicate.Team) *TeamUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *TeamUpdate) SetUpdatedAt(v time.Time) *TeamUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *TeamUpdate) SetDeletedAt(v time.Time) *TeamUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *TeamUpdate) SetNillableDeletedAt(v *time.Time) *TeamUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *TeamUpdate) ClearDeletedAt() *TeamUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetName sets the "name" field.
func (_u *TeamUpdate) SetName(v string) *TeamUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *TeamUpdate) SetNillableName(v *string) *TeamUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *TeamUpdate) SetStatus(v string) *TeamUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *TeamUpdate) SetNillableStatus(v *string) *TeamUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetMemberLimit sets the "member_limit" field.
func (_u *TeamUpdate) SetMemberLimit(v int) *TeamUpdate {
	_u.mutation.ResetMemberLimit()
	_u.mutation.SetMemberLimit(v)
	return _u
}

// SetNillableMemberLimit sets the "member_limit" field if the given value is not nil.
func (_u *TeamUpdate) SetNillableMemberLimit(v *int) *TeamUpdate {
	if v != nil {
		_u.SetMemberLimit(*v)
	}
	return _u
}

// AddMemberLimit adds value to the "member_limit" field.
func (_u *TeamUpdate) AddMemberLimit(v int) *TeamUpdate {
	_u.mutation.AddMemberLimit(v)
	return _u
}

// SetDefaultDailyLimitUsd sets the "default_daily_limit_usd" field.
func (_u *TeamUpdate) SetDefaultDailyLimitUsd(v float64) *TeamUpdate {
	_u.mutation.ResetDefaultDailyLimitUsd()
	_u.mutation.SetDefaultDailyLimitUsd(v)
	return _u
}

// SetNillableDefaultDailyLimitUsd sets the "default_daily_limit_usd" field if the given value is not nil.
func (_u *TeamUpdate) SetNillableDefaultDailyLimitUsd(v *float64) *TeamUpdate {
	if v != nil {
		_u.SetDefaultDailyLimitUsd(*v)
	}
	return _u
}

// AddDefaultDailyLimitUsd adds value to the "default_daily_limit_usd" field.
func (_u *TeamUpdate) AddDefaultDailyLimitUsd(v float64) *TeamUpdate {
	_u.mutation.AddDefaultDailyLimitUsd(v)
	return _u
}

// SetDefaultWeeklyLimitUsd sets the "default_weekly_limit_usd" field.
func (_u *TeamUpdate) SetDefaultWeeklyLimitUsd(v float64) *TeamUpdate {
	_u.mutation.ResetDefaultWeeklyLimitUsd()
	_u.mutation.SetDefaultWeeklyLimitUsd(v)
	return _u
}

// SetNillableDefaultWeeklyLimitUsd sets the "default_weekly_limit_usd" field if the given value is not nil.
func (_u *TeamUpdate) SetNillableDefaultWeeklyLimitUsd(v *float64) *TeamUpdate {
	if v != nil {
		_u.SetDefaultWeeklyLimitUsd(*v)
	}
	return _u
}

// AddDefaultWeeklyLimitUsd adds value to the "default_weekly_limit_usd" field.
func (_u *TeamUpdate) AddDefaultWeeklyLimitUsd(v float64) *TeamUpdate {
	_u.mutation.AddDefaultWeeklyLimitUsd(v)
	return _u
}

// SetDefaultMonthlyLimitUsd sets the "default_monthly_limit_usd" field.
func (_u *TeamUpdate) SetDefaultMonthlyLimitUsd(v float64) *TeamUpdate {
	_u.mutation.ResetDefaultMonthlyLimitUsd()
	_u.mutation.SetDefaultMonthlyLimitUsd(v)
	return _u
}

// SetNillableDefaultMonthlyLimitUsd sets the "default_monthly_limit_usd" field if the given value is not nil.
func (_u *TeamUpdate) SetNillableDefaultMonthlyLimitUsd(v *float64) *TeamUpdate {
	if v != nil {
		_u.SetDefaultMonthlyLimitUsd(*v)
	}
	return _u
}

// AddDefaultMonthlyLimitUsd adds value to the "default_monthly_limit_usd" field.
func (_u *TeamUpdate) AddDefaultMonthlyLimitUsd(v float64) *TeamUpdate {
	_u.mutation.AddDefaultMonthlyLimitUsd(v)
	return _u
}

// AddMembershipIDs adds the "memberships" edge to the TeamMembership entity by IDs.
func (_u *TeamUpdate) AddMembershipIDs(ids ...int64) *TeamUpdate {
	_u.mutation.AddMembershipIDs(ids...)
	return _u
}

// AddMemberships adds the "memberships" edges to the TeamMembership entity.
func (_u *TeamUpdate) AddMemberships(v ...*TeamMembership) *TeamUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddMembershipIDs(ids...)
}

// AddInvitationIDs adds the "invitations" edge to the TeamInvitation entity by IDs.
func (_u *TeamUpdate) AddInvitationIDs(ids ...int64) *TeamUpdate {
	_u.mutation.AddInvitationIDs(ids...)
	return _u
}

// AddInvitations adds the "invitations" edges to the TeamInvitation entity.
func (_u *TeamUpdate) AddInvitations(v ...*TeamInvitation) *TeamUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddInvitationIDs(ids...)
}

// AddOwnershipTransferIDs adds the "ownership_transfers" edge to the TeamOwnershipTransfer entity by IDs.
func (_u *TeamUpdate) AddOwnershipTransferIDs(ids ...int64) *TeamUpdate {
	_u.mutation.AddOwnershipTransferIDs(ids...)
	return _u
}

// AddOwnershipTransfers adds the "ownership_transfers" edges to the TeamOwnershipTransfer entity.
func (_u *TeamUpdate) AddOwnershipTransfers(v ...*TeamOwnershipTransfer) *TeamUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddOwnershipTransferIDs(ids...)
}

// AddAPIKeyIDs adds the "api_keys" edge to the APIKey entity by IDs.
func (_u *TeamUpdate) AddAPIKeyIDs(ids ...int64) *TeamUpdate {
	_u.mutation.AddAPIKeyIDs(ids...)
	return _u
}

// AddAPIKeys adds the "api_keys" edges to the APIKey entity.
func (_u *TeamUpdate) AddAPIKeys(v ...*APIKey) *TeamUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAPIKeyIDs(ids...)
}

// AddUsageLogIDs adds the "usage_logs" edge to the UsageLog entity by IDs.
func (_u *TeamUpdate) AddUsageLogIDs(ids ...int64) *TeamUpdate {
	_u.mutation.AddUsageLogIDs(ids...)
	return _u
}

// AddUsageLogs adds the "usage_logs" edges to the UsageLog entity.
func (_u *TeamUpdate) AddUsageLogs(v ...*UsageLog) *TeamUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddUsageLogIDs(ids...)
}

// Mutation returns the TeamMutation object of the builder.
func (_u *TeamUpdate) Mutation() *TeamMutation {
	return _u.mutation
}

// ClearMemberships clears all "memberships" edges to the TeamMembership entity.
func (_u *TeamUpdate) ClearMemberships() *TeamUpdate {
	_u.mutation.ClearMemberships()
	return _u
}

// RemoveMembershipIDs removes the "memberships" edge to TeamMembership entities by IDs.
func (_u *TeamUpdate) RemoveMembershipIDs(ids ...int64) *TeamUpdate {
	_u.mutation.RemoveMembershipIDs(ids...)
	return _u
}

// RemoveMemberships removes "memberships" edges to TeamMembership entities.
func (_u *TeamUpdate) RemoveMemberships(v ...*TeamMembership) *TeamUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveMembershipIDs(ids...)
}

// ClearInvitations clears all "invitations" edges to the TeamInvitation entity.
func (_u *TeamUpdate) ClearInvitations() *TeamUpdate {
	_u.mutation.ClearInvitations()
	return _u
}

// RemoveInvitationIDs removes the "invitations" edge to TeamInvitation entities by IDs.
func (_u *TeamUpdate) RemoveInvitationIDs(ids ...int64) *TeamUpdate {
	_u.mutation.RemoveInvitationIDs(ids...)
	return _u
}

// RemoveInvitations removes "invitations" edges to TeamInvitation entities.
func (_u *TeamUpdate) RemoveInvitations(v ...*TeamInvitation) *TeamUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveInvitationIDs(ids...)
}

// ClearOwnershipTransfers clears all "ownership_transfers" edges to the TeamOwnershipTransfer entity.
func (_u *TeamUpdate) ClearOwnershipTransfers() *TeamUpdate {
	_u.mutation.ClearOwnershipTransfers()
	return _u
}

// RemoveOwnershipTransferIDs removes the "ownership_transfers" edge to TeamOwnershipTransfer entities by IDs.
func (_u *TeamUpdate) RemoveOwnershipTransferIDs(ids ...int64) *TeamUpdate {
	_u.mutation.RemoveOwnershipTransferIDs(ids...)
	return _u
}

// RemoveOwnershipTransfers removes "ownership_transfers" edges to TeamOwnershipTransfer entities.
func (_u *TeamUpdate) RemoveOwnershipTransfers(v ...*TeamOwnershipTransfer) *TeamUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveOwnershipTransferIDs(ids...)
}

// ClearAPIKeys clears all "api_keys" edges to the APIKey entity.
func (_u *TeamUpdate) ClearAPIKeys() *TeamUpdate {
	_u.mutation.ClearAPIKeys()
	return _u
}

// RemoveAPIKeyIDs removes the "api_keys" edge to APIKey entities by IDs.
func (_u *TeamUpdate) RemoveAPIKeyIDs(ids ...int64) *TeamUpdate {
	_u.mutation.RemoveAPIKeyIDs(ids...)
	return _u
}

// RemoveAPIKeys removes "api_keys" edges to APIKey entities.
func (_u *TeamUpdate) RemoveAPIKeys(v ...*APIKey) *TeamUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAPIKeyIDs(ids...)
}

// ClearUsageLogs clears all "usage_logs" edges to the UsageLog entity.
func (_u *TeamUpdate) ClearUsageLogs() *TeamUpdate {
	_u.mutation.ClearUsageLogs()
	return _u
}

// RemoveUsageLogIDs removes the "usage_logs" edge to UsageLog entities by IDs.
func (_u *TeamUpdate) RemoveUsageLogIDs(ids ...int64) *TeamUpdate {
	_u.mutation.RemoveUsageLogIDs(ids...)
	return _u
}

// RemoveUsageLogs removes "usage_logs" edges to UsageLog entities.
func (_u *TeamUpdate) RemoveUsageLogs(v ...*UsageLog) *TeamUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveUsageLogIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *TeamUpdate) Save(ctx context.Context) (int, error) {
	if err := _u.defaults(); err != nil {
		return 0, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TeamUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *TeamUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TeamUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *TeamUpdate) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if team.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized team.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := team.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *TeamUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := team.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Team.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := team.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Team.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.MemberLimit(); ok {
		if err := team.MemberLimitValidator(v); err != nil {
			return &ValidationError{Name: "member_limit", err: fmt.Errorf(`ent: validator failed for field "Team.member_limit": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DefaultDailyLimitUsd(); ok {
		if err := team.DefaultDailyLimitUsdValidator(v); err != nil {
			return &ValidationError{Name: "default_daily_limit_usd", err: fmt.Errorf(`ent: validator failed for field "Team.default_daily_limit_usd": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DefaultWeeklyLimitUsd(); ok {
		if err := team.DefaultWeeklyLimitUsdValidator(v); err != nil {
			return &ValidationError{Name: "default_weekly_limit_usd", err: fmt.Errorf(`ent: validator failed for field "Team.default_weekly_limit_usd": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DefaultMonthlyLimitUsd(); ok {
		if err := team.DefaultMonthlyLimitUsdValidator(v); err != nil {
			return &ValidationError{Name: "default_monthly_limit_usd", err: fmt.Errorf(`ent: validator failed for field "Team.default_monthly_limit_usd": %w`, err)}
		}
	}
	return nil
}

func (_u *TeamUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(team.Table, team.Columns, sqlgraph.NewFieldSpec(team.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(team.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(team.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(team.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(team.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(team.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.MemberLimit(); ok {
		_spec.SetField(team.FieldMemberLimit, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMemberLimit(); ok {
		_spec.AddField(team.FieldMemberLimit, field.TypeInt, value)
	}
	if value, ok := _u.mutation.DefaultDailyLimitUsd(); ok {
		_spec.SetField(team.FieldDefaultDailyLimitUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedDefaultDailyLimitUsd(); ok {
		_spec.AddField(team.FieldDefaultDailyLimitUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.DefaultWeeklyLimitUsd(); ok {
		_spec.SetField(team.FieldDefaultWeeklyLimitUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedDefaultWeeklyLimitUsd(); ok {
		_spec.AddField(team.FieldDefaultWeeklyLimitUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.DefaultMonthlyLimitUsd(); ok {
		_spec.SetField(team.FieldDefaultMonthlyLimitUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedDefaultMonthlyLimitUsd(); ok {
		_spec.AddField(team.FieldDefaultMonthlyLimitUsd, field.TypeFloat64, value)
	}
	if _u.mutation.MembershipsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   team.MembershipsTable,
			Columns: []string{team.MembershipsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(teammembership.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedMembershipsIDs(); len(nodes) > 0 && !_u.mutation.MembershipsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   team.MembershipsTable,
			Columns: []string{team.MembershipsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(teammembership.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MembershipsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   team.MembershipsTable,
			Columns: []string{team.MembershipsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(teammembership.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.InvitationsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   team.InvitationsTable,
			Columns: []string{team.InvitationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(teaminvitation.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedInvitationsIDs(); len(nodes) > 0 && !_u.mutation.InvitationsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   team.InvitationsTable,
			Columns: []string{team.InvitationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(teaminvitation.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.InvitationsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   team.InvitationsTable,
			Columns: []string{team.InvitationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(teaminvitation.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.OwnershipTransfersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   team.OwnershipTransfersTable,
			Columns: []string{team.OwnershipTransfersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(teamownershiptransfer.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedOwnershipTransfersIDs(); len(nodes) > 0 && !_u.mutation.OwnershipTransfersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   team.OwnershipTransfersTable,
			Columns: []string{team.OwnershipTransfersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(teamownershiptransfer.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OwnershipTransfersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   team.OwnershipTransfersTable,
			Columns: []string{team.OwnershipTransfersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(teamownershiptransfer.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.APIKeysCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   team.APIKeysTable,
			Columns: []string{team.APIKeysColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apikey.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAPIKeysIDs(); len(nodes) > 0 && !_u.mutation.APIKeysCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   team.APIKeysTable,
			Columns: []string{team.APIKeysColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apikey.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.APIKeysIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   team.APIKeysTable,
			Columns: []string{team.APIKeysColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apikey.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UsageLogsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   team.UsageLogsTable,
			Columns: []string{team.UsageLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usagelog.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedUsageLogsIDs(); len(nodes) > 0 && !_u.mutation.UsageLogsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   team.UsageLogsTable,
			Columns: []string{team.UsageLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usagelog.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UsageLogsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   team.UsageLogsTable,
			Columns: []string{team.UsageLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usagelog.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{team.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// TeamUpdateOne is the builder for updating a single Team entity.
type TeamUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *TeamMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *TeamUpdateOne) SetUpdatedAt(v time.Time) *TeamUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *TeamUpdateOne) SetDeletedAt(v time.Time) *TeamUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *TeamUpdateOne) SetNillableDeletedAt(v *time.Time) *TeamUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *TeamUpdateOne) ClearDeletedAt() *TeamUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetName sets the "name" field.
func (_u *TeamUpdateOne) SetName(v string) *TeamUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *TeamUpdateOne) SetNillableName(v *string) *TeamUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *TeamUpdateOne) SetStatus(v string) *TeamUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *TeamUpdateOne) SetNillableStatus(v *string) *TeamUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetMemberLimit sets the "member_limit" field.
func (_u *TeamUpdateOne) SetMemberLimit(v int) *TeamUpdateOne {
	_u.mutation.ResetMemberLimit()
	_u.mutation.SetMemberLimit(v)
	return _u
}

// SetNillableMemberLimit sets the "member_limit" field if the given value is not nil.
func (_u *TeamUpdateOne) SetNillableMemberLimit(v *int) *TeamUpdateOne {
	if v != nil {
		_u.SetMemberLimit(*v)
	}
	return _u
}

// AddMemberLimit adds value to the "member_limit" field.
func (_u *TeamUpdateOne) AddMemberLimit(v int) *TeamUpdateOne {
	_u.mutation.AddMemberLimit(v)
	return _u
}

// SetDefaultDailyLimitUsd sets the "default_daily_limit_usd" field.
func (_u *TeamUpdateOne) SetDefaultDailyLimitUsd(v float64) *TeamUpdateOne {
	_u.mutation.ResetDefaultDailyLimitUsd()
	_u.mutation.SetDefaultDailyLimitUsd(v)
	return _u
}

// SetNillableDefaultDailyLimitUsd sets the "default_daily_limit_usd" field if the given value is not nil.
func (_u *TeamUpdateOne) SetNillableDefaultDailyLimitUsd(v *float64) *TeamUpdateOne {
	if v != nil {
		_u.SetDefaultDailyLimitUsd(*v)
	}
	return _u
}

// AddDefaultDailyLimitUsd adds value to the "default_daily_limit_usd" field.
func (_u *TeamUpdateOne) AddDefaultDailyLimitUsd(v float64) *TeamUpdateOne {
	_u.mutation.AddDefaultDailyLimitUsd(v)
	return _u
}

// SetDefaultWeeklyLimitUsd sets the "default_weekly_limit_usd" field.
func (_u *TeamUpdateOne) SetDefaultWeeklyLimitUsd(v float64) *TeamUpdateOne {
	_u.mutation.ResetDefaultWeeklyLimitUsd()
	_u.mutation.SetDefaultWeeklyLimitUsd(v)
	return _u
}

// SetNillableDefaultWeeklyLimitUsd sets the "default_weekly_limit_usd" field if the given value is not nil.
func (_u *TeamUpdateOne) SetNillableDefaultWeeklyLimitUsd(v *float64) *TeamUpdateOne {
	if v != nil {
		_u.SetDefaultWeeklyLimitUsd(*v)
	}
	return _u
}

// AddDefaultWeeklyLimitUsd adds value to the "default_weekly_limit_usd" field.
func (_u *TeamUpdateOne) AddDefaultWeeklyLimitUsd(v float64) *TeamUpdateOne {
	_u.mutation.AddDefaultWeeklyLimitUsd(v)
	return _u
}

// SetDefaultMonthlyLimitUsd sets the "default_monthly_limit_usd" field.
func (_u *TeamUpdateOne) SetDefaultMonthlyLimitUsd(v float64) *TeamUpdateOne {
	_u.mutation.ResetDefaultMonthlyLimitUsd()
	_u.mutation.SetDefaultMonthlyLimitUsd(v)
	return _u
}

// SetNillableDefaultMonthlyLimitUsd sets the "default_monthly_limit_usd" field if the given value is not nil.
func (_u *TeamUpdateOne) SetNillableDefaultMonthlyLimitUsd(v *float64) *TeamUpdateOne {
	if v != nil {
		_u.SetDefaultMonthlyLimitUsd(*v)
	}
	return _u
}

// AddDefaultMonthlyLimitUsd adds value to the "default_monthly_limit_usd" field.
func (_u *TeamUpdateOne) AddDefaultMonthlyLimitUsd(v float64) *TeamUpdateOne {
	_u.mutation.AddDefaultMonthlyLimitUsd(v)
	return _u
}

// AddMembershipIDs adds the "memberships" edge to the TeamMembership entity by IDs.
func (_u *TeamUpdateOne) AddMembershipIDs(ids ...int64) *TeamUpdateOne {
	_u.mutation.AddMembershipIDs(ids...)
	return _u
}

// AddMemberships adds the "memberships" edges to the TeamMembership entity.
func (_u *TeamUpdateOne) AddMemberships(v ...*TeamMembership) *TeamUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddMembershipIDs(ids...)
}

// AddInvitationIDs adds the "invitations" edge to the TeamInvitation entity by IDs.
func (_u *TeamUpdateOne) AddInvitationIDs(ids ...int64) *TeamUpdateOne {
	_u.mutation.AddInvitationIDs(ids...)
	return _u
}

// AddInvitations adds the "invitations" edges to the TeamInvitation entity.
func (_u *TeamUpdateOne) AddInvitations(v ...*TeamInvitation) *TeamUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddInvitationIDs(ids...)
}

// AddOwnershipTransferIDs adds the "ownership_transfers" edge to the TeamOwnershipTransfer entity by IDs.
func (_u *TeamUpdateOne) AddOwnershipTransferIDs(ids ...int64) *TeamUpdateOne {
	_u.mutation.AddOwnershipTransferIDs(ids...)
	return _u
}

// AddOwnershipTransfers adds the "ownership_transfers" edges to the TeamOwnershipTransfer entity.
func (_u *TeamUpdateOne) AddOwnershipTransfers(v ...*TeamOwnershipTransfer) *TeamUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddOwnershipTransferIDs(ids...)
}

// AddAPIKeyIDs adds the "api_keys" edge to the APIKey entity by IDs.
func (_u *TeamUpdateOne) AddAPIKeyIDs(ids ...int64) *TeamUpdateOne {
	_u.mutation.AddAPIKeyIDs(ids...)
	return _u
}

// AddAPIKeys adds the "api_keys" edges to the APIKey entity.
func (_u *TeamUpdateOne) AddAPIKeys(v ...*APIKey) *TeamUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAPIKeyIDs(ids...)
}

// AddUsageLogIDs adds the "usage_logs" edge to the UsageLog entity by IDs.
func (_u *TeamUpdateOne) AddUsageLogIDs(ids ...int64) *TeamUpdateOne {
	_u.mutation.AddUsageLogIDs(ids...)
	return _u
}

// AddUsageLogs adds the "usage_logs" edges to the UsageLog entity.
func (_u *TeamUpdateOne) AddUsageLogs(v ...*UsageLog) *TeamUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddUsageLogIDs(ids...)
}

// Mutation returns the TeamMutation object of the builder.
func (_u *TeamUpdateOne) Mutation() *TeamMutation {
	return _u.mutation
}

// ClearMemberships clears all "memberships" edges to the TeamMembership entity.
func (_u *TeamUpdateOne) ClearMemberships() *TeamUpdateOne {
	_u.mutation.ClearMemberships()
	return _u
}

// RemoveMembershipIDs removes the "memberships" edge to TeamMembership entities by IDs.
func (_u *TeamUpdateOne) RemoveMembershipIDs(ids ...int64) *TeamUpdateOne {
	_u.mutation.RemoveMembershipIDs(ids...)
	return _u
}

// RemoveMemberships removes "memberships" edges to TeamMembership entities.
func (_u *TeamUpdateOne) RemoveMemberships(v ...*TeamMembership) *TeamUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveMembershipIDs(ids...)
}

// ClearInvitations clears all "invitations" edges to the TeamInvitation entity.
func (_u *TeamUpdateOne) ClearInvitations() *TeamUpdateOne {
	_u.mutation.ClearInvitations()
	return _u
}

// RemoveInvitationIDs removes the "invitations" edge to TeamInvitation entities by IDs.
func (_u *TeamUpdateOne) RemoveInvitationIDs(ids ...int64) *TeamUpdateOne {
	_u.mutation.RemoveInvitationIDs(ids...)
	return _u
}

// RemoveInvitations removes "invitations" edges to TeamInvitation entities.
func (_u *TeamUpdateOne) RemoveInvitations(v ...*TeamInvitation) *TeamUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveInvitationIDs(ids...)
}

// ClearOwnershipTransfers clears all "ownership_transfers" edges to the TeamOwnershipTransfer entity.
func (_u *TeamUpdateOne) ClearOwnershipTransfers() *TeamUpdateOne {
	_u.mutation.ClearOwnershipTransfers()
	return _u
}

// RemoveOwnershipTransferIDs removes the "ownership_transfers" edge to TeamOwnershipTransfer entities by IDs.
func (_u *TeamUpdateOne) RemoveOwnershipTransferIDs(ids ...int64) *TeamUpdateOne {
	_u.mutation.RemoveOwnershipTransferIDs(ids...)
	return _u
}

// RemoveOwnershipTransfers removes "ownership_transfers" edges to TeamOwnershipTransfer entities.
func (_u *TeamUpdateOne) RemoveOwnershipTransfers(v ...*TeamOwnershipTransfer) *TeamUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveOwnershipTransferIDs(ids...)
}

// ClearAPIKeys clears all "api_keys" edges to the APIKey entity.
func (_u *TeamUpdateOne) ClearAPIKeys() *TeamUpdateOne {
	_u.mutation.ClearAPIKeys()
	return _u
}

// RemoveAPIKeyIDs removes the "api_keys" edge to APIKey entities by IDs.
func (_u *TeamUpdateOne) RemoveAPIKeyIDs(ids ...int64) *TeamUpdateOne {
	_u.mutation.RemoveAPIKeyIDs(ids...)
	return _u
}

// RemoveAPIKeys removes "api_keys" edges to APIKey entities.
func (_u *TeamUpdateOne) RemoveAPIKeys(v ...*APIKey) *TeamUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAPIKeyIDs(ids...)
}

// ClearUsageLogs clears all "usage_logs" edges to the UsageLog entity.
func (_u *TeamUpdateOne) ClearUsageLogs() *TeamUpdateOne {
	_u.mutation.ClearUsageLogs()
	return _u
}

// RemoveUsageLogIDs removes the "usage_logs" edge to UsageLog entities by IDs.
func (_u *TeamUpdateOne) RemoveUsageLogIDs(ids ...int64) *TeamUpdateOne {
	_u.mutation.RemoveUsageLogIDs(ids...)
	return _u
}

// RemoveUsageLogs removes "usage_logs" edges to UsageLog entities.
func (_u *TeamUpdateOne) RemoveUsageLogs(v ...*UsageLog) *TeamUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveUsageLogIDs(ids...)
}

// Where appends a list predicates to the TeamUpdate builder.
func (_u *TeamUpdateOne) Where(ps ...predicate.Team) *TeamUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *TeamUpdateOne) Select(field string, fields ...string) *TeamUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Team entity.
func (_u *TeamUpdateOne) Save(ctx context.Context) (*Team, error) {
	if err := _u.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TeamUpdateOne) SaveX(ctx context.Context) *Team {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *TeamUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TeamUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *TeamUpdateOne) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if team.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized team.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := team.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *TeamUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := team.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Team.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := team.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Team.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.MemberLimit(); ok {
		if err := team.MemberLimitValidator(v); err != nil {
			return &ValidationError{Name: "member_limit", err: fmt.Errorf(`ent: validator failed for field "Team.member_limit": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DefaultDailyLimitUsd(); ok {
		if err := team.DefaultDailyLimitUsdValidator(v); err != nil {
			return &ValidationError{Name: "default_daily_limit_usd", err: fmt.Errorf(`ent: validator failed for field "Team.default_daily_limit_usd": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DefaultWeeklyLimitUsd(); ok {
		if err := team.DefaultWeeklyLimitUsdValidator(v); err != nil {
			return &ValidationError{Name: "default_weekly_limit_usd", err: fmt.Errorf(`ent: validator failed for field "Team.default_weekly_limit_usd": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DefaultMonthlyLimitUsd(); ok {
		if err := team.DefaultMonthlyLimitUsdValidator(v); err != nil {
			return &ValidationError{Name: "default_monthly_limit_usd", err: fmt.Errorf(`ent: validator failed for field "Team.default_monthly_limit_usd": %w`, err)}
		}
	}
	return nil
}

func (_u *TeamUpdateOne) sqlSave(ctx context.Context) (_node *Team, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(team.Table, team.Columns, sqlgraph.NewFieldSpec(team.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Team.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, team.FieldID)
		for _, f := range fields {
			if !team.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != team.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(team.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(team.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(team.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(team.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(team.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.MemberLimit(); ok {
		_spec.SetField(team.FieldMemberLimit, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMemberLimit(); ok {
		_spec.AddField(team.FieldMemberLimit, field.TypeInt, value)
	}
	if value, ok := _u.mutation.DefaultDailyLimitUsd(); ok {
		_spec.SetField(team.FieldDefaultDailyLimitUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedDefaultDailyLimitUsd(); ok {
		_spec.AddField(team.FieldDefaultDailyLimitUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.DefaultWeeklyLimitUsd(); ok {
		_spec.SetField(team.FieldDefaultWeeklyLimitUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedDefaultWeeklyLimitUsd(); ok {
		_spec.AddField(team.FieldDefaultWeeklyLimitUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.DefaultMonthlyLimitUsd(); ok {
		_spec.SetField(team.FieldDefaultMonthlyLimitUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedDefaultMonthlyLimitUsd(); ok {
		_spec.AddField(team.FieldDefaultMonthlyLimitUsd, field.TypeFloat64, value)
	}
	if _u.mutation.MembershipsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   team.MembershipsTable,
			Columns: []string{team.MembershipsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(teammembership.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedMembershipsIDs(); len(nodes) > 0 && !_u.mutation.MembershipsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   team.MembershipsTable,
			Columns: []string{team.MembershipsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(teammembership.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MembershipsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   team.MembershipsTable,
			Columns: []string{team.MembershipsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(teammembership.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.InvitationsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   team.InvitationsTable,
			Columns: []string{team.InvitationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(teaminvitation.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedInvitationsIDs(); len(nodes) > 0 && !_u.mutation.InvitationsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   team.InvitationsTable,
			Columns: []string{team.InvitationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(teaminvitation.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.InvitationsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   team.InvitationsTable,
			Columns: []string{team.InvitationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(teaminvitation.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.OwnershipTransfersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   team.OwnershipTransfersTable,
			Columns: []string{team.OwnershipTransfersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(teamownershiptransfer.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedOwnershipTransfersIDs(); len(nodes) > 0 && !_u.mutation.OwnershipTransfersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   team.OwnershipTransfersTable,
			Columns: []string{team.OwnershipTransfersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(teamownershiptransfer.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OwnershipTransfersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   team.OwnershipTransfersTable,
			Columns: []string{team.OwnershipTransfersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(teamownershiptransfer.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.APIKeysCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   team.APIKeysTable,
			Columns: []string{team.APIKeysColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apikey.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAPIKeysIDs(); len(nodes) > 0 && !_u.mutation.APIKeysCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   team.APIKeysTable,
			Columns: []string{team.APIKeysColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apikey.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.APIKeysIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   team.APIKeysTable,
			Columns: []string{team.APIKeysColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apikey.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UsageLogsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   team.UsageLogsTable,
			Columns: []string{team.UsageLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usagelog.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedUsageLogsIDs(); len(nodes) > 0 && !_u.mutation.UsageLogsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   team.UsageLogsTable,
			Columns: []string{team.UsageLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usagelog.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UsageLogsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   team.UsageLogsTable,
			Columns: []string{team.UsageLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usagelog.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Team{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{team.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
