// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/LuckyKuang/sub2api-plus/ent/team"
	"github.com/LuckyKuang/sub2api-plus/ent/teamownershiptransfer"
)

// TeamOwnershipTransferCreate is the builder for creating a TeamOwnershipTransfer entity.
type TeamOwnershipTransferCreate struct {
	config
	mutation *TeamOwnershipTransferMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *TeamOwnershipTransferCreate) SetCreatedAt(v time.Time) *TeamOwnershipTransferCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *TeamOwnershipTransferCreate) SetNillableCreatedAt(v *time.Time) *TeamOwnershipTransferCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *TeamOwnershipTransferCreate) SetUpdatedAt(v time.Time) *TeamOwnershipTransferCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *TeamOwnershipTransferCreate) SetNillableUpdatedAt(v *time.Time) *TeamOwnershipTransferCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetTeamID sets the "team_id" field.
func (_c *TeamOwnershipTransferCreate) SetTeamID(v int64) *TeamOwnershipTransferCreate {
	_c.mutation.SetTeamID(v)
	return _c
}

// SetFromUserID sets the "from_user_id" field.
func (_c *TeamOwnershipTransferCreate) SetFromUserID(v int64) *TeamOwnershipTransferCreate {
	_c.mutation.SetFromUserID(v)
	return _c
}

// SetToUserID sets the "to_user_id" field.
func (_c *TeamOwnershipTransferCreate) SetToUserID(v int64) *TeamOwnershipTransferCreate {
	_c.mutation.SetToUserID(v)
	return _c
}

// SetTokenHash sets the "token_hash" field.
func (_c *TeamOwnershipTransferCreate) SetTokenHash(v string) *TeamOwnershipTransferCreate {
	_c.mutation.SetTokenHash(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *TeamOwnershipTransferCreate) SetStatus(v string) *TeamOwnershipTransferCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *TeamOwnershipTransferCreate) SetNillableStatus(v *string) *TeamOwnershipTransferCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetExpiresAt sets the "expires_at" field.
func (_c *TeamOwnershipTransferCreate) SetExpiresAt(v time.Time) *TeamOwnershipTransferCreate {
	_c.mutation.SetExpiresAt(v)
	return _c
}

// SetResolvedAt sets the "resolved_at" field.
func (_c *TeamOwnershipTransferCreate) SetResolvedAt(v time.Time) *TeamOwnershipTransferCreate {
	_c.mutation.SetResolvedAt(v)
	return _c
}

// SetNillableResolvedAt sets the "resolved_at" field if the given value is not nil.
func (_c *TeamOwnershipTransferCreate) SetNillableResolvedAt(v *time.Time) *TeamOwnershipTransferCreate {
	if v != nil {
		_c.SetResolvedAt(*v)
	}
	return _c
}

// SetTeam sets the "team" edge to the Team entity.
func (_c *TeamOwnershipTransferCreate) SetTeam(v *Team) *TeamOwnershipTransferCreate {
	return _c.SetTeamID(v.ID)
}

// Mutation returns the TeamOwnershipTransferMutation object of the builder.
func (_c *TeamOwnershipTransferCreate) Mutation() *TeamOwnershipTransferMutation {
	return _c.mutation
}

// Save creates the TeamOwnershipTransfer in the database.
func (_c *TeamOwnershipTransferCreate) Save(ctx context.Context) (*TeamOwnershipTransfer, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *TeamOwnershipTransferCreate) SaveX(ctx context.Context) *TeamOwnershipTransfer {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TeamOwnershipTransferCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TeamOwnershipTransferCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *TeamOwnershipTransferCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := teamownershiptransfer.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := teamownershiptransfer.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := teamownershiptransfer.DefaultStatus
		_c.mutation.SetStatus(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *TeamOwnershipTransferCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "TeamOwnershipTransfer.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "TeamOwnershipTransfer.updated_at"`)}
	}
	if _, ok := _c.mutation.TeamID(); !ok {
		return &ValidationError{Name: "team_id", err: errors.New(`ent: missing required field "TeamOwnershipTransfer.team_id"`)}
	}
	if _, ok := _c.mutation.FromUserID(); !ok {
		return &ValidationError{Name: "from_user_id", err: errors.New(`ent: missing required field "TeamOwnershipTransfer.from_user_id"`)}
	}
	if _, ok := _c.mutation.ToUserID(); !ok {
		return &ValidationError{Name: "to_user_id", err: errors.New(`ent: missing required field "TeamOwnershipTransfer.to_user_id"`)}
	}
	if _, ok := _c.mutation.TokenHash(); !ok {
		return &ValidationError{Name: "token_hash", err: errors.New(`ent: missing required field "TeamOwnershipTransfer.token_hash"`)}
	}
	if v, ok := _c.mutation.TokenHash(); ok {
		if err := teamownershiptransfer.TokenHashValidator(v); err != nil {
			return &ValidationError{Name: "token_hash", err: fmt.Errorf(`ent: validator failed for field "TeamOwnershipTransfer.token_hash": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "TeamOwnershipTransfer.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := teamownershiptransfer.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "TeamOwnershipTransfer.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ExpiresAt(); !ok {
		return &ValidationError{Name: "expires_at", err: errors.New(`ent: missing required field "TeamOwnershipTransfer.expires_at"`)}
	}
	if len(_c.mutation.TeamIDs()) == 0 {
		return &ValidationError{Name: "team", err: errors.New(`ent: missing required edge "TeamOwnershipTransfer.team"`)}
	}
	return nil
}

func (_c *TeamOwnershipTransferCreate) sqlSave(ctx context.Context) (*TeamOwnershipTransfer, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *TeamOwnershipTransferCreate) createSpec() (*TeamOwnershipTransfer, *sqlgraph.CreateSpec) {
	var (
		_node = &TeamOwnershipTransfer{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(teamownershiptransfer.Table, sqlgraph.NewFieldSpec(teamownershiptransfer.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(teamownershiptransfer.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(teamownershiptransfer.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.FromUserID(); ok {
		_spec.SetField(teamownershiptransfer.FieldFromUserID, field.TypeInt64, value)
		_node.FromUserID = value
	}
	if value, ok := _c.mutation.ToUserID(); ok {
		_spec.SetField(teamownershiptransfer.FieldToUserID, field.TypeInt64, value)
		_node.ToUserID = value
	}
	if value, ok := _c.mutation.TokenHash(); ok {
		_spec.SetField(teamownershiptransfer.FieldTokenHash, field.TypeString, value)
		_node.TokenHash = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(teamownershiptransfer.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.ExpiresAt(); ok {
		_spec.SetField(teamownershiptransfer.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = value
	}
	if value, ok := _c.mutation.ResolvedAt(); ok {
		_spec.SetField(teamownershiptransfer.FieldResolvedAt, field.TypeTime, value)
		_node.ResolvedAt = &value
	}
	if nodes := _c.mutation.TeamIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   teamownershiptransfer.TeamTable,
			Columns: []string{teamownershiptransfer.TeamColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(team.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.TeamID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.TeamOwnershipTransfer.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.TeamOwnershipTransferUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *TeamOwnershipTransferCreate) OnConflict(opts ...sql.ConflictOption) *TeamOwnershipTransferUpsertOne {
	_c.conflict = opts
	return &TeamOwnershipTransferUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.TeamOwnershipTransfer.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *TeamOwnershipTransferCreate) OnConflictColumns(columns ...string) *TeamOwnershipTransferUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &TeamOwnershipTransferUpsertOne{
		create: _c,
	}
}

type (
	// TeamOwnershipTransferUpsertOne is the builder for "upsert"-ing
	//  one TeamOwnershipTransfer node.
	TeamOwnershipTransferUpsertOne struct {
		create *TeamOwnershipTransferCreate
	}

	// TeamOwnershipTransferUpsert is the "OnConflict" setter.
	TeamOwnershipTransferUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *TeamOwnershipTransferUpsert) SetUpdatedAt(v time.Time) *TeamOwnershipTransferUpsert {
	u.Set(teamownershiptransfer.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *TeamOwnershipTransferUpsert) UpdateUpdatedAt() *TeamOwnershipTransferUpsert {
	u.SetExcluded(teamownershiptransfer.FieldUpdatedAt)
	return u
}

// SetTeamID sets the "team_id" field.
func (u *TeamOwnershipTransferUpsert) SetTeamID(v int64) *TeamOwnershipTransferUpsert {
	u.Set(teamownershiptransfer.FieldTeamID, v)
	return u
}

// UpdateTeamID sets the "team_id" field to the value that was provided on create.
func (u *TeamOwnershipTransferUpsert) UpdateTeamID() *TeamOwnershipTransferUpsert {
	u.SetExcluded(teamownershiptransfer.FieldTeamID)
	return u
}

// SetFromUserID sets the "from_user_id" field.
func (u *TeamOwnershipTransferUpsert) SetFromUserID(v int64) *TeamOwnershipTransferUpsert {
	u.Set(teamownershiptransfer.FieldFromUserID, v)
	return u
}

// UpdateFromUserID sets the "from_user_id" field to the value that was provided on create.
func (u *TeamOwnershipTransferUpsert) UpdateFromUserID() *TeamOwnershipTransferUpsert {
	u.SetExcluded(teamownershiptransfer.FieldFromUserID)
	return u
}

// AddFromUserID adds v to the "from_user_id" field.
func (u *TeamOwnershipTransferUpsert) AddFromUserID(v int64) *TeamOwnershipTransferUpsert {
	u.Add(teamownershiptransfer.FieldFromUserID, v)
	return u
}

// SetToUserID sets the "to_user_id" field.
func (u *TeamOwnershipTransferUpsert) SetToUserID(v int64) *TeamOwnershipTransferUpsert {
	u.Set(teamownershiptransfer.FieldToUserID, v)
	return u
}

// UpdateToUserID sets the "to_user_id" field to the value that was provided on create.
func (u *TeamOwnershipTransferUpsert) UpdateToUserID() *TeamOwnershipTransferUpsert {
	u.SetExcluded(teamownershiptransfer.FieldToUserID)
	return u
}

// AddToUserID adds v to the "to_user_id" field.
func (u *TeamOwnershipTransferUpsert) AddToUserID(v int64) *TeamOwnershipTransferUpsert {
	u.Add(teamownershiptransfer.FieldToUserID, v)
	return u
}

// SetTokenHash sets the "token_hash" field.
func (u *TeamOwnershipTransferUpsert) SetTokenHash(v string) *TeamOwnershipTransferUpsert {
	u.Set(teamownershiptransfer.FieldTokenHash, v)
	return u
}

// UpdateTokenHash sets the "token_hash" field to the value that was provided on create.
func (u *TeamOwnershipTransferUpsert) UpdateTokenHash() *TeamOwnershipTransferUpsert {
	u.SetExcluded(teamownershiptransfer.FieldTokenHash)
	return u
}

// SetStatus sets the "status" field.
func (u *TeamOwnershipTransferUpsert) SetStatus(v string) *TeamOwnershipTransferUpsert {
	u.Set(teamownershiptransfer.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *TeamOwnershipTransferUpsert) UpdateStatus() *TeamOwnershipTransferUpsert {
	u.SetExcluded(teamownershiptransfer.FieldStatus)
	return u
}

// SetExpiresAt sets the "expires_at" field.
func (u *TeamOwnershipTransferUpsert) SetExpiresAt(v time.Time) *TeamOwnershipTransferUpsert {
	u.Set(teamownershiptransfer.FieldExpiresAt, v)
	return u
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *TeamOwnershipTransferUpsert) UpdateExpiresAt() *TeamOwnershipTransferUpsert {
	u.SetExcluded(teamownershiptransfer.FieldExpiresAt)
	return u
}

// SetResolvedAt sets the "resolved_at" field.
func (u *TeamOwnershipTransferUpsert) SetResolvedAt(v time.Time) *TeamOwnershipTransferUpsert {
	u.Set(teamownershiptransfer.FieldResolvedAt, v)
	return u
}

// UpdateResolvedAt sets the "resolved_at" field to the value that was provided on create.
func (u *TeamOwnershipTransferUpsert) UpdateResolvedAt() *TeamOwnershipTransferUpsert {
	u.SetExcluded(teamownershiptransfer.FieldResolvedAt)
	return u
}

// ClearResolvedAt clears the value of the "resolved_at" field.
func (u *TeamOwnershipTransferUpsert) ClearResolvedAt() *TeamOwnershipTransferUpsert {
	u.SetNull(teamownershiptransfer.FieldResolvedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.TeamOwnershipTransfer.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *TeamOwnershipTransferUpsertOne) UpdateNewValues() *TeamOwnershipTransferUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(teamownershiptransfer.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.TeamOwnershipTransfer.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *TeamOwnershipTransferUpsertOne) Ignore() *TeamOwnershipTransferUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *TeamOwnershipTransferUpsertOne) DoNothing() *TeamOwnershipTransferUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the TeamOwnershipTransferCreate.OnConflict
// documentation for more info.
func (u *TeamOwnershipTransferUpsertOne) Update(set func(*TeamOwnershipTransferUpsert)) *TeamOwnershipTransferUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&TeamOwnershipTransferUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *TeamOwnershipTransferUpsertOne) SetUpdatedAt(v time.Time) *TeamOwnershipTransferUpsertOne {
	return u.Update(func(s *TeamOwnershipTransferUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *TeamOwnershipTransferUpsertOne) UpdateUpdatedAt() *TeamOwnershipTransferUpsertOne {
	return u.Update(func(s *TeamOwnershipTransferUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetTeamID sets the "team_id" field.
func (u *TeamOwnershipTransferUpsertOne) SetTeamID(v int64) *TeamOwnershipTransferUpsertOne {
	return u.Update(func(s *TeamOwnershipTransferUpsert) {
		s.SetTeamID(v)
	})
}

// UpdateTeamID sets the "team_id" field to the value that was provided on create.
func (u *TeamOwnershipTransferUpsertOne) UpdateTeamID() *TeamOwnershipTransferUpsertOne {
	return u.Update(func(s *TeamOwnershipTransferUpsert) {
		s.UpdateTeamID()
	})
}

// SetFromUserID sets the "from_user_id" field.
func (u *TeamOwnershipTransferUpsertOne) SetFromUserID(v int64) *TeamOwnershipTransferUpsertOne {
	return u.Update(func(s *TeamOwnershipTransferUpsert) {
		s.SetFromUserID(v)
	})
}

// AddFromUserID adds v to the "from_user_id" field.
func (u *TeamOwnershipTransferUpsertOne) AddFromUserID(v int64) *TeamOwnershipTransferUpsertOne {
	return u.Update(func(s *TeamOwnershipTransferUpsert) {
		s.AddFromUserID(v)
	})
}

// UpdateFromUserID sets the "from_user_id" field to the value that was provided on create.
func (u *TeamOwnershipTransferUpsertOne) UpdateFromUserID() *TeamOwnershipTransferUpsertOne {
	return u.Update(func(s *TeamOwnershipTransferUpsert) {
		s.UpdateFromUserID()
	})
}

// SetToUserID sets the "to_user_id" field.
func (u *TeamOwnershipTransferUpsertOne) SetToUserID(v int64) *TeamOwnershipTransferUpsertOne {
	return u.Update(func(s *TeamOwnershipTransferUpsert) {
		s.SetToUserID(v)
	})
}

// AddToUserID adds v to the "to_user_id" field.
func (u *TeamOwnershipTransferUpsertOne) AddToUserID(v int64) *TeamOwnershipTransferUpsertOne {
	return u.Update(func(s *TeamOwnershipTransferUpsert) {
		s.AddToUserID(v)
	})
}

// UpdateToUserID sets the "to_user_id" field to the value that was provided on create.
func (u *TeamOwnershipTransferUpsertOne) UpdateToUserID() *TeamOwnershipTransferUpsertOne {
	return u.Update(func(s *TeamOwnershipTransferUpsert) {
		s.UpdateToUserID()
	})
}

// SetTokenHash sets the "token_hash" field.
func (u *TeamOwnershipTransferUpsertOne) SetTokenHash(v string) *TeamOwnershipTransferUpsertOne {
	return u.Update(func(s *TeamOwnershipTransferUpsert) {
		s.SetTokenHash(v)
	})
}

// UpdateTokenHash sets the "token_hash" field to the value that was provided on create.
func (u *TeamOwnershipTransferUpsertOne) UpdateTokenHash() *TeamOwnershipTransferUpsertOne {
	return u.Update(func(s *TeamOwnershipTransferUpsert) {
		s.UpdateTokenHash()
	})
}

// SetStatus sets the "status" field.
func (u *TeamOwnershipTransferUpsertOne) SetStatus(v string) *TeamOwnershipTransferUpsertOne {
	return u.Update(func(s *TeamOwnershipTransferUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *TeamOwnershipTransferUpsertOne) UpdateStatus() *TeamOwnershipTransferUpsertOne {
	return u.Update(func(s *TeamOwnershipTransferUpsert) {
		s.UpdateStatus()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *TeamOwnershipTransferUpsertOne) SetExpiresAt(v time.Time) *TeamOwnershipTransferUpsertOne {
	return u.Update(func(s *TeamOwnershipTransferUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *TeamOwnershipTransferUpsertOne) UpdateExpiresAt() *TeamOwnershipTransferUpsertOne {
	return u.Update(func(s *TeamOwnershipTransferUpsert) {
		s.UpdateExpiresAt()
	})
}

// SetResolvedAt sets the "resolved_at" field.
func (u *TeamOwnershipTransferUpsertOne) SetResolvedAt(v time.Time) *TeamOwnershipTransferUpsertOne {
	return u.Update(func(s *TeamOwnershipTransferUpsert) {
		s.SetResolvedAt(v)
	})
}

// UpdateResolvedAt sets the "resolved_at" field to the value that was provided on create.
func (u *TeamOwnershipTransferUpsertOne) UpdateResolvedAt() *TeamOwnershipTransferUpsertOne {
	return u.Update(func(s *TeamOwnershipTransferUpsert) {
		s.UpdateResolvedAt()
	})
}

// ClearResolvedAt clears the value of the "resolved_at" field.
func (u *TeamOwnershipTransferUpsertOne) ClearResolvedAt() *TeamOwnershipTransferUpsertOne {
	return u.Update(func(s *TeamOwnershipTransferUpsert) {
		s.ClearResolvedAt()
	})
}

// Exec executes the query.
func (u *TeamOwnershipTransferUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for TeamOwnershipTransferCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *TeamOwnershipTransferUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *TeamOwnershipTransferUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *TeamOwnershipTransferUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// TeamOwnershipTransferCreateBulk is the builder for creating many TeamOwnershipTransfer entities in bulk.
type TeamOwnershipTransferCreateBulk struct {
	config
	err      error
	builders []*TeamOwnershipTransferCreate
	conflict []sql.ConflictOption
}

// Save creates the TeamOwnershipTransfer entities in the database.
func (_c *TeamOwnershipTransferCreateBulk) Save(ctx context.Context) ([]*TeamOwnershipTransfer, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*TeamOwnershipTransfer, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TeamOwnershipTransferMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *TeamOwnershipTransferCreateBulk) SaveX(ctx context.Context) []*TeamOwnershipTransfer {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TeamOwnershipTransferCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TeamOwnershipTransferCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.TeamOwnershipTransfer.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.TeamOwnershipTransferUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *TeamOwnershipTransferCreateBulk) OnConflict(opts ...sql.ConflictOption) *TeamOwnershipTransferUpsertBulk {
	_c.conflict = opts
	return &TeamOwnershipTransferUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.TeamOwnershipTransfer.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *TeamOwnershipTransferCreateBulk) OnConflictColumns(columns ...string) *TeamOwnershipTransferUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &TeamOwnershipTransferUpsertBulk{
		create: _c,
	}
}

// TeamOwnershipTransferUpsertBulk is the builder for "upsert"-ing
// a bulk of TeamOwnershipTransfer nodes.
type TeamOwnershipTransferUpsertBulk struct {
	create *TeamOwnershipTransferCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.TeamOwnershipTransfer.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *TeamOwnershipTransferUpsertBulk) UpdateNewValues() *TeamOwnershipTransferUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(teamownershiptransfer.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.TeamOwnershipTransfer.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *TeamOwnershipTransferUpsertBulk) Ignore() *TeamOwnershipTransferUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *TeamOwnershipTransferUpsertBulk) DoNothing() *TeamOwnershipTransferUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the TeamOwnershipTransferCreateBulk.OnConflict
// documentation for more info.
func (u *TeamOwnershipTransferUpsertBulk) Update(set func(*TeamOwnershipTransferUpsert)) *TeamOwnershipTransferUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&TeamOwnershipTransferUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *TeamOwnershipTransferUpsertBulk) SetUpdatedAt(v time.Time) *TeamOwnershipTransferUpsertBulk {
	return u.Update(func(s *TeamOwnershipTransferUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *TeamOwnershipTransferUpsertBulk) UpdateUpdatedAt() *TeamOwnershipTransferUpsertBulk {
	return u.Update(func(s *TeamOwnershipTransferUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetTeamID sets the "team_id" field.
func (u *TeamOwnershipTransferUpsertBulk) SetTeamID(v int64) *TeamOwnershipTransferUpsertBulk {
	return u.Update(func(s *TeamOwnershipTransferUpsert) {
		s.SetTeamID(v)
	})
}

// UpdateTeamID sets the "team_id" field to the value that was provided on create.
func (u *TeamOwnershipTransferUpsertBulk) UpdateTeamID() *TeamOwnershipTransferUpsertBulk {
	return u.Update(func(s *TeamOwnershipTransferUpsert) {
		s.UpdateTeamID()
	})
}

// SetFromUserID sets the "from_user_id" field.
func (u *TeamOwnershipTransferUpsertBulk) SetFromUserID(v int64) *TeamOwnershipTransferUpsertBulk {
	return u.Update(func(s *TeamOwnershipTransferUpsert) {
		s.SetFromUserID(v)
	})
}

// AddFromUserID adds v to the "from_user_id" field.
func (u *TeamOwnershipTransferUpsertBulk) AddFromUserID(v int64) *TeamOwnershipTransferUpsertBulk {
	return u.Update(func(s *TeamOwnershipTransferUpsert) {
		s.AddFromUserID(v)
	})
}

// UpdateFromUserID sets the "from_user_id" field to the value that was provided on create.
func (u *TeamOwnershipTransferUpsertBulk) UpdateFromUserID() *TeamOwnershipTransferUpsertBulk {
	return u.Update(func(s *TeamOwnershipTransferUpsert) {
		s.UpdateFromUserID()
	})
}

// SetToUserID sets the "to_user_id" field.
func (u *TeamOwnershipTransferUpsertBulk) SetToUserID(v int64) *TeamOwnershipTransferUpsertBulk {
	return u.Update(func(s *TeamOwnershipTransferUpsert) {
		s.SetToUserID(v)
	})
}

// AddToUserID adds v to the "to_user_id" field.
func (u *TeamOwnershipTransferUpsertBulk) AddToUserID(v int64) *TeamOwnershipTransferUpsertBulk {
	return u.Update(func(s *TeamOwnershipTransferUpsert) {
		s.AddToUserID(v)
	})
}

// UpdateToUserID sets the "to_user_id" field to the value that was provided on create.
func (u *TeamOwnershipTransferUpsertBulk) UpdateToUserID() *TeamOwnershipTransferUpsertBulk {
	return u.Update(func(s *TeamOwnershipTransferUpsert) {
		s.UpdateToUserID()
	})
}

// SetTokenHash sets the "token_hash" field.
func (u *TeamOwnershipTransferUpsertBulk) SetTokenHash(v string) *TeamOwnershipTransferUpsertBulk {
	return u.Update(func(s *TeamOwnershipTransferUpsert) {
		s.SetTokenHash(v)
	})
}

// UpdateTokenHash sets the "token_hash" field to the value that was provided on create.
func (u *TeamOwnershipTransferUpsertBulk) UpdateTokenHash() *TeamOwnershipTransferUpsertBulk {
	return u.Update(func(s *TeamOwnershipTransferUpsert) {
		s.UpdateTokenHash()
	})
}

// SetStatus sets the "status" field.
func (u *TeamOwnershipTransferUpsertBulk) SetStatus(v string) *TeamOwnershipTransferUpsertBulk {
	return u.Update(func(s *TeamOwnershipTransferUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *TeamOwnershipTransferUpsertBulk) UpdateStatus() *TeamOwnershipTransferUpsertBulk {
	return u.Update(func(s *TeamOwnershipTransferUpsert) {
		s.UpdateStatus()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *TeamOwnershipTransferUpsertBulk) SetExpiresAt(v time.Time) *TeamOwnershipTransferUpsertBulk {
	return u.Update(func(s *TeamOwnershipTransferUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *TeamOwnershipTransferUpsertBulk) UpdateExpiresAt() *TeamOwnershipTransferUpsertBulk {
	return u.Update(func(s *TeamOwnershipTransferUpsert) {
		s.UpdateExpiresAt()
	})
}

// SetResolvedAt sets the "resolved_at" field.
func (u *TeamOwnershipTransferUpsertBulk) SetResolvedAt(v time.Time) *TeamOwnershipTransferUpsertBulk {
	return u.Update(func(s *TeamOwnershipTransferUpsert) {
		s.SetResolvedAt(v)
	})
}

// UpdateResolvedAt sets the "resolved_at" field to the value that was provided on create.
func (u *TeamOwnershipTransferUpsertBulk) UpdateResolvedAt() *TeamOwnershipTransferUpsertBulk {
	return u.Update(func(s *TeamOwnershipTransferUpsert) {
		s.UpdateResolvedAt()
	})
}

// ClearResolvedAt clears the value of the "resolved_at" field.
func (u *TeamOwnershipTransferUpsertBulk) ClearResolvedAt() *TeamOwnershipTransferUpsertBulk {
	return u.Update(func(s *TeamOwnershipTransferUpsert) {
		s.ClearResolvedAt()
	})
}

// Exec executes the query.
func (u *TeamOwnershipTransferUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the TeamOwnershipTransferCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for TeamOwnershipTransferCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *TeamOwnershipTransferUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
