// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/LuckyKuang/sub2api-plus/ent/team"
	"github.com/LuckyKuang/sub2api-plus/ent/teammembership"
	"github.com/LuckyKuang/sub2api-plus/ent/user"
)

// TeamMembershipCreate is the builder for creating a TeamMembership entity.
type TeamMembershipCreate struct {
	config
	mutation *TeamMembershipMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *TeamMembershipCreate) SetCreatedAt(v time.Time) *TeamMembershipCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *TeamMembershipCreate) SetNillableCreatedAt(v *time.Time) *TeamMembershipCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *TeamMembershipCreate) SetUpdatedAt(v time.Time) *TeamMembershipCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *TeamMembershipCreate) SetNillableUpdatedAt(v *time.Time) *TeamMembershipCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetTeamID sets the "team_id" field.
func (_c *TeamMembershipCreate) SetTeamID(v int64) *TeamMembershipCreate {
	_c.mutation.SetTeamID(v)
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *TeamMembershipCreate) SetUserID(v int64) *TeamMembershipCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetRole sets the "role" field.
func (_c *TeamMembershipCreate) SetRole(v string) *TeamMembershipCreate {
	_c.mutation.SetRole(v)
	return _c
}

// SetNillableRole sets the "role" field if the given value is not nil.
func (_c *TeamMembershipCreate) SetNillableRole(v *string) *TeamMembershipCreate {
	if v != nil {
		_c.SetRole(*v)
	}
	return _c
}

// SetDailyLimitUsd sets the "daily_limit_usd" field.
func (_c *TeamMembershipCreate) SetDailyLimitUsd(v float64) *TeamMembershipCreate {
	_c.mutation.SetDailyLimitUsd(v)
	return _c
}

// SetNillableDailyLimitUsd sets the "daily_limit_usd" field if the given value is not nil.
func (_c *TeamMembershipCreate) SetNillableDailyLimitUsd(v *float64) *TeamMembershipCreate {
	if v != nil {
		_c.SetDailyLimitUsd(*v)
	}
	return _c
}

// SetWeeklyLimitUsd sets the "weekly_limit_usd" field.
func (_c *TeamMembershipCreate) SetWeeklyLimitUsd(v float64) *TeamMembershipCreate {
	_c.mutation.SetWeeklyLimitUsd(v)
	return _c
}

// SetNillableWeeklyLimitUsd sets the "weekly_limit_usd" field if the given value is not nil.
func (_c *TeamMembershipCreate) SetNillableWeeklyLimitUsd(v *float64) *TeamMembershipCreate {
	if v != nil {
		_c.SetWeeklyLimitUsd(*v)
	}
	return _c
}

// SetMonthlyLimitUsd sets the "monthly_limit_usd" field.
func (_c *TeamMembershipCreate) SetMonthlyLimitUsd(v float64) *TeamMembershipCreate {
	_c.mutation.SetMonthlyLimitUsd(v)
	return _c
}

// SetNillableMonthlyLimitUsd sets the "monthly_limit_usd" field if the given value is not nil.
func (_c *TeamMembershipCreate) SetNillableMonthlyLimitUsd(v *float64) *TeamMembershipCreate {
	if v != nil {
		_c.SetMonthlyLimitUsd(*v)
	}
	return _c
}

// SetDailyUsageUsd sets the "daily_usage_usd" field.
func (_c *TeamMembershipCreate) SetDailyUsageUsd(v float64) *TeamMembershipCreate {
	_c.mutation.SetDailyUsageUsd(v)
	return _c
}

// SetNillableDailyUsageUsd sets the "daily_usage_usd" field if the given value is not nil.
func (_c *TeamMembershipCreate) SetNillableDailyUsageUsd(v *float64) *TeamMembershipCreate {
	if v != nil {
		_c.SetDailyUsageUsd(*v)
	}
	return _c
}

// SetWeeklyUsageUsd sets the "weekly_usage_usd" field.
func (_c *TeamMembershipCreate) SetWeeklyUsageUsd(v float64) *TeamMembershipCreate {
	_c.mutation.SetWeeklyUsageUsd(v)
	return _c
}

// SetNillableWeeklyUsageUsd sets the "weekly_usage_usd" field if the given value is not nil.
func (_c *TeamMembershipCreate) SetNillableWeeklyUsageUsd(v *float64) *TeamMembershipCreate {
	if v != nil {
		_c.SetWeeklyUsageUsd(*v)
	}
	return _c
}

// SetMonthlyUsageUsd sets the "monthly_usage_usd" field.
func (_c *TeamMembershipCreate) SetMonthlyUsageUsd(v float64) *TeamMembershipCreate {
	_c.mutation.SetMonthlyUsageUsd(v)
	return _c
}

// SetNillableMonthlyUsageUsd sets the "monthly_usage_usd" field if the given value is not nil.
func (_c *TeamMembershipCreate) SetNillableMonthlyUsageUsd(v *float64) *TeamMembershipCreate {
	if v != nil {
		_c.SetMonthlyUsageUsd(*v)
	}
	return _c
}

// SetDailyWindowStart sets the "daily_window_start" field.
func (_c *TeamMembershipCreate) SetDailyWindowStart(v time.Time) *TeamMembershipCreate {
	_c.mutation.SetDailyWindowStart(v)
	return _c
}

// SetNillableDailyWindowStart sets the "daily_window_start" field if the given value is not nil.
func (_c *TeamMembershipCreate) SetNillableDailyWindowStart(v *time.Time) *TeamMembershipCreate {
	if v != nil {
		_c.SetDailyWindowStart(*v)
	}
	return _c
}

// SetWeeklyWindowStart sets the "weekly_window_start" field.
func (_c *TeamMembershipCreate) SetWeeklyWindowStart(v time.Time) *TeamMembershipCreate {
	_c.mutation.SetWeeklyWindowStart(v)
	return _c
}

// SetNillableWeeklyWindowStart sets the "weekly_window_start" field if the given value is not nil.
func (_c *TeamMembershipCreate) SetNillableWeeklyWindowStart(v *time.Time) *TeamMembershipCreate {
	if v != nil {
		_c.SetWeeklyWindowStart(*v)
	}
	return _c
}

// SetMonthlyWindowStart sets the "monthly_window_start" field.
func (_c *TeamMembershipCreate) SetMonthlyWindowStart(v time.Time) *TeamMembershipCreate {
	_c.mutation.SetMonthlyWindowStart(v)
	return _c
}

// SetNillableMonthlyWindowStart sets the "monthly_window_start" field if the given value is not nil.
func (_c *TeamMembershipCreate) SetNillableMonthlyWindowStart(v *time.Time) *TeamMembershipCreate {
	if v != nil {
		_c.SetMonthlyWindowStart(*v)
	}
	return _c
}

// SetJoinedAt sets the "joined_at" field.
func (_c *TeamMembershipCreate) SetJoinedAt(v time.Time) *TeamMembershipCreate {
	_c.mutation.SetJoinedAt(v)
	return _c
}

// SetNillableJoinedAt sets the "joined_at" field if the given value is not nil.
func (_c *TeamMembershipCreate) SetNillableJoinedAt(v *time.Time) *TeamMembershipCreate {
	if v != nil {
		_c.SetJoinedAt(*v)
	}
	return _c
}

// SetLeftAt sets the "left_at" field.
func (_c *TeamMembershipCreate) SetLeftAt(v time.Time) *TeamMembershipCreate {
	_c.mutation.SetLeftAt(v)
	return _c
}

// SetNillableLeftAt sets the "left_at" field if the given value is not nil.
func (_c *TeamMembershipCreate) SetNillableLeftAt(v *time.Time) *TeamMembershipCreate {
	if v != nil {
		_c.SetLeftAt(*v)
	}
	return _c
}

// SetTeam sets the "team" edge to the Team entity.
func (_c *TeamMembershipCreate) SetTeam(v *Team) *TeamMembershipCreate {
	return _c.SetTeamID(v.ID)
}

// SetUser sets the "user" edge to the User entity.
func (_c *TeamMembershipCreate) SetUser(v *User) *TeamMembershipCreate {
	return _c.SetUserID(v.ID)
}

// Mutation returns the TeamMembershipMutation object of the builder.
func (_c *TeamMembershipCreate) Mutation() *TeamMembershipMutation {
	return _c.mutation
}

// Save creates the TeamMembership in the database.
func (_c *TeamMembershipCreate) Save(ctx context.Context) (*TeamMembership, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *TeamMembershipCreate) SaveX(ctx context.Context) *TeamMembership {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TeamMembershipCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TeamMembershipCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *TeamMembershipCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := teammembership.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := teammembership.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Role(); !ok {
		v := teammembership.DefaultRole
		_c.mutation.SetRole(v)
	}
	if _, ok := _c.mutation.DailyLimitUsd(); !ok {
		v := teammembership.DefaultDailyLimitUsd
		_c.mutation.SetDailyLimitUsd(v)
	}
	if _, ok := _c.mutation.WeeklyLimitUsd(); !ok {
		v := teammembership.DefaultWeeklyLimitUsd
		_c.mutation.SetWeeklyLimitUsd(v)
	}
	if _, ok := _c.mutation.MonthlyLimitUsd(); !ok {
		v := teammembership.DefaultMonthlyLimitUsd
		_c.mutation.SetMonthlyLimitUsd(v)
	}
	if _, ok := _c.mutation.DailyUsageUsd(); !ok {
		v := teammembership.DefaultDailyUsageUsd
		_c.mutation.SetDailyUsageUsd(v)
	}
	if _, ok := _c.mutation.WeeklyUsageUsd(); !ok {
		v := teammembership.DefaultWeeklyUsageUsd
		_c.mutation.SetWeeklyUsageUsd(v)
	}
	if _, ok := _c.mutation.MonthlyUsageUsd(); !ok {
		v := teammembership.DefaultMonthlyUsageUsd
		_c.mutation.SetMonthlyUsageUsd(v)
	}
	if _, ok := _c.mutation.JoinedAt(); !ok {
		v := teammembership.DefaultJoinedAt()
		_c.mutation.SetJoinedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *TeamMembershipCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "TeamMembership.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "TeamMembership.updated_at"`)}
	}
	if _, ok := _c.mutation.TeamID(); !ok {
		return &ValidationError{Name: "team_id", err: errors.New(`ent: missing required field "TeamMembership.team_id"`)}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "TeamMembership.user_id"`)}
	}
	if _, ok := _c.mutation.Role(); !ok {
		return &ValidationError{Name: "role", err: errors.New(`ent: missing required field "TeamMembership.role"`)}
	}
	if v, ok := _c.mutation.Role(); ok {
		if err := teammembership.RoleValidator(v); err != nil {
			return &ValidationError{Name: "role", err: fmt.Errorf(`ent: validator failed for field "TeamMembership.role": %w`, err)}
		}
	}
	if _, ok := _c.mutation.DailyLimitUsd(); !ok {
		return &ValidationError{Name: "daily_limit_usd", err: errors.New(`ent: missing required field "TeamMembership.daily_limit_usd"`)}
	}
	if v, ok := _c.mutation.DailyLimitUsd(); ok {
		if err := teammembership.DailyLimitUsdValidator(v); err != nil {
			return &ValidationError{Name: "daily_limit_usd", err: fmt.Errorf(`ent: validator failed for field "TeamMembership.daily_limit_usd": %w`, err)}
		}
	}
	if _, ok := _c.mutation.WeeklyLimitUsd(); !ok {
		return &ValidationError{Name: "weekly_limit_usd", err: errors.New(`ent: missing required field "TeamMembership.weekly_limit_usd"`)}
	}
	if v, ok := _c.mutation.WeeklyLimitUsd(); ok {
		if err := teammembership.WeeklyLimitUsdValidator(v); err != nil {
			return &ValidationError{Name: "weekly_limit_usd", err: fmt.Errorf(`ent: validator failed for field "TeamMembership.weekly_limit_usd": %w`, err)}
		}
	}
	if _, ok := _c.mutation.MonthlyLimitUsd(); !ok {
		return &ValidationError{Name: "monthly_limit_usd", err: errors.New(`ent: missing required field "TeamMembership.monthly_limit_usd"`)}
	}
	if v, ok := _c.mutation.MonthlyLimitUsd(); ok {
		if err := teammembership.MonthlyLimitUsdValidator(v); err != nil {
			return &ValidationError{Name: "monthly_limit_usd", err: fmt.Errorf(`ent: validator failed for field "TeamMembership.monthly_limit_usd": %w`, err)}
		}
	}
	if _, ok := _c.mutation.DailyUsageUsd(); !ok {
		return &ValidationError{Name: "daily_usage_usd", err: errors.New(`ent: missing required field "TeamMembership.daily_usage_usd"`)}
	}
	if v, ok := _c.mutation.DailyUsageUsd(); ok {
		if err := teammembership.DailyUsageUsdValidator(v); err != nil {
			return &ValidationError{Name: "daily_usage_usd", err: fmt.Errorf(`ent: validator failed for field "TeamMembership.daily_usage_usd": %w`, err)}
		}
	}
	if _, ok := _c.mutation.WeeklyUsageUsd(); !ok {
		return &ValidationError{Name: "weekly_usage_usd", err: errors.New(`ent: missing required field "TeamMembership.weekly_usage_usd"`)}
	}
	if v, ok := _c.mutation.WeeklyUsageUsd(); ok {
		if err := teammembership.WeeklyUsageUsdValidator(v); err != nil {
			return &ValidationError{Name: "weekly_usage_usd", err: fmt.Errorf(`ent: validator failed for field "TeamMembership.weekly_usage_usd": %w`, err)}
		}
	}
	if _, ok := _c.mutation.MonthlyUsageUsd(); !ok {
		return &ValidationError{Name: "monthly_usage_usd", err: errors.New(`ent: missing required field "TeamMembership.monthly_usage_usd"`)}
	}
	if v, ok := _c.mutation.MonthlyUsageUsd(); ok {
		if err := teammembership.MonthlyUsageUsdValidator(v); err != nil {
			return &ValidationError{Name: "monthly_usage_usd", err: fmt.Errorf(`ent: validator failed for field "TeamMembership.monthly_usage_usd": %w`, err)}
		}
	}
	if _, ok := _c.mutation.JoinedAt(); !ok {
		return &ValidationError{Name: "joined_at", err: errors.New(`ent: missing required field "TeamMembership.joined_at"`)}
	}
	if len(_c.mutation.TeamIDs()) == 0 {
		return &ValidationError{Name: "team", err: errors.New(`ent: missing required edge "TeamMembership.team"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "TeamMembership.user"`)}
	}
	return nil
}

func (_c *TeamMembershipCreate) sqlSave(ctx context.Context) (*TeamMembership, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *TeamMembershipCreate) createSpec() (*TeamMembership, *sqlgraph.CreateSpec) {
	var (
		_node = &TeamMembership{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(teammembership.Table, sqlgraph.NewFieldSpec(teammembership.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(teammembership.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(teammembership.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.Role(); ok {
		_spec.SetField(teammembership.FieldRole, field.TypeString, value)
		_node.Role = value
	}
	if value, ok := _c.mutation.DailyLimitUsd(); ok {
		_spec.SetField(teammembership.FieldDailyLimitUsd, field.TypeFloat64, value)
		_node.DailyLimitUsd = value
	}
	if value, ok := _c.mutation.WeeklyLimitUsd(); ok {
		_spec.SetField(teammembership.FieldWeeklyLimitUsd, field.TypeFloat64, value)
		_node.WeeklyLimitUsd = value
	}
	if value, ok := _c.mutation.MonthlyLimitUsd(); ok {
		_spec.SetField(teammembership.FieldMonthlyLimitUsd, field.TypeFloat64, value)
		_node.MonthlyLimitUsd = value
	}
	if value, ok := _c.mutation.DailyUsageUsd(); ok {
		_spec.SetField(teammembership.FieldDailyUsageUsd, field.TypeFloat64, value)
		_node.DailyUsageUsd = value
	}
	if value, ok := _c.mutation.WeeklyUsageUsd(); ok {
		_spec.SetField(teammembership.FieldWeeklyUsageUsd, field.TypeFloat64, value)
		_node.WeeklyUsageUsd = value
	}
	if value, ok := _c.mutation.MonthlyUsageUsd(); ok {
		_spec.SetField(teammembership.FieldMonthlyUsageUsd, field.TypeFloat64, value)
		_node.MonthlyUsageUsd = value
	}
	if value, ok := _c.mutation.DailyWindowStart(); ok {
		_spec.SetField(teammembership.FieldDailyWindowStart, field.TypeTime, value)
		_node.DailyWindowStart = &value
	}
	if value, ok := _c.mutation.WeeklyWindowStart(); ok {
		_spec.SetField(teammembership.FieldWeeklyWindowStart, field.TypeTime, value)
		_node.WeeklyWindowStart = &value
	}
	if value, ok := _c.mutation.MonthlyWindowStart(); ok {
		_spec.SetField(teammembership.FieldMonthlyWindowStart, field.TypeTime, value)
		_node.MonthlyWindowStart = &value
	}
	if value, ok := _c.mutation.JoinedAt(); ok {
		_spec.SetField(teammembership.FieldJoinedAt, field.TypeTime, value)
		_node.JoinedAt = value
	}
	if value, ok := _c.mutation.LeftAt(); ok {
		_spec.SetField(teammembership.FieldLeftAt, field.TypeTime, value)
		_node.LeftAt = &value
	}
	if nodes := _c.mutation.TeamIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   teammembership.TeamTable,
			Columns: []string{teammembership.TeamColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(team.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.TeamID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   teammembership.UserTable,
			Columns: []string{teammembership.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.TeamMembership.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.TeamMembershipUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *TeamMembershipCreate) OnConflict(opts ...sql.ConflictOption) *TeamMembershipUpsertOne {
	_c.conflict = opts
	return &TeamMembershipUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.TeamMembership.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *TeamMembershipCreate) OnConflictColumns(columns ...string) *TeamMembershipUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &TeamMembershipUpsertOne{
		create: _c,
	}
}

type (
	// TeamMembershipUpsertOne is the builder for "upsert"-ing
	//  one TeamMembership node.
	TeamMembershipUpsertOne struct {
		create *TeamMembershipCreate
	}

	// TeamMembershipUpsert is the "OnConflict" setter.
	TeamMembershipUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *TeamMembershipUpsert) SetUpdatedAt(v time.Time) *TeamMembershipUpsert {
	u.Set(teammembership.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *TeamMembershipUpsert) UpdateUpdatedAt() *TeamMembershipUpsert {
	u.SetExcluded(teammembership.FieldUpdatedAt)
	return u
}

// SetTeamID sets the "team_id" field.
func (u *TeamMembershipUpsert) SetTeamID(v int64) *TeamMembershipUpsert {
	u.Set(teammembership.FieldTeamID, v)
	return u
}

// UpdateTeamID sets the "team_id" field to the value that was provided on create.
func (u *TeamMembershipUpsert) UpdateTeamID() *TeamMembershipUpsert {
	u.SetExcluded(teammembership.FieldTeamID)
	return u
}

// SetUserID sets the "user_id" field.
func (u *TeamMembershipUpsert) SetUserID(v int64) *TeamMembershipUpsert {
	u.Set(teammembership.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *TeamMembershipUpsert) UpdateUserID() *TeamMembershipUpsert {
	u.SetExcluded(teammembership.FieldUserID)
	return u
}

// SetRole sets the "role" field.
func (u *TeamMembershipUpsert) SetRole(v string) *TeamMembershipUpsert {
	u.Set(teammembership.FieldRole, v)
	return u
}

// UpdateRole sets the "role" field to the value that was provided on create.
func (u *TeamMembershipUpsert) UpdateRole() *TeamMembershipUpsert {
	u.SetExcluded(teammembership.FieldRole)
	return u
}

// SetDailyLimitUsd sets the "daily_limit_usd" field.
func (u *TeamMembershipUpsert) SetDailyLimitUsd(v float64) *TeamMembershipUpsert {
	u.Set(teammembership.FieldDailyLimitUsd, v)
	return u
}

// UpdateDailyLimitUsd sets the "daily_limit_usd" field to the value that was provided on create.
func (u *TeamMembershipUpsert) UpdateDailyLimitUsd() *TeamMembershipUpsert {
	u.SetExcluded(teammembership.FieldDailyLimitUsd)
	return u
}

// AddDailyLimitUsd adds v to the "daily_limit_usd" field.
func (u *TeamMembershipUpsert) AddDailyLimitUsd(v float64) *TeamMembershipUpsert {
	u.Add(teammembership.FieldDailyLimitUsd, v)
	return u
}

// SetWeeklyLimitUsd sets the "weekly_limit_usd" field.
func (u *TeamMembershipUpsert) SetWeeklyLimitUsd(v float64) *TeamMembershipUpsert {
	u.Set(teammembership.FieldWeeklyLimitUsd, v)
	return u
}

// UpdateWeeklyLimitUsd sets the "weekly_limit_usd" field to the value that was provided on create.
func (u *TeamMembershipUpsert) UpdateWeeklyLimitUsd() *TeamMembershipUpsert {
	u.SetExcluded(teammembership.FieldWeeklyLimitUsd)
	return u
}

// AddWeeklyLimitUsd adds v to the "weekly_limit_usd" field.
func (u *TeamMembershipUpsert) AddWeeklyLimitUsd(v float64) *TeamMembershipUpsert {
	u.Add(teammembership.FieldWeeklyLimitUsd, v)
	return u
}

// SetMonthlyLimitUsd sets the "monthly_limit_usd" field.
func (u *TeamMembershipUpsert) SetMonthlyLimitUsd(v float64) *TeamMembershipUpsert {
	u.Set(teammembership.FieldMonthlyLimitUsd, v)
	return u
}

// UpdateMonthlyLimitUsd sets the "monthly_limit_usd" field to the value that was provided on create.
func (u *TeamMembershipUpsert) UpdateMonthlyLimitUsd() *TeamMembershipUpsert {
	u.SetExcluded(teammembership.FieldMonthlyLimitUsd)
	return u
}

// AddMonthlyLimitUsd adds v to the "monthly_limit_usd" field.
func (u *TeamMembershipUpsert) AddMonthlyLimitUsd(v float64) *TeamMembershipUpsert {
	u.Add(teammembership.FieldMonthlyLimitUsd, v)
	return u
}

// SetDailyUsageUsd sets the "daily_usage_usd" field.
func (u *TeamMembershipUpsert) SetDailyUsageUsd(v float64) *TeamMembershipUpsert {
	u.Set(teammembership.FieldDailyUsageUsd, v)
	return u
}

// UpdateDailyUsageUsd sets the "daily_usage_usd" field to the value that was provided on create.
func (u *TeamMembershipUpsert) UpdateDailyUsageUsd() *TeamMembershipUpsert {
	u.SetExcluded(teammembership.FieldDailyUsageUsd)
	return u
}

// AddDailyUsageUsd adds v to the "daily_usage_usd" field.
func (u *TeamMembershipUpsert) AddDailyUsageUsd(v float64) *TeamMembershipUpsert {
	u.Add(teammembership.FieldDailyUsageUsd, v)
	return u
}

// SetWeeklyUsageUsd sets the "weekly_usage_usd" field.
func (u *TeamMembershipUpsert) SetWeeklyUsageUsd(v float64) *TeamMembershipUpsert {
	u.Set(teammembership.FieldWeeklyUsageUsd, v)
	return u
}

// UpdateWeeklyUsageUsd sets the "weekly_usage_usd" field to the value that was provided on create.
func (u *TeamMembershipUpsert) UpdateWeeklyUsageUsd() *TeamMembershipUpsert {
	u.SetExcluded(teammembership.FieldWeeklyUsageUsd)
	return u
}

// AddWeeklyUsageUsd adds v to the "weekly_usage_usd" field.
func (u *TeamMembershipUpsert) AddWeeklyUsageUsd(v float64) *TeamMembershipUpsert {
	u.Add(teammembership.FieldWeeklyUsageUsd, v)
	return u
}

// SetMonthlyUsageUsd sets the "monthly_usage_usd" field.
func (u *TeamMembershipUpsert) SetMonthlyUsageUsd(v float64) *TeamMembershipUpsert {
	u.Set(teammembership.FieldMonthlyUsageUsd, v)
	return u
}

// UpdateMonthlyUsageUsd sets the "monthly_usage_usd" field to the value that was provided on create.
func (u *TeamMembershipUpsert) UpdateMonthlyUsageUsd() *TeamMembershipUpsert {
	u.SetExcluded(teammembership.FieldMonthlyUsageUsd)
	return u
}

// AddMonthlyUsageUsd adds v to the "monthly_usage_usd" field.
func (u *TeamMembershipUpsert) AddMonthlyUsageUsd(v float64) *TeamMembershipUpsert {
	u.Add(teammembership.FieldMonthlyUsageUsd, v)
	return u
}

// SetDailyWindowStart sets the "daily_window_start" field.
func (u *TeamMembershipUpsert) SetDailyWindowStart(v time.Time) *TeamMembershipUpsert {
	u.Set(teammembership.FieldDailyWindowStart, v)
	return u
}

// UpdateDailyWindowStart sets the "daily_window_start" field to the value that was provided on create.
func (u *TeamMembershipUpsert) UpdateDailyWindowStart() *TeamMembershipUpsert {
	u.SetExcluded(teammembership.FieldDailyWindowStart)
	return u
}

// ClearDailyWindowStart clears the value of the "daily_window_start" field.
func (u *TeamMembershipUpsert) ClearDailyWindowStart() *TeamMembershipUpsert {
	u.SetNull(teammembership.FieldDailyWindowStart)
	return u
}

// SetWeeklyWindowStart sets the "weekly_window_start" field.
func (u *TeamMembershipUpsert) SetWeeklyWindowStart(v time.Time) *TeamMembershipUpsert {
	u.Set(teammembership.FieldWeeklyWindowStart, v)
	return u
}

// UpdateWeeklyWindowStart sets the "weekly_window_start" field to the value that was provided on create.
func (u *TeamMembershipUpsert) UpdateWeeklyWindowStart() *TeamMembershipUpsert {
	u.SetExcluded(teammembership.FieldWeeklyWindowStart)
	return u
}

// ClearWeeklyWindowStart clears the value of the "weekly_window_start" field.
func (u *TeamMembershipUpsert) ClearWeeklyWindowStart() *TeamMembershipUpsert {
	u.SetNull(teammembership.FieldWeeklyWindowStart)
	return u
}

// SetMonthlyWindowStart sets the "monthly_window_start" field.
func (u *TeamMembershipUpsert) SetMonthlyWindowStart(v time.Time) *TeamMembershipUpsert {
	u.Set(teammembership.FieldMonthlyWindowStart, v)
	return u
}

// UpdateMonthlyWindowStart sets the "monthly_window_start" field to the value that was provided on create.
func (u *TeamMembershipUpsert) UpdateMonthlyWindowStart() *TeamMembershipUpsert {
	u.SetExcluded(teammembership.FieldMonthlyWindowStart)
	return u
}

// ClearMonthlyWindowStart clears the value of the "monthly_window_start" field.
func (u *TeamMembershipUpsert) ClearMonthlyWindowStart() *TeamMembershipUpsert {
	u.SetNull(teammembership.FieldMonthlyWindowStart)
	return u
}

// SetJoinedAt sets the "joined_at" field.
func (u *TeamMembershipUpsert) SetJoinedAt(v time.Time) *TeamMembershipUpsert {
	u.Set(teammembership.FieldJoinedAt, v)
	return u
}

// UpdateJoinedAt sets the "joined_at" field to the value that was provided on create.
func (u *TeamMembershipUpsert) UpdateJoinedAt() *TeamMembershipUpsert {
	u.SetExcluded(teammembership.FieldJoinedAt)
	return u
}

// SetLeftAt sets the "left_at" field.
func (u *TeamMembershipUpsert) SetLeftAt(v time.Time) *TeamMembershipUpsert {
	u.Set(teammembership.FieldLeftAt, v)
	return u
}

// UpdateLeftAt sets the "left_at" field to the value that was provided on create.
func (u *TeamMembershipUpsert) UpdateLeftAt() *TeamMembershipUpsert {
	u.SetExcluded(teammembership.FieldLeftAt)
	return u
}

// ClearLeftAt clears the value of the "left_at" field.
func (u *TeamMembershipUpsert) ClearLeftAt() *TeamMembershipUpsert {
	u.SetNull(teammembership.FieldLeftAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.TeamMembership.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *TeamMembershipUpsertOne) UpdateNewValues() *TeamMembershipUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(teammembership.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.TeamMembership.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *TeamMembershipUpsertOne) Ignore() *TeamMembershipUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *TeamMembershipUpsertOne) DoNothing() *TeamMembershipUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the TeamMembershipCreate.OnConflict
// documentation for more info.
func (u *TeamMembershipUpsertOne) Update(set func(*TeamMembershipUpsert)) *TeamMembershipUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&TeamMembershipUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *TeamMembershipUpsertOne) SetUpdatedAt(v time.Time) *TeamMembershipUpsertOne {
	return u.Update(func(s *TeamMembershipUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *TeamMembershipUpsertOne) UpdateUpdatedAt() *TeamMembershipUpsertOne {
	return u.Update(func(s *TeamMembershipUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetTeamID sets the "team_id" field.
func (u *TeamMembershipUpsertOne) SetTeamID(v int64) *TeamMembershipUpsertOne {
	return u.Update(func(s *TeamMembershipUpsert) {
		s.SetTeamID(v)
	})
}

// UpdateTeamID sets the "team_id" field to the value that was provided on create.
func (u *TeamMembershipUpsertOne) UpdateTeamID() *TeamMembershipUpsertOne {
	return u.Update(func(s *TeamMembershipUpsert) {
		s.UpdateTeamID()
	})
}

// SetUserID sets the "user_id" field.
func (u *TeamMembershipUpsertOne) SetUserID(v int64) *TeamMembershipUpsertOne {
	return u.Update(func(s *TeamMembershipUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *TeamMembershipUpsertOne) UpdateUserID() *TeamMembershipUpsertOne {
	return u.Update(func(s *TeamMembershipUpsert) {
		s.UpdateUserID()
	})
}

// SetRole sets the "role" field.
func (u *TeamMembershipUpsertOne) SetRole(v string) *TeamMembershipUpsertOne {
	return u.Update(func(s *TeamMembershipUpsert) {
		s.SetRole(v)
	})
}

// UpdateRole sets the "role" field to the value that was provided on create.
func (u *TeamMembershipUpsertOne) UpdateRole() *TeamMembershipUpsertOne {
	return u.Update(func(s *TeamMembershipUpsert) {
		s.UpdateRole()
	})
}

// SetDailyLimitUsd sets the "daily_limit_usd" field.
func (u *TeamMembershipUpsertOne) SetDailyLimitUsd(v float64) *TeamMembershipUpsertOne {
	return u.Update(func(s *TeamMembershipUpsert) {
		s.SetDailyLimitUsd(v)
	})
}

// AddDailyLimitUsd adds v to the "daily_limit_usd" field.
func (u *TeamMembershipUpsertOne) AddDailyLimitUsd(v float64) *TeamMembershipUpsertOne {
	return u.Update(func(s *TeamMembershipUpsert) {
		s.AddDailyLimitUsd(v)
	})
}

// UpdateDailyLimitUsd sets the "daily_limit_usd" field to the value that was provided on create.
func (u *TeamMembershipUpsertOne) UpdateDailyLimitUsd() *TeamMembershipUpsertOne {
	return u.Update(func(s *TeamMembershipUpsert) {
		s.UpdateDailyLimitUsd()
	})
}

// SetWeeklyLimitUsd sets the "weekly_limit_usd" field.
func (u *TeamMembershipUpsertOne) SetWeeklyLimitUsd(v float64) *TeamMembershipUpsertOne {
	return u.Update(func(s *TeamMembershipUpsert) {
		s.SetWeeklyLimitUsd(v)
	})
}

// AddWeeklyLimitUsd adds v to the "weekly_limit_usd" field.
func (u *TeamMembershipUpsertOne) AddWeeklyLimitUsd(v float64) *TeamMembershipUpsertOne {
	return u.Update(func(s *TeamMembershipUpsert) {
		s.AddWeeklyLimitUsd(v)
	})
}

// UpdateWeeklyLimitUsd sets the "weekly_limit_usd" field to the value that was provided on create.
func (u *TeamMembershipUpsertOne) UpdateWeeklyLimitUsd() *TeamMembershipUpsertOne {
	return u.Update(func(s *TeamMembershipUpsert) {
		s.UpdateWeeklyLimitUsd()
	})
}

// SetMonthlyLimitUsd sets the "monthly_limit_usd" field.
func (u *TeamMembershipUpsertOne) SetMonthlyLimitUsd(v float64) *TeamMembershipUpsertOne {
	return u.Update(func(s *TeamMembershipUpsert) {
		s.SetMonthlyLimitUsd(v)
	})
}

// AddMonthlyLimitUsd adds v to the "monthly_limit_usd" field.
func (u *TeamMembershipUpsertOne) AddMonthlyLimitUsd(v float64) *TeamMembershipUpsertOne {
	return u.Update(func(s *TeamMembershipUpsert) {
		s.AddMonthlyLimitUsd(v)
	})
}

// UpdateMonthlyLimitUsd sets the "monthly_limit_usd" field to the value that was provided on create.
func (u *TeamMembershipUpsertOne) UpdateMonthlyLimitUsd() *TeamMembershipUpsertOne {
	return u.Update(func(s *TeamMembershipUpsert) {
		s.UpdateMonthlyLimitUsd()
	})
}

// SetDailyUsageUsd sets the "daily_usage_usd" field.
func (u *TeamMembershipUpsertOne) SetDailyUsageUsd(v float64) *TeamMembershipUpsertOne {
	return u.Update(func(s *TeamMembershipUpsert) {
		s.SetDailyUsageUsd(v)
	})
}

// AddDailyUsageUsd adds v to the "daily_usage_usd" field.
func (u *TeamMembershipUpsertOne) AddDailyUsageUsd(v float64) *TeamMembershipUpsertOne {
	return u.Update(func(s *TeamMembershipUpsert) {
		s.AddDailyUsageUsd(v)
	})
}

// UpdateDailyUsageUsd sets the "daily_usage_usd" field to the value that was provided on create.
func (u *TeamMembershipUpsertOne) UpdateDailyUsageUsd() *TeamMembershipUpsertOne {
	return u.Update(func(s *TeamMembershipUpsert) {
		s.UpdateDailyUsageUsd()
	})
}

// SetWeeklyUsageUsd sets the "weekly_usage_usd" field.
func (u *TeamMembershipUpsertOne) SetWeeklyUsageUsd(v float64) *TeamMembershipUpsertOne {
	return u.Update(func(s *TeamMembershipUpsert) {
		s.SetWeeklyUsageUsd(v)
	})
}

// AddWeeklyUsageUsd adds v to the "weekly_usage_usd" field.
func (u *TeamMembershipUpsertOne) AddWeeklyUsageUsd(v float64) *TeamMembershipUpsertOne {
	return u.Update(func(s *TeamMembershipUpsert) {
		s.AddWeeklyUsageUsd(v)
	})
}

// UpdateWeeklyUsageUsd sets the "weekly_usage_usd" field to the value that was provided on create.
func (u *TeamMembershipUpsertOne) UpdateWeeklyUsageUsd() *TeamMembershipUpsertOne {
	return u.Update(func(s *TeamMembershipUpsert) {
		s.UpdateWeeklyUsageUsd()
	})
}

// SetMonthlyUsageUsd sets the "monthly_usage_usd" field.
func (u *TeamMembershipUpsertOne) SetMonthlyUsageUsd(v float64) *TeamMembershipUpsertOne {
	return u.Update(func(s *TeamMembershipUpsert) {
		s.SetMonthlyUsageUsd(v)
	})
}

// AddMonthlyUsageUsd adds v to the "monthly_usage_usd" field.
func (u *TeamMembershipUpsertOne) AddMonthlyUsageUsd(v float64) *TeamMembershipUpsertOne {
	return u.Update(func(s *TeamMembershipUpsert) {
		s.AddMonthlyUsageUsd(v)
	})
}

// UpdateMonthlyUsageUsd sets the "monthly_usage_usd" field to the value that was provided on create.
func (u *TeamMembershipUpsertOne) UpdateMonthlyUsageUsd() *TeamMembershipUpsertOne {
	return u.Update(func(s *TeamMembershipUpsert) {
		s.UpdateMonthlyUsageUsd()
	})
}

// SetDailyWindowStart sets the "daily_window_start" field.
func (u *TeamMembershipUpsertOne) SetDailyWindowStart(v time.Time) *TeamMembershipUpsertOne {
	return u.Update(func(s *TeamMembershipUpsert) {
		s.SetDailyWindowStart(v)
	})
}

// UpdateDailyWindowStart sets the "daily_window_start" field to the value that was provided on create.
func (u *TeamMembershipUpsertOne) UpdateDailyWindowStart() *TeamMembershipUpsertOne {
	return u.Update(func(s *TeamMembershipUpsert) {
		s.UpdateDailyWindowStart()
	})
}

// ClearDailyWindowStart clears the value of the "daily_window_start" field.
func (u *TeamMembershipUpsertOne) ClearDailyWindowStart() *TeamMembershipUpsertOne {
	return u.Update(func(s *TeamMembershipUpsert) {
		s.ClearDailyWindowStart()
	})
}

// SetWeeklyWindowStart sets the "weekly_window_start" field.
func (u *TeamMembershipUpsertOne) SetWeeklyWindowStart(v time.Time) *TeamMembershipUpsertOne {
	return u.Update(func(s *TeamMembershipUpsert) {
		s.SetWeeklyWindowStart(v)
	})
}

// UpdateWeeklyWindowStart sets the "weekly_window_start" field to the value that was provided on create.
func (u *TeamMembershipUpsertOne) UpdateWeeklyWindowStart() *TeamMembershipUpsertOne {
	return u.Update(func(s *TeamMembershipUpsert) {
		s.UpdateWeeklyWindowStart()
	})
}

// ClearWeeklyWindowStart clears the value of the "weekly_window_start" field.
func (u *TeamMembershipUpsertOne) ClearWeeklyWindowStart() *TeamMembershipUpsertOne {
	return u.Update(func(s *TeamMembershipUpsert) {
		s.ClearWeeklyWindowStart()
	})
}

// SetMonthlyWindowStart sets the "monthly_window_start" field.
func (u *TeamMembershipUpsertOne) SetMonthlyWindowStart(v time.Time) *TeamMembershipUpsertOne {
	return u.Update(func(s *TeamMembershipUpsert) {
		s.SetMonthlyWindowStart(v)
	})
}

// UpdateMonthlyWindowStart sets the "monthly_window_start" field to the value that was provided on create.
func (u *TeamMembershipUpsertOne) UpdateMonthlyWindowStart() *TeamMembershipUpsertOne {
	return u.Update(func(s *TeamMembershipUpsert) {
		s.UpdateMonthlyWindowStart()
	})
}

// ClearMonthlyWindowStart clears the value of the "monthly_window_start" field.
func (u *TeamMembershipUpsertOne) ClearMonthlyWindowStart() *TeamMembershipUpsertOne {
	return u.Update(func(s *TeamMembershipUpsert) {
		s.ClearMonthlyWindowStart()
	})
}

// SetJoinedAt sets the "joined_at" field.
func (u *TeamMembershipUpsertOne) SetJoinedAt(v time.Time) *TeamMembershipUpsertOne {
	return u.Update(func(s *TeamMembershipUpsert) {
		s.SetJoinedAt(v)
	})
}

// UpdateJoinedAt sets the "joined_at" field to the value that was provided on create.
func (u *TeamMembershipUpsertOne) UpdateJoinedAt() *TeamMembershipUpsertOne {
	return u.Update(func(s *TeamMembershipUpsert) {
		s.UpdateJoinedAt()
	})
}

// SetLeftAt sets the "left_at" field.
func (u *TeamMembershipUpsertOne) SetLeftAt(v time.Time) *TeamMembershipUpsertOne {
	return u.Update(func(s *TeamMembershipUpsert) {
		s.SetLeftAt(v)
	})
}

// UpdateLeftAt sets the "left_at" field to the value that was provided on create.
func (u *TeamMembershipUpsertOne) UpdateLeftAt() *TeamMembershipUpsertOne {
	return u.Update(func(s *TeamMembershipUpsert) {
		s.UpdateLeftAt()
	})
}

// ClearLeftAt clears the value of the "left_at" field.
func (u *TeamMembershipUpsertOne) ClearLeftAt() *TeamMembershipUpsertOne {
	return u.Update(func(s *TeamMembershipUpsert) {
		s.ClearLeftAt()
	})
}

// Exec executes the query.
func (u *TeamMembershipUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for TeamMembershipCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *TeamMembershipUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *TeamMembershipUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *TeamMembershipUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// TeamMembershipCreateBulk is the builder for creating many TeamMembership entities in bulk.
type TeamMembershipCreateBulk struct {
	config
	err      error
	builders []*TeamMembershipCreate
	conflict []sql.ConflictOption
}

// Save creates the TeamMembership entities in the database.
func (_c *TeamMembershipCreateBulk) Save(ctx context.Context) ([]*TeamMembership, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*TeamMembership, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TeamMembershipMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *TeamMembershipCreateBulk) SaveX(ctx context.Context) []*TeamMembership {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TeamMembershipCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TeamMembershipCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.TeamMembership.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.TeamMembershipUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *TeamMembershipCreateBulk) OnConflict(opts ...sql.ConflictOption) *TeamMembershipUpsertBulk {
	_c.conflict = opts
	return &TeamMembershipUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.TeamMembership.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *TeamMembershipCreateBulk) OnConflictColumns(columns ...string) *TeamMembershipUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &TeamMembershipUpsertBulk{
		create: _c,
	}
}

// TeamMembershipUpsertBulk is the builder for "upsert"-ing
// a bulk of TeamMembership nodes.
type TeamMembershipUpsertBulk struct {
	create *TeamMembershipCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.TeamMembership.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *TeamMembershipUpsertBulk) UpdateNewValues() *TeamMembershipUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(teammembership.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.TeamMembership.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *TeamMembershipUpsertBulk) Ignore() *TeamMembershipUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *TeamMembershipUpsertBulk) DoNothing() *TeamMembershipUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the TeamMembershipCreateBulk.OnConflict
// documentation for more info.
func (u *TeamMembershipUpsertBulk) Update(set func(*TeamMembershipUpsert)) *TeamMembershipUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&TeamMembershipUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *TeamMembershipUpsertBulk) SetUpdatedAt(v time.Time) *TeamMembershipUpsertBulk {
	return u.Update(func(s *TeamMembershipUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *TeamMembershipUpsertBulk) UpdateUpdatedAt() *TeamMembershipUpsertBulk {
	return u.Update(func(s *TeamMembershipUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetTeamID sets the "team_id" field.
func (u *TeamMembershipUpsertBulk) SetTeamID(v int64) *TeamMembershipUpsertBulk {
	return u.Update(func(s *TeamMembershipUpsert) {
		s.SetTeamID(v)
	})
}

// UpdateTeamID sets the "team_id" field to the value that was provided on create.
func (u *TeamMembershipUpsertBulk) UpdateTeamID() *TeamMembershipUpsertBulk {
	return u.Update(func(s *TeamMembershipUpsert) {
		s.UpdateTeamID()
	})
}

// SetUserID sets the "user_id" field.
func (u *TeamMembershipUpsertBulk) SetUserID(v int64) *TeamMembershipUpsertBulk {
	return u.Update(func(s *TeamMembershipUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *TeamMembershipUpsertBulk) UpdateUserID() *TeamMembershipUpsertBulk {
	return u.Update(func(s *TeamMembershipUpsert) {
		s.UpdateUserID()
	})
}

// SetRole sets the "role" field.
func (u *TeamMembershipUpsertBulk) SetRole(v string) *TeamMembershipUpsertBulk {
	return u.Update(func(s *TeamMembershipUpsert) {
		s.SetRole(v)
	})
}

// UpdateRole sets the "role" field to the value that was provided on create.
func (u *TeamMembershipUpsertBulk) UpdateRole() *TeamMembershipUpsertBulk {
	return u.Update(func(s *TeamMembershipUpsert) {
		s.UpdateRole()
	})
}

// SetDailyLimitUsd sets the "daily_limit_usd" field.
func (u *TeamMembershipUpsertBulk) SetDailyLimitUsd(v float64) *TeamMembershipUpsertBulk {
	return u.Update(func(s *TeamMembershipUpsert) {
		s.SetDailyLimitUsd(v)
	})
}

// AddDailyLimitUsd adds v to the "daily_limit_usd" field.
func (u *TeamMembershipUpsertBulk) AddDailyLimitUsd(v float64) *TeamMembershipUpsertBulk {
	return u.Update(func(s *TeamMembershipUpsert) {
		s.AddDailyLimitUsd(v)
	})
}

// UpdateDailyLimitUsd sets the "daily_limit_usd" field to the value that was provided on create.
func (u *TeamMembershipUpsertBulk) UpdateDailyLimitUsd() *TeamMembershipUpsertBulk {
	return u.Update(func(s *TeamMembershipUpsert) {
		s.UpdateDailyLimitUsd()
	})
}

// SetWeeklyLimitUsd sets the "weekly_limit_usd" field.
func (u *TeamMembershipUpsertBulk) SetWeeklyLimitUsd(v float64) *TeamMembershipUpsertBulk {
	return u.Update(func(s *TeamMembershipUpsert) {
		s.SetWeeklyLimitUsd(v)
	})
}

// AddWeeklyLimitUsd adds v to the "weekly_limit_usd" field.
func (u *TeamMembershipUpsertBulk) AddWeeklyLimitUsd(v float64) *TeamMembershipUpsertBulk {
	return u.Update(func(s *TeamMembershipUpsert) {
		s.AddWeeklyLimitUsd(v)
	})
}

// UpdateWeeklyLimitUsd sets the "weekly_limit_usd" field to the value that was provided on create.
func (u *TeamMembershipUpsertBulk) UpdateWeeklyLimitUsd() *TeamMembershipUpsertBulk {
	return u.Update(func(s *TeamMembershipUpsert) {
		s.UpdateWeeklyLimitUsd()
	})
}

// SetMonthlyLimitUsd sets the "monthly_limit_usd" field.
func (u *TeamMembershipUpsertBulk) SetMonthlyLimitUsd(v float64) *TeamMembershipUpsertBulk {
	return u.Update(func(s *TeamMembershipUpsert) {
		s.SetMonthlyLimitUsd(v)
	})
}

// AddMonthlyLimitUsd adds v to the "monthly_limit_usd" field.
func (u *TeamMembershipUpsertBulk) AddMonthlyLimitUsd(v float64) *TeamMembershipUpsertBulk {
	return u.Update(func(s *TeamMembershipUpsert) {
		s.AddMonthlyLimitUsd(v)
	})
}

// UpdateMonthlyLimitUsd sets the "monthly_limit_usd" field to the value that was provided on create.
func (u *TeamMembershipUpsertBulk) UpdateMonthlyLimitUsd() *TeamMembershipUpsertBulk {
	return u.Update(func(s *TeamMembershipUpsert) {
		s.UpdateMonthlyLimitUsd()
	})
}

// SetDailyUsageUsd sets the "daily_usage_usd" field.
func (u *TeamMembershipUpsertBulk) SetDailyUsageUsd(v float64) *TeamMembershipUpsertBulk {
	return u.Update(func(s *TeamMembershipUpsert) {
		s.SetDailyUsageUsd(v)
	})
}

// AddDailyUsageUsd adds v to the "daily_usage_usd" field.
func (u *TeamMembershipUpsertBulk) AddDailyUsageUsd(v float64) *TeamMembershipUpsertBulk {
	return u.Update(func(s *TeamMembershipUpsert) {
		s.AddDailyUsageUsd(v)
	})
}

// UpdateDailyUsageUsd sets the "daily_usage_usd" field to the value that was provided on create.
func (u *TeamMembershipUpsertBulk) UpdateDailyUsageUsd() *TeamMembershipUpsertBulk {
	return u.Update(func(s *TeamMembershipUpsert) {
		s.UpdateDailyUsageUsd()
	})
}

// SetWeeklyUsageUsd sets the "weekly_usage_usd" field.
func (u *TeamMembershipUpsertBulk) SetWeeklyUsageUsd(v float64) *TeamMembershipUpsertBulk {
	return u.Update(func(s *TeamMembershipUpsert) {
		s.SetWeeklyUsageUsd(v)
	})
}

// AddWeeklyUsageUsd adds v to the "weekly_usage_usd" field.
func (u *TeamMembershipUpsertBulk) AddWeeklyUsageUsd(v float64) *TeamMembershipUpsertBulk {
	return u.Update(func(s *TeamMembershipUpsert) {
		s.AddWeeklyUsageUsd(v)
	})
}

// UpdateWeeklyUsageUsd sets the "weekly_usage_usd" field to the value that was provided on create.
func (u *TeamMembershipUpsertBulk) UpdateWeeklyUsageUsd() *TeamMembershipUpsertBulk {
	return u.Update(func(s *TeamMembershipUpsert) {
		s.UpdateWeeklyUsageUsd()
	})
}

// SetMonthlyUsageUsd sets the "monthly_usage_usd" field.
func (u *TeamMembershipUpsertBulk) SetMonthlyUsageUsd(v float64) *TeamMembershipUpsertBulk {
	return u.Update(func(s *TeamMembershipUpsert) {
		s.SetMonthlyUsageUsd(v)
	})
}

// AddMonthlyUsageUsd adds v to the "monthly_usage_usd" field.
func (u *TeamMembershipUpsertBulk) AddMonthlyUsageUsd(v float64) *TeamMembershipUpsertBulk {
	return u.Update(func(s *TeamMembershipUpsert) {
		s.AddMonthlyUsageUsd(v)
	})
}

// UpdateMonthlyUsageUsd sets the "monthly_usage_usd" field to the value that was provided on create.
func (u *TeamMembershipUpsertBulk) UpdateMonthlyUsageUsd() *TeamMembershipUpsertBulk {
	return u.Update(func(s *TeamMembershipUpsert) {
		s.UpdateMonthlyUsageUsd()
	})
}

// SetDailyWindowStart sets the "daily_window_start" field.
func (u *TeamMembershipUpsertBulk) SetDailyWindowStart(v time.Time) *TeamMembershipUpsertBulk {
	return u.Update(func(s *TeamMembershipUpsert) {
		s.SetDailyWindowStart(v)
	})
}

// UpdateDailyWindowStart sets the "daily_window_start" field to the value that was provided on create.
func (u *TeamMembershipUpsertBulk) UpdateDailyWindowStart() *TeamMembershipUpsertBulk {
	return u.Update(func(s *TeamMembershipUpsert) {
		s.UpdateDailyWindowStart()
	})
}

// ClearDailyWindowStart clears the value of the "daily_window_start" field.
func (u *TeamMembershipUpsertBulk) ClearDailyWindowStart() *TeamMembershipUpsertBulk {
	return u.Update(func(s *TeamMembershipUpsert) {
		s.ClearDailyWindowStart()
	})
}

// SetWeeklyWindowStart sets the "weekly_window_start" field.
func (u *TeamMembershipUpsertBulk) SetWeeklyWindowStart(v time.Time) *TeamMembershipUpsertBulk {
	return u.Update(func(s *TeamMembershipUpsert) {
		s.SetWeeklyWindowStart(v)
	})
}

// UpdateWeeklyWindowStart sets the "weekly_window_start" field to the value that was provided on create.
func (u *TeamMembershipUpsertBulk) UpdateWeeklyWindowStart() *TeamMembershipUpsertBulk {
	return u.Update(func(s *TeamMembershipUpsert) {
		s.UpdateWeeklyWindowStart()
	})
}

// ClearWeeklyWindowStart clears the value of the "weekly_window_start" field.
func (u *TeamMembershipUpsertBulk) ClearWeeklyWindowStart() *TeamMembershipUpsertBulk {
	return u.Update(func(s *TeamMembershipUpsert) {
		s.ClearWeeklyWindowStart()
	})
}

// SetMonthlyWindowStart sets the "monthly_window_start" field.
func (u *TeamMembershipUpsertBulk) SetMonthlyWindowStart(v time.Time) *TeamMembershipUpsertBulk {
	return u.Update(func(s *TeamMembershipUpsert) {
		s.SetMonthlyWindowStart(v)
	})
}

// UpdateMonthlyWindowStart sets the "monthly_window_start" field to the value that was provided on create.
func (u *TeamMembershipUpsertBulk) UpdateMonthlyWindowStart() *TeamMembershipUpsertBulk {
	return u.Update(func(s *TeamMembershipUpsert) {
		s.UpdateMonthlyWindowStart()
	})
}

// ClearMonthlyWindowStart clears the value of the "monthly_window_start" field.
func (u *TeamMembershipUpsertBulk) ClearMonthlyWindowStart() *TeamMembershipUpsertBulk {
	return u.Update(func(s *TeamMembershipUpsert) {
		s.ClearMonthlyWindowStart()
	})
}

// SetJoinedAt sets the "joined_at" field.
func (u *TeamMembershipUpsertBulk) SetJoinedAt(v time.Time) *TeamMembershipUpsertBulk {
	return u.Update(func(s *TeamMembershipUpsert) {
		s.SetJoinedAt(v)
	})
}

// UpdateJoinedAt sets the "joined_at" field to the value that was provided on create.
func (u *TeamMembershipUpsertBulk) UpdateJoinedAt() *TeamMembershipUpsertBulk {
	return u.Update(func(s *TeamMembershipUpsert) {
		s.UpdateJoinedAt()
	})
}

// SetLeftAt sets the "left_at" field.
func (u *TeamMembershipUpsertBulk) SetLeftAt(v time.Time) *TeamMembershipUpsertBulk {
	return u.Update(func(s *TeamMembershipUpsert) {
		s.SetLeftAt(v)
	})
}

// UpdateLeftAt sets the "left_at" field to the value that was provided on create.
func (u *TeamMembershipUpsertBulk) UpdateLeftAt() *TeamMembershipUpsertBulk {
	return u.Update(func(s *TeamMembershipUpsert) {
		s.UpdateLeftAt()
	})
}

// ClearLeftAt clears the value of the "left_at" field.
func (u *TeamMembershipUpsertBulk) ClearLeftAt() *TeamMembershipUpsertBulk {
	return u.Update(func(s *TeamMembershipUpsert) {
		s.ClearLeftAt()
	})
}

// Exec executes the query.
func (u *TeamMembershipUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the TeamMembershipCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for TeamMembershipCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *TeamMembershipUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
