// Code generated by tools/generate_release_channel.py; DO NOT EDIT.

package releasechannel

const (
	ReleaseRepository  = "skyqingname/gotocc-router"
	ReleaseImage       = "ghcr.io/skyqingname/sub2api-plus"
	UpstreamRepository = "LuckyKuang/sub2api-plus"
	UpstreamBaseline   = "v0.2.0+custom.002"
	PricingManifestURL = "https://github.com/" + ReleaseRepository + "/releases/latest/download/model-pricing-manifest.json"
)

type RuntimeFile struct {
	Path     string
	Required bool
}

var RuntimeFiles = []RuntimeFile{
	{Path: "release-channel.json", Required: true},
	{Path: "resources/model-pricing/model_prices_and_context_window.json", Required: true},
}
